unit LUX.DICOM.Tags.G0018;

interface //#################################################################### ■

uses LUX, LUX.DICOM.Tags, LUX.DICOM.VRs;

type //$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$【型】

     //$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$【レコード】

     //$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$【クラス】

     //%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% TDICOMElems0018

     TDICOMElems0018 = class( TDICOMElems )
     private
     protected
     public
       constructor Create;
     end;

//const //$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$【定数】

//var //$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$【変数】

//$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$【ルーチン】

implementation //############################################################### ■

//$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$【レコード】

//$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$【クラス】

//%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% TDICOMElems0018

//&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&& private

//&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&& protected

//&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&& public

constructor TDICOMElems0018.Create;
begin
     inherited;

     Add( $0000, [TTypeVR.vrUL], 'Acquisition Group Length' );

     // http://dicom.nema.org/medical/dicom/current/output/html/part06.html#chapter_6
     // 6 Registry of DICOM Data Elements
     Add( $0010, [TTypeVR.vrLO], 'Contrast/Bolus Agent' );
     Add( $0012, [TTypeVR.vrSQ], 'Contrast/Bolus Agent Sequence' );
     Add( $0013, [TTypeVR.vrFL], 'Contrast/Bolus T1 Relaxivity' );
     Add( $0014, [TTypeVR.vrSQ], 'Contrast/Bolus Administration Route Sequence' );
     Add( $0015, [TTypeVR.vrCS], 'Body Part Examined' );
     Add( $0020, [TTypeVR.vrCS], 'Scanning Sequence' );
     Add( $0021, [TTypeVR.vrCS], 'Sequence Variant' );
     Add( $0022, [TTypeVR.vrCS], 'Scan Options' );
     Add( $0023, [TTypeVR.vrCS], 'MR Acquisition Type' );
     Add( $0024, [TTypeVR.vrSH], 'Sequence Name' );
     Add( $0025, [TTypeVR.vrCS], 'Angio Flag' );
     Add( $0026, [TTypeVR.vrSQ], 'Intervention Drug Information Sequence' );
     Add( $0027, [TTypeVR.vrTM], 'Intervention Drug Stop Time' );
     Add( $0028, [TTypeVR.vrDS], 'Intervention Drug Dose' );
     Add( $0029, [TTypeVR.vrSQ], 'Intervention Drug Code Sequence' );
     Add( $002A, [TTypeVR.vrSQ], 'Additional Drug Sequence' );
     Add( $0030, [TTypeVR.vrLO], 'Radionuclide' );
     Add( $0031, [TTypeVR.vrLO], 'Radiopharmaceutical' );
     Add( $0032, [TTypeVR.vrDS], 'Energy Window Centerline' );
     Add( $0033, [TTypeVR.vrDS], 'Energy Window Total Width' );
     Add( $0034, [TTypeVR.vrLO], 'Intervention Drug Name' );
     Add( $0035, [TTypeVR.vrTM], 'Intervention Drug Start Time' );
     Add( $0036, [TTypeVR.vrSQ], 'Intervention Sequence' );
     Add( $0037, [TTypeVR.vrCS], 'Therapy Type' );
     Add( $0038, [TTypeVR.vrCS], 'Intervention Status' );
     Add( $0039, [TTypeVR.vrCS], 'Therapy Description' );
     Add( $003A, [TTypeVR.vrST], 'Intervention Description' );
     Add( $0040, [TTypeVR.vrIS], 'Cine Rate' );
     Add( $0042, [TTypeVR.vrCS], 'Initial Cine Run State' );
     Add( $0050, [TTypeVR.vrDS], 'Slice Thickness' );
     Add( $0060, [TTypeVR.vrDS], 'KVP' );
     Add( $0061, [TTypeVR.vrDS], '' );
     Add( $0070, [TTypeVR.vrIS], 'Counts Accumulated' );
     Add( $0071, [TTypeVR.vrCS], 'Acquisition Termination Condition' );
     Add( $0072, [TTypeVR.vrDS], 'Effective Duration' );
     Add( $0073, [TTypeVR.vrCS], 'Acquisition Start Condition' );
     Add( $0074, [TTypeVR.vrIS], 'Acquisition Start Condition Data' );
     Add( $0075, [TTypeVR.vrIS], 'Acquisition Termination Condition Data' );
     Add( $0080, [TTypeVR.vrDS], 'Repetition Time' );
     Add( $0081, [TTypeVR.vrDS], 'Echo Time' );
     Add( $0082, [TTypeVR.vrDS], 'Inversion Time' );
     Add( $0083, [TTypeVR.vrDS], 'Number of Averages' );
     Add( $0084, [TTypeVR.vrDS], 'Imaging Frequency' );
     Add( $0085, [TTypeVR.vrSH], 'Imaged Nucleus' );
     Add( $0086, [TTypeVR.vrIS], 'Echo Number(s)' );
     Add( $0087, [TTypeVR.vrDS], 'Magnetic Field Strength' );
     Add( $0088, [TTypeVR.vrDS], 'Spacing Between Slices' );
     Add( $0089, [TTypeVR.vrIS], 'Number of Phase Encoding Steps' );
     Add( $0090, [TTypeVR.vrDS], 'Data Collection Diameter' );
     Add( $0091, [TTypeVR.vrIS], 'Echo Train Length' );
     Add( $0093, [TTypeVR.vrDS], 'Percent Sampling' );
     Add( $0094, [TTypeVR.vrDS], 'Percent Phase Field of View' );
     Add( $0095, [TTypeVR.vrDS], 'Pixel Bandwidth' );
     Add( $1000, [TTypeVR.vrLO], 'Device Serial Number' );
     Add( $1002, [TTypeVR.vrUI], 'Device UID' );
     Add( $1003, [TTypeVR.vrLO], 'Device ID' );
     Add( $1004, [TTypeVR.vrLO], 'Plate ID' );
     Add( $1005, [TTypeVR.vrLO], 'Generator ID' );
     Add( $1006, [TTypeVR.vrLO], 'Grid ID' );
     Add( $1007, [TTypeVR.vrLO], 'Cassette ID' );
     Add( $1008, [TTypeVR.vrLO], 'Gantry ID' );
     Add( $1009, [TTypeVR.vrUT], 'Unique Device Identifier' );
     Add( $100A, [TTypeVR.vrSQ], 'UDI Sequence' );
     Add( $1010, [TTypeVR.vrLO], 'Secondary Capture Device ID' );
     Add( $1011, [TTypeVR.vrLO], 'Hardcopy Creation Device ID' );
     Add( $1012, [TTypeVR.vrDA], 'Date of Secondary Capture' );
     Add( $1014, [TTypeVR.vrTM], 'Time of Secondary Capture' );
     Add( $1016, [TTypeVR.vrLO], 'Secondary Capture Device Manufacturer' );
     Add( $1017, [TTypeVR.vrLO], 'Hardcopy Device Manufacturer' );
     Add( $1018, [TTypeVR.vrLO], 'Secondary Capture Device Manufacturer''s Model Name' );
     Add( $1019, [TTypeVR.vrLO], 'Secondary Capture Device Software Versions' );
     Add( $101A, [TTypeVR.vrLO], 'Hardcopy Device Software Version' );
     Add( $101B, [TTypeVR.vrLO], 'Hardcopy Device Manufacturer''s Model Name' );
     Add( $1020, [TTypeVR.vrLO], 'Software Version(s)' );
     Add( $1022, [TTypeVR.vrSH], 'Video Image Format Acquired' );
     Add( $1023, [TTypeVR.vrLO], 'Digital Image Format Acquired' );
     Add( $1030, [TTypeVR.vrLO], 'Protocol Name' );
     Add( $1040, [TTypeVR.vrLO], 'Contrast/Bolus Route' );
     Add( $1041, [TTypeVR.vrDS], 'Contrast/Bolus Volume' );
     Add( $1042, [TTypeVR.vrTM], 'Contrast/Bolus Start Time' );
     Add( $1043, [TTypeVR.vrTM], 'Contrast/Bolus Stop Time' );
     Add( $1044, [TTypeVR.vrDS], 'Contrast/Bolus Total Dose' );
     Add( $1045, [TTypeVR.vrIS], 'Syringe Counts' );
     Add( $1046, [TTypeVR.vrDS], 'Contrast Flow Rate' );
     Add( $1047, [TTypeVR.vrDS], 'Contrast Flow Duration' );
     Add( $1048, [TTypeVR.vrCS], 'Contrast/Bolus Ingredient' );
     Add( $1049, [TTypeVR.vrDS], 'Contrast/Bolus Ingredient Concentration' );
     Add( $1050, [TTypeVR.vrDS], 'Spatial Resolution' );
     Add( $1060, [TTypeVR.vrDS], 'Trigger Time' );
     Add( $1061, [TTypeVR.vrLO], 'Trigger Source or Type' );
     Add( $1062, [TTypeVR.vrIS], 'Nominal Interval' );
     Add( $1063, [TTypeVR.vrDS], 'Frame Time' );
     Add( $1064, [TTypeVR.vrLO], 'Cardiac Framing Type' );
     Add( $1065, [TTypeVR.vrDS], 'Frame Time Vector' );
     Add( $1066, [TTypeVR.vrDS], 'Frame Delay' );
     Add( $1067, [TTypeVR.vrDS], 'Image Trigger Delay' );
     Add( $1068, [TTypeVR.vrDS], 'Multiplex Group Time Offset' );
     Add( $1069, [TTypeVR.vrDS], 'Trigger Time Offset' );
     Add( $106A, [TTypeVR.vrCS], 'Synchronization Trigger' );
     Add( $106C, [TTypeVR.vrUS], 'Synchronization Channel' );
     Add( $106E, [TTypeVR.vrUL], 'Trigger Sample Position' );
     Add( $1070, [TTypeVR.vrLO], 'Radiopharmaceutical Route' );
     Add( $1071, [TTypeVR.vrDS], 'Radiopharmaceutical Volume' );
     Add( $1072, [TTypeVR.vrTM], 'Radiopharmaceutical Start Time' );
     Add( $1073, [TTypeVR.vrTM], 'Radiopharmaceutical Stop Time' );
     Add( $1074, [TTypeVR.vrDS], 'Radionuclide Total Dose' );
     Add( $1075, [TTypeVR.vrDS], 'Radionuclide Half Life' );
     Add( $1076, [TTypeVR.vrDS], 'Radionuclide Positron Fraction' );
     Add( $1077, [TTypeVR.vrDS], 'Radiopharmaceutical Specific Activity' );
     Add( $1078, [TTypeVR.vrDT], 'Radiopharmaceutical Start DateTime' );
     Add( $1079, [TTypeVR.vrDT], 'Radiopharmaceutical Stop DateTime' );
     Add( $1080, [TTypeVR.vrCS], 'Beat Rejection Flag' );
     Add( $1081, [TTypeVR.vrIS], 'Low R-R Value' );
     Add( $1082, [TTypeVR.vrIS], 'High R-R Value' );
     Add( $1083, [TTypeVR.vrIS], 'Intervals Acquired' );
     Add( $1084, [TTypeVR.vrIS], 'Intervals Rejected' );
     Add( $1085, [TTypeVR.vrLO], 'PVC Rejection' );
     Add( $1086, [TTypeVR.vrIS], 'Skip Beats' );
     Add( $1088, [TTypeVR.vrIS], 'Heart Rate' );
     Add( $1090, [TTypeVR.vrIS], 'Cardiac Number of Images' );
     Add( $1094, [TTypeVR.vrIS], 'Trigger Window' );
     Add( $1100, [TTypeVR.vrDS], 'Reconstruction Diameter' );
     Add( $1110, [TTypeVR.vrDS], 'Distance Source to Detector' );
     Add( $1111, [TTypeVR.vrDS], 'Distance Source to Patient' );
     Add( $1114, [TTypeVR.vrDS], 'Estimated Radiographic Magnification Factor' );
     Add( $1120, [TTypeVR.vrDS], 'Gantry/Detector Tilt' );
     Add( $1121, [TTypeVR.vrDS], 'Gantry/Detector Slew' );
     Add( $1130, [TTypeVR.vrDS], 'Table Height' );
     Add( $1131, [TTypeVR.vrDS], 'Table Traverse' );
     Add( $1134, [TTypeVR.vrCS], 'Table Motion' );
     Add( $1135, [TTypeVR.vrDS], 'Table Vertical Increment' );
     Add( $1136, [TTypeVR.vrDS], 'Table Lateral Increment' );
     Add( $1137, [TTypeVR.vrDS], 'Table Longitudinal Increment' );
     Add( $1138, [TTypeVR.vrDS], 'Table Angle' );
     Add( $113A, [TTypeVR.vrCS], 'Table Type' );
     Add( $1140, [TTypeVR.vrCS], 'Rotation Direction' );
     Add( $1141, [TTypeVR.vrDS], 'Angular Position' );
     Add( $1142, [TTypeVR.vrDS], 'Radial Position' );
     Add( $1143, [TTypeVR.vrDS], 'Scan Arc' );
     Add( $1144, [TTypeVR.vrDS], 'Angular Step' );
     Add( $1145, [TTypeVR.vrDS], 'Center of Rotation Offset' );
     Add( $1146, [TTypeVR.vrDS], 'Rotation Offset' );
     Add( $1147, [TTypeVR.vrCS], 'Field of View Shape' );
     Add( $1149, [TTypeVR.vrIS], 'Field of View Dimension(s)' );
     Add( $1150, [TTypeVR.vrIS], 'Exposure Time' );
     Add( $1151, [TTypeVR.vrIS], 'X-Ray Tube Current' );
     Add( $1152, [TTypeVR.vrIS], 'Exposure' );
     Add( $1153, [TTypeVR.vrIS], 'Exposure in µAs' );
     Add( $1154, [TTypeVR.vrDS], 'Average Pulse Width' );
     Add( $1155, [TTypeVR.vrCS], 'Radiation Setting' );
     Add( $1156, [TTypeVR.vrCS], 'Rectification Type' );
     Add( $115A, [TTypeVR.vrCS], 'Radiation Mode' );
     Add( $115E, [TTypeVR.vrDS], 'Image and Fluoroscopy Area Dose Product' );
     Add( $1160, [TTypeVR.vrSH], 'Filter Type' );
     Add( $1161, [TTypeVR.vrLO], 'Type of Filters' );
     Add( $1162, [TTypeVR.vrDS], 'Intensifier Size' );
     Add( $1164, [TTypeVR.vrDS], 'Imager Pixel Spacing' );
     Add( $1166, [TTypeVR.vrCS], 'Grid' );
     Add( $1170, [TTypeVR.vrIS], 'Generator Power' );
     Add( $1180, [TTypeVR.vrSH], 'Collimator/grid Name' );
     Add( $1181, [TTypeVR.vrCS], 'Collimator Type' );
     Add( $1182, [TTypeVR.vrIS], 'Focal Distance' );
     Add( $1183, [TTypeVR.vrDS], 'X Focus Center' );
     Add( $1184, [TTypeVR.vrDS], 'Y Focus Center' );
     Add( $1190, [TTypeVR.vrDS], 'Focal Spot(s)' );
     Add( $1191, [TTypeVR.vrCS], 'Anode Target Material' );
     Add( $11A0, [TTypeVR.vrDS], 'Body Part Thickness' );
     Add( $11A2, [TTypeVR.vrDS], 'Compression Force' );
     Add( $11A4, [TTypeVR.vrLO], 'Paddle Description' );
     Add( $1200, [TTypeVR.vrDA], 'Date of Last Calibration' );
     Add( $1201, [TTypeVR.vrTM], 'Time of Last Calibration' );
     Add( $1202, [TTypeVR.vrDT], 'DateTime of Last Calibration' );
     Add( $1210, [TTypeVR.vrSH], 'Convolution Kernel' );
     Add( $1240, [TTypeVR.vrIS], 'Upper/Lower Pixel Values' );
     Add( $1242, [TTypeVR.vrIS], 'Actual Frame Duration' );
     Add( $1243, [TTypeVR.vrIS], 'Count Rate' );
     Add( $1244, [TTypeVR.vrUS], 'Preferred Playback Sequencing' );
     Add( $1250, [TTypeVR.vrSH], 'Receive Coil Name' );
     Add( $1251, [TTypeVR.vrSH], 'Transmit Coil Name' );
     Add( $1260, [TTypeVR.vrSH], 'Plate Type' );
     Add( $1261, [TTypeVR.vrLO], 'Phosphor Type' );
     Add( $1271, [TTypeVR.vrFD], 'Water Equivalent Diameter' );
     Add( $1272, [TTypeVR.vrSQ], 'Water Equivalent Diameter Calculation Method Code Sequence' );
     Add( $1300, [TTypeVR.vrDS], 'Scan Velocity' );
     Add( $1301, [TTypeVR.vrCS], 'Whole Body Technique' );
     Add( $1302, [TTypeVR.vrIS], 'Scan Length' );
     Add( $1310, [TTypeVR.vrUS], 'Acquisition Matrix' );
     Add( $1312, [TTypeVR.vrCS], 'In-plane Phase Encoding Direction' );
     Add( $1314, [TTypeVR.vrDS], 'Flip Angle' );
     Add( $1315, [TTypeVR.vrCS], 'Variable Flip Angle Flag' );
     Add( $1316, [TTypeVR.vrDS], 'SAR' );
     Add( $1318, [TTypeVR.vrDS], 'dB/dt' );
     Add( $1320, [TTypeVR.vrFL], 'B1rms' );
     Add( $1400, [TTypeVR.vrLO], 'Acquisition Device Processing Description' );
     Add( $1401, [TTypeVR.vrLO], 'Acquisition Device Processing Code' );
     Add( $1402, [TTypeVR.vrCS], 'Cassette Orientation' );
     Add( $1403, [TTypeVR.vrCS], 'Cassette Size' );
     Add( $1404, [TTypeVR.vrUS], 'Exposures on Plate' );
     Add( $1405, [TTypeVR.vrIS], 'Relative X-Ray Exposure' );
     Add( $1411, [TTypeVR.vrDS], 'Exposure Index' );
     Add( $1412, [TTypeVR.vrDS], 'Target Exposure Index' );
     Add( $1413, [TTypeVR.vrDS], 'Deviation Index' );
     Add( $1450, [TTypeVR.vrDS], 'Column Angulation' );
     Add( $1460, [TTypeVR.vrDS], 'Tomo Layer Height' );
     Add( $1470, [TTypeVR.vrDS], 'Tomo Angle' );
     Add( $1480, [TTypeVR.vrDS], 'Tomo Time' );
     Add( $1490, [TTypeVR.vrCS], 'Tomo Type' );
     Add( $1491, [TTypeVR.vrCS], 'Tomo Class' );
     Add( $1495, [TTypeVR.vrIS], 'Number of Tomosynthesis Source Images' );
     Add( $1500, [TTypeVR.vrCS], 'Positioner Motion' );
     Add( $1508, [TTypeVR.vrCS], 'Positioner Type' );
     Add( $1510, [TTypeVR.vrDS], 'Positioner Primary Angle' );
     Add( $1511, [TTypeVR.vrDS], 'Positioner Secondary Angle' );
     Add( $1520, [TTypeVR.vrDS], 'Positioner Primary Angle Increment' );
     Add( $1521, [TTypeVR.vrDS], 'Positioner Secondary Angle Increment' );
     Add( $1530, [TTypeVR.vrDS], 'Detector Primary Angle' );
     Add( $1531, [TTypeVR.vrDS], 'Detector Secondary Angle' );
     Add( $1600, [TTypeVR.vrCS], 'Shutter Shape' );
     Add( $1602, [TTypeVR.vrIS], 'Shutter Left Vertical Edge' );
     Add( $1604, [TTypeVR.vrIS], 'Shutter Right Vertical Edge' );
     Add( $1606, [TTypeVR.vrIS], 'Shutter Upper Horizontal Edge' );
     Add( $1608, [TTypeVR.vrIS], 'Shutter Lower Horizontal Edge' );
     Add( $1610, [TTypeVR.vrIS], 'Center of Circular Shutter' );
     Add( $1612, [TTypeVR.vrIS], 'Radius of Circular Shutter' );
     Add( $1620, [TTypeVR.vrIS], 'Vertices of the Polygonal Shutter' );
     Add( $1622, [TTypeVR.vrUS], 'Shutter Presentation Value' );
     Add( $1623, [TTypeVR.vrUS], 'Shutter Overlay Group' );
     Add( $1624, [TTypeVR.vrUS], 'Shutter Presentation Color CIELab Value' );
     Add( $1700, [TTypeVR.vrCS], 'Collimator Shape' );
     Add( $1702, [TTypeVR.vrIS], 'Collimator Left Vertical Edge' );
     Add( $1704, [TTypeVR.vrIS], 'Collimator Right Vertical Edge' );
     Add( $1706, [TTypeVR.vrIS], 'Collimator Upper Horizontal Edge' );
     Add( $1708, [TTypeVR.vrIS], 'Collimator Lower Horizontal Edge' );
     Add( $1710, [TTypeVR.vrIS], 'Center of Circular Collimator' );
     Add( $1712, [TTypeVR.vrIS], 'Radius of Circular Collimator' );
     Add( $1720, [TTypeVR.vrIS], 'Vertices of the Polygonal Collimator' );
     Add( $1800, [TTypeVR.vrCS], 'Acquisition Time Synchronized' );
     Add( $1801, [TTypeVR.vrSH], 'Time Source' );
     Add( $1802, [TTypeVR.vrCS], 'Time Distribution Protocol' );
     Add( $1803, [TTypeVR.vrLO], 'NTP Source Address' );
     Add( $2001, [TTypeVR.vrIS], 'Page Number Vector' );
     Add( $2002, [TTypeVR.vrSH], 'Frame Label Vector' );
     Add( $2003, [TTypeVR.vrDS], 'Frame Primary Angle Vector' );
     Add( $2004, [TTypeVR.vrDS], 'Frame Secondary Angle Vector' );
     Add( $2005, [TTypeVR.vrDS], 'Slice Location Vector' );
     Add( $2006, [TTypeVR.vrSH], 'Display Window Label Vector' );
     Add( $2010, [TTypeVR.vrDS], 'Nominal Scanned Pixel Spacing' );
     Add( $2020, [TTypeVR.vrCS], 'Digitizing Device Transport Direction' );
     Add( $2030, [TTypeVR.vrDS], 'Rotation of Scanned Film' );
     Add( $2041, [TTypeVR.vrSQ], 'Biopsy Target Sequence' );
     Add( $2042, [TTypeVR.vrUI], 'Target UID' );
     Add( $2043, [TTypeVR.vrFL], 'Localizing Cursor Position' );
     Add( $2044, [TTypeVR.vrFL], 'Calculated Target Position' );
     Add( $2045, [TTypeVR.vrSH], 'Target Label' );
     Add( $2046, [TTypeVR.vrFL], 'Displayed Z Value' );
     Add( $3100, [TTypeVR.vrCS], 'IVUS Acquisition' );
     Add( $3101, [TTypeVR.vrDS], 'IVUS Pullback Rate' );
     Add( $3102, [TTypeVR.vrDS], 'IVUS Gated Rate' );
     Add( $3103, [TTypeVR.vrIS], 'IVUS Pullback Start Frame Number' );
     Add( $3104, [TTypeVR.vrIS], 'IVUS Pullback Stop Frame Number' );
     Add( $3105, [TTypeVR.vrIS], 'Lesion Number' );
     Add( $4000, [TTypeVR.vrLT], 'Acquisition Comments' );
     Add( $5000, [TTypeVR.vrSH], 'Output Power' );
     Add( $5010, [TTypeVR.vrLO], 'Transducer Data' );
     Add( $5012, [TTypeVR.vrDS], 'Focus Depth' );
     Add( $5020, [TTypeVR.vrLO], 'Processing Function' );
     Add( $5021, [TTypeVR.vrLO], 'Postprocessing Function' );
     Add( $5022, [TTypeVR.vrDS], 'Mechanical Index' );
     Add( $5024, [TTypeVR.vrDS], 'Bone Thermal Index' );
     Add( $5026, [TTypeVR.vrDS], 'Cranial Thermal Index' );
     Add( $5027, [TTypeVR.vrDS], 'Soft Tissue Thermal Index' );
     Add( $5028, [TTypeVR.vrDS], 'Soft Tissue-focus Thermal Index' );
     Add( $5029, [TTypeVR.vrDS], 'Soft Tissue-surface Thermal Index' );
     Add( $5030, [TTypeVR.vrDS], 'Dynamic Range' );
     Add( $5040, [TTypeVR.vrDS], 'Total Gain' );
     Add( $5050, [TTypeVR.vrIS], 'Depth of Scan Field' );
     Add( $5100, [TTypeVR.vrCS], 'Patient Position' );
     Add( $5101, [TTypeVR.vrCS], 'View Position' );
     Add( $5104, [TTypeVR.vrSQ], 'Projection Eponymous Name Code Sequence' );
     Add( $5210, [TTypeVR.vrDS], 'Image Transformation Matrix' );
     Add( $5212, [TTypeVR.vrDS], 'Image Translation Vector' );
     Add( $6000, [TTypeVR.vrDS], 'Sensitivity' );
     Add( $6011, [TTypeVR.vrSQ], 'Sequence of Ultrasound Regions' );
     Add( $6012, [TTypeVR.vrUS], 'Region Spatial Format' );
     Add( $6014, [TTypeVR.vrUS], 'Region Data Type' );
     Add( $6016, [TTypeVR.vrUL], 'Region Flags' );
     Add( $6018, [TTypeVR.vrUL], 'Region Location Min X0' );
     Add( $601A, [TTypeVR.vrUL], 'Region Location Min Y0' );
     Add( $601C, [TTypeVR.vrUL], 'Region Location Max X1' );
     Add( $601E, [TTypeVR.vrUL], 'Region Location Max Y1' );
     Add( $6020, [TTypeVR.vrSL], 'Reference Pixel X0' );
     Add( $6022, [TTypeVR.vrSL], 'Reference Pixel Y0' );
     Add( $6024, [TTypeVR.vrUS], 'Physical Units X Direction' );
     Add( $6026, [TTypeVR.vrUS], 'Physical Units Y Direction' );
     Add( $6028, [TTypeVR.vrFD], 'Reference Pixel Physical Value X' );
     Add( $602A, [TTypeVR.vrFD], 'Reference Pixel Physical Value Y' );
     Add( $602C, [TTypeVR.vrFD], 'Physical Delta X' );
     Add( $602E, [TTypeVR.vrFD], 'Physical Delta Y' );
     Add( $6030, [TTypeVR.vrUL], 'Transducer Frequency' );
     Add( $6031, [TTypeVR.vrCS], 'Transducer Type' );
     Add( $6032, [TTypeVR.vrUL], 'Pulse Repetition Frequency' );
     Add( $6034, [TTypeVR.vrFD], 'Doppler Correction Angle' );
     Add( $6036, [TTypeVR.vrFD], 'Steering Angle' );
     Add( $6038, [TTypeVR.vrUL], 'Doppler Sample Volume X Position (Retired)' );
     Add( $6039, [TTypeVR.vrSL], 'Doppler Sample Volume X Position' );
     Add( $603A, [TTypeVR.vrUL], 'Doppler Sample Volume Y Position (Retired)' );
     Add( $603B, [TTypeVR.vrSL], 'Doppler Sample Volume Y Position' );
     Add( $603C, [TTypeVR.vrUL], 'TM-Line Position X0 (Retired)' );
     Add( $603D, [TTypeVR.vrSL], 'TM-Line Position X0' );
     Add( $603E, [TTypeVR.vrUL], 'TM-Line Position Y0 (Retired)' );
     Add( $603F, [TTypeVR.vrSL], 'TM-Line Position Y0' );
     Add( $6040, [TTypeVR.vrUL], 'TM-Line Position X1 (Retired)' );
     Add( $6041, [TTypeVR.vrSL], 'TM-Line Position X1' );
     Add( $6042, [TTypeVR.vrUL], 'TM-Line Position Y1 (Retired)' );
     Add( $6043, [TTypeVR.vrSL], 'TM-Line Position Y1' );
     Add( $6044, [TTypeVR.vrUS], 'Pixel Component Organization' );
     Add( $6046, [TTypeVR.vrUL], 'Pixel Component Mask' );
     Add( $6048, [TTypeVR.vrUL], 'Pixel Component Range Start' );
     Add( $604A, [TTypeVR.vrUL], 'Pixel Component Range Stop' );
     Add( $604C, [TTypeVR.vrUS], 'Pixel Component Physical Units' );
     Add( $604E, [TTypeVR.vrUS], 'Pixel Component Data Type' );
     Add( $6050, [TTypeVR.vrUL], 'Number of Table Break Points' );
     Add( $6052, [TTypeVR.vrUL], 'Table of X Break Points' );
     Add( $6054, [TTypeVR.vrFD], 'Table of Y Break Points' );
     Add( $6056, [TTypeVR.vrUL], 'Number of Table Entries' );
     Add( $6058, [TTypeVR.vrUL], 'Table of Pixel Values' );
     Add( $605A, [TTypeVR.vrFL], 'Table of Parameter Values' );
     Add( $6060, [TTypeVR.vrFL], 'R Wave Time Vector' );
     Add( $7000, [TTypeVR.vrCS], 'Detector Conditions Nominal Flag' );
     Add( $7001, [TTypeVR.vrDS], 'Detector Temperature' );
     Add( $7004, [TTypeVR.vrCS], 'Detector Type' );
     Add( $7005, [TTypeVR.vrCS], 'Detector Configuration' );
     Add( $7006, [TTypeVR.vrLT], 'Detector Description' );
     Add( $7008, [TTypeVR.vrLT], 'Detector Mode' );
     Add( $700A, [TTypeVR.vrSH], 'Detector ID' );
     Add( $700C, [TTypeVR.vrDA], 'Date of Last Detector Calibration' );
     Add( $700E, [TTypeVR.vrTM], 'Time of Last Detector Calibration' );
     Add( $7010, [TTypeVR.vrIS], 'Exposures on Detector Since Last Calibration' );
     Add( $7011, [TTypeVR.vrIS], 'Exposures on Detector Since Manufactured' );
     Add( $7012, [TTypeVR.vrDS], 'Detector Time Since Last Exposure' );
     Add( $7014, [TTypeVR.vrDS], 'Detector Active Time' );
     Add( $7016, [TTypeVR.vrDS], 'Detector Activation Offset From Exposure' );
     Add( $701A, [TTypeVR.vrDS], 'Detector Binning' );
     Add( $7020, [TTypeVR.vrDS], 'Detector Element Physical Size' );
     Add( $7022, [TTypeVR.vrDS], 'Detector Element Spacing' );
     Add( $7024, [TTypeVR.vrCS], 'Detector Active Shape' );
     Add( $7026, [TTypeVR.vrDS], 'Detector Active Dimension(s)' );
     Add( $7028, [TTypeVR.vrDS], 'Detector Active Origin' );
     Add( $702A, [TTypeVR.vrLO], 'Detector Manufacturer Name' );
     Add( $702B, [TTypeVR.vrLO], 'Detector Manufacturer''s Model Name' );
     Add( $7030, [TTypeVR.vrDS], 'Field of View Origin' );
     Add( $7032, [TTypeVR.vrDS], 'Field of View Rotation' );
     Add( $7034, [TTypeVR.vrCS], 'Field of View Horizontal Flip' );
     Add( $7036, [TTypeVR.vrFL], 'Pixel Data Area Origin Relative To FOV' );
     Add( $7038, [TTypeVR.vrFL], 'Pixel Data Area Rotation Angle Relative To FOV' );
     Add( $7040, [TTypeVR.vrLT], 'Grid Absorbing Material' );
     Add( $7041, [TTypeVR.vrLT], 'Grid Spacing Material' );
     Add( $7042, [TTypeVR.vrDS], 'Grid Thickness' );
     Add( $7044, [TTypeVR.vrDS], 'Grid Pitch' );
     Add( $7046, [TTypeVR.vrIS], 'Grid Aspect Ratio' );
     Add( $7048, [TTypeVR.vrDS], 'Grid Period' );
     Add( $704C, [TTypeVR.vrDS], 'Grid Focal Distance' );
     Add( $7050, [TTypeVR.vrCS], 'Filter Material' );
     Add( $7052, [TTypeVR.vrDS], 'Filter Thickness Minimum' );
     Add( $7054, [TTypeVR.vrDS], 'Filter Thickness Maximum' );
     Add( $7056, [TTypeVR.vrFL], 'Filter Beam Path Length Minimum' );
     Add( $7058, [TTypeVR.vrFL], 'Filter Beam Path Length Maximum' );
     Add( $7060, [TTypeVR.vrCS], 'Exposure Control Mode' );
     Add( $7062, [TTypeVR.vrLT], 'Exposure Control Mode Description' );
     Add( $7064, [TTypeVR.vrCS], 'Exposure Status' );
     Add( $7065, [TTypeVR.vrDS], 'Phototimer Setting' );
     Add( $8150, [TTypeVR.vrDS], 'Exposure Time in µS' );
     Add( $8151, [TTypeVR.vrDS], 'X-Ray Tube Current in µA' );
     Add( $9004, [TTypeVR.vrCS], 'Content Qualification' );
     Add( $9005, [TTypeVR.vrSH], 'Pulse Sequence Name' );
     Add( $9006, [TTypeVR.vrSQ], 'MR Imaging Modifier Sequence' );
     Add( $9008, [TTypeVR.vrCS], 'Echo Pulse Sequence' );
     Add( $9009, [TTypeVR.vrCS], 'Inversion Recovery' );
     Add( $9010, [TTypeVR.vrCS], 'Flow Compensation' );
     Add( $9011, [TTypeVR.vrCS], 'Multiple Spin Echo' );
     Add( $9012, [TTypeVR.vrCS], 'Multi-planar Excitation' );
     Add( $9014, [TTypeVR.vrCS], 'Phase Contrast' );
     Add( $9015, [TTypeVR.vrCS], 'Time of Flight Contrast' );
     Add( $9016, [TTypeVR.vrCS], 'Spoiling' );
     Add( $9017, [TTypeVR.vrCS], 'Steady State Pulse Sequence' );
     Add( $9018, [TTypeVR.vrCS], 'Echo Planar Pulse Sequence' );
     Add( $9019, [TTypeVR.vrFD], 'Tag Angle First Axis' );
     Add( $9020, [TTypeVR.vrCS], 'Magnetization Transfer' );
     Add( $9021, [TTypeVR.vrCS], 'T2 Preparation' );
     Add( $9022, [TTypeVR.vrCS], 'Blood Signal Nulling' );
     Add( $9024, [TTypeVR.vrCS], 'Saturation Recovery' );
     Add( $9025, [TTypeVR.vrCS], 'Spectrally Selected Suppression' );
     Add( $9026, [TTypeVR.vrCS], 'Spectrally Selected Excitation' );
     Add( $9027, [TTypeVR.vrCS], 'Spatial Pre-saturation' );
     Add( $9028, [TTypeVR.vrCS], 'Tagging' );
     Add( $9029, [TTypeVR.vrCS], 'Oversampling Phase' );
     Add( $9030, [TTypeVR.vrFD], 'Tag Spacing First Dimension' );
     Add( $9032, [TTypeVR.vrCS], 'Geometry of k-Space Traversal' );
     Add( $9033, [TTypeVR.vrCS], 'Segmented k-Space Traversal' );
     Add( $9034, [TTypeVR.vrCS], 'Rectilinear Phase Encode Reordering' );
     Add( $9035, [TTypeVR.vrFD], 'Tag Thickness' );
     Add( $9036, [TTypeVR.vrCS], 'Partial Fourier Direction' );
     Add( $9037, [TTypeVR.vrCS], 'Cardiac Synchronization Technique' );
     Add( $9041, [TTypeVR.vrLO], 'Receive Coil Manufacturer Name' );
     Add( $9042, [TTypeVR.vrSQ], 'MR Receive Coil Sequence' );
     Add( $9043, [TTypeVR.vrCS], 'Receive Coil Type' );
     Add( $9044, [TTypeVR.vrCS], 'Quadrature Receive Coil' );
     Add( $9045, [TTypeVR.vrSQ], 'Multi-Coil Definition Sequence' );
     Add( $9046, [TTypeVR.vrLO], 'Multi-Coil Configuration' );
     Add( $9047, [TTypeVR.vrSH], 'Multi-Coil Element Name' );
     Add( $9048, [TTypeVR.vrCS], 'Multi-Coil Element Used' );
     Add( $9049, [TTypeVR.vrSQ], 'MR Transmit Coil Sequence' );
     Add( $9050, [TTypeVR.vrLO], 'Transmit Coil Manufacturer Name' );
     Add( $9051, [TTypeVR.vrCS], 'Transmit Coil Type' );
     Add( $9052, [TTypeVR.vrFD], 'Spectral Width' );
     Add( $9053, [TTypeVR.vrFD], 'Chemical Shift Reference' );
     Add( $9054, [TTypeVR.vrCS], 'Volume Localization Technique' );
     Add( $9058, [TTypeVR.vrUS], 'MR Acquisition Frequency Encoding Steps' );
     Add( $9059, [TTypeVR.vrCS], 'De-coupling' );
     Add( $9060, [TTypeVR.vrCS], 'De-coupled Nucleus' );
     Add( $9061, [TTypeVR.vrFD], 'De-coupling Frequency' );
     Add( $9062, [TTypeVR.vrCS], 'De-coupling Method' );
     Add( $9063, [TTypeVR.vrFD], 'De-coupling Chemical Shift Reference' );
     Add( $9064, [TTypeVR.vrCS], 'k-space Filtering' );
     Add( $9065, [TTypeVR.vrCS], 'Time Domain Filtering' );
     Add( $9066, [TTypeVR.vrUS], 'Number of Zero Fills' );
     Add( $9067, [TTypeVR.vrCS], 'Baseline Correction' );
     Add( $9069, [TTypeVR.vrFD], 'Parallel Reduction Factor In-plane' );
     Add( $9070, [TTypeVR.vrFD], 'Cardiac R-R Interval Specified' );
     Add( $9073, [TTypeVR.vrFD], 'Acquisition Duration' );
     Add( $9074, [TTypeVR.vrDT], 'Frame Acquisition DateTime' );
     Add( $9075, [TTypeVR.vrCS], 'Diffusion Directionality' );
     Add( $9076, [TTypeVR.vrSQ], 'Diffusion Gradient Direction Sequence' );
     Add( $9077, [TTypeVR.vrCS], 'Parallel Acquisition' );
     Add( $9078, [TTypeVR.vrCS], 'Parallel Acquisition Technique' );
     Add( $9079, [TTypeVR.vrFD], 'Inversion Times' );
     Add( $9080, [TTypeVR.vrST], 'Metabolite Map Description' );
     Add( $9081, [TTypeVR.vrCS], 'Partial Fourier' );
     Add( $9082, [TTypeVR.vrFD], 'Effective Echo Time' );
     Add( $9083, [TTypeVR.vrSQ], 'Metabolite Map Code Sequence' );
     Add( $9084, [TTypeVR.vrSQ], 'Chemical Shift Sequence' );
     Add( $9085, [TTypeVR.vrCS], 'Cardiac Signal Source' );
     Add( $9087, [TTypeVR.vrFD], 'Diffusion b-value' );
     Add( $9089, [TTypeVR.vrFD], 'Diffusion Gradient Orientation' );
     Add( $9090, [TTypeVR.vrFD], 'Velocity Encoding Direction' );
     Add( $9091, [TTypeVR.vrFD], 'Velocity Encoding Minimum Value' );
     Add( $9092, [TTypeVR.vrSQ], 'Velocity Encoding Acquisition Sequence' );
     Add( $9093, [TTypeVR.vrUS], 'Number of k-Space Trajectories' );
     Add( $9094, [TTypeVR.vrCS], 'Coverage of k-Space' );
     Add( $9095, [TTypeVR.vrUL], 'Spectroscopy Acquisition Phase Rows' );
     Add( $9096, [TTypeVR.vrFD], 'Parallel Reduction Factor In-plane (Retired)' );
     Add( $9098, [TTypeVR.vrFD], 'Transmitter Frequency' );
     Add( $9100, [TTypeVR.vrCS], 'Resonant Nucleus' );
     Add( $9101, [TTypeVR.vrCS], 'Frequency Correction' );
     Add( $9103, [TTypeVR.vrSQ], 'MR Spectroscopy FOV/Geometry Sequence' );
     Add( $9104, [TTypeVR.vrFD], 'Slab Thickness' );
     Add( $9105, [TTypeVR.vrFD], 'Slab Orientation' );
     Add( $9106, [TTypeVR.vrFD], 'Mid Slab Position' );
     Add( $9107, [TTypeVR.vrSQ], 'MR Spatial Saturation Sequence' );
     Add( $9112, [TTypeVR.vrSQ], 'MR Timing and Related Parameters Sequence' );
     Add( $9114, [TTypeVR.vrSQ], 'MR Echo Sequence' );
     Add( $9115, [TTypeVR.vrSQ], 'MR Modifier Sequence' );
     Add( $9117, [TTypeVR.vrSQ], 'MR Diffusion Sequence' );
     Add( $9118, [TTypeVR.vrSQ], 'Cardiac Synchronization Sequence' );
     Add( $9119, [TTypeVR.vrSQ], 'MR Averages Sequence' );
     Add( $9125, [TTypeVR.vrSQ], 'MR FOV/Geometry Sequence' );
     Add( $9126, [TTypeVR.vrSQ], 'Volume Localization Sequence' );
     Add( $9127, [TTypeVR.vrUL], 'Spectroscopy Acquisition Data Columns' );
     Add( $9147, [TTypeVR.vrCS], 'Diffusion Anisotropy Type' );
     Add( $9151, [TTypeVR.vrDT], 'Frame Reference DateTime' );
     Add( $9152, [TTypeVR.vrSQ], 'MR Metabolite Map Sequence' );
     Add( $9155, [TTypeVR.vrFD], 'Parallel Reduction Factor out-of-plane' );
     Add( $9159, [TTypeVR.vrUL], 'Spectroscopy Acquisition Out-of-plane Phase Steps' );
     Add( $9166, [TTypeVR.vrCS], 'Bulk Motion Status' );
     Add( $9168, [TTypeVR.vrFD], 'Parallel Reduction Factor Second In-plane' );
     Add( $9169, [TTypeVR.vrCS], 'Cardiac Beat Rejection Technique' );
     Add( $9170, [TTypeVR.vrCS], 'Respiratory Motion Compensation Technique' );
     Add( $9171, [TTypeVR.vrCS], 'Respiratory Signal Source' );
     Add( $9172, [TTypeVR.vrCS], 'Bulk Motion Compensation Technique' );
     Add( $9173, [TTypeVR.vrCS], 'Bulk Motion Signal Source' );
     Add( $9174, [TTypeVR.vrCS], 'Applicable Safety Standard Agency' );
     Add( $9175, [TTypeVR.vrLO], 'Applicable Safety Standard Description' );
     Add( $9176, [TTypeVR.vrSQ], 'Operating Mode Sequence' );
     Add( $9177, [TTypeVR.vrCS], 'Operating Mode Type' );
     Add( $9178, [TTypeVR.vrCS], 'Operating Mode' );
     Add( $9179, [TTypeVR.vrCS], 'Specific Absorption Rate Definition' );
     Add( $9180, [TTypeVR.vrCS], 'Gradient Output Type' );
     Add( $9181, [TTypeVR.vrFD], 'Specific Absorption Rate Value' );
     Add( $9182, [TTypeVR.vrFD], 'Gradient Output' );
     Add( $9183, [TTypeVR.vrCS], 'Flow Compensation Direction' );
     Add( $9184, [TTypeVR.vrFD], 'Tagging Delay' );
     Add( $9185, [TTypeVR.vrST], 'Respiratory Motion Compensation Technique Description' );
     Add( $9186, [TTypeVR.vrSH], 'Respiratory Signal Source ID' );
     Add( $9195, [TTypeVR.vrFD], 'Chemical Shift Minimum Integration Limit in Hz' );
     Add( $9196, [TTypeVR.vrFD], 'Chemical Shift Maximum Integration Limit in Hz' );
     Add( $9197, [TTypeVR.vrSQ], 'MR Velocity Encoding Sequence' );
     Add( $9198, [TTypeVR.vrCS], 'First Order Phase Correction' );
     Add( $9199, [TTypeVR.vrCS], 'Water Referenced Phase Correction' );
     Add( $9200, [TTypeVR.vrCS], 'MR Spectroscopy Acquisition Type' );
     Add( $9214, [TTypeVR.vrCS], 'Respiratory Cycle Position' );
     Add( $9217, [TTypeVR.vrFD], 'Velocity Encoding Maximum Value' );
     Add( $9218, [TTypeVR.vrFD], 'Tag Spacing Second Dimension' );
     Add( $9219, [TTypeVR.vrSS], 'Tag Angle Second Axis' );
     Add( $9220, [TTypeVR.vrFD], 'Frame Acquisition Duration' );
     Add( $9226, [TTypeVR.vrSQ], 'MR Image Frame Type Sequence' );
     Add( $9227, [TTypeVR.vrSQ], 'MR Spectroscopy Frame Type Sequence' );
     Add( $9231, [TTypeVR.vrUS], 'MR Acquisition Phase Encoding Steps in-plane' );
     Add( $9232, [TTypeVR.vrUS], 'MR Acquisition Phase Encoding Steps out-of-plane' );
     Add( $9234, [TTypeVR.vrUL], 'Spectroscopy Acquisition Phase Columns' );
     Add( $9236, [TTypeVR.vrCS], 'Cardiac Cycle Position' );
     Add( $9239, [TTypeVR.vrSQ], 'Specific Absorption Rate Sequence' );
     Add( $9240, [TTypeVR.vrUS], 'RF Echo Train Length' );
     Add( $9241, [TTypeVR.vrUS], 'Gradient Echo Train Length' );
     Add( $9250, [TTypeVR.vrCS], 'Arterial Spin Labeling Contrast' );
     Add( $9251, [TTypeVR.vrSQ], 'MR Arterial Spin Labeling Sequence' );
     Add( $9252, [TTypeVR.vrLO], 'ASL Technique Description' );
     Add( $9253, [TTypeVR.vrUS], 'ASL Slab Number' );
     Add( $9254, [TTypeVR.vrFD], 'ASL Slab Thickness' );
     Add( $9255, [TTypeVR.vrFD], 'ASL Slab Orientation' );
     Add( $9256, [TTypeVR.vrFD], 'ASL Mid Slab Position' );
     Add( $9257, [TTypeVR.vrCS], 'ASL Context' );
     Add( $9258, [TTypeVR.vrUL], 'ASL Pulse Train Duration' );
     Add( $9259, [TTypeVR.vrCS], 'ASL Crusher Flag' );
     Add( $925A, [TTypeVR.vrFD], 'ASL Crusher Flow Limit' );
     Add( $925B, [TTypeVR.vrLO], 'ASL Crusher Description' );
     Add( $925C, [TTypeVR.vrCS], 'ASL Bolus Cut-off Flag' );
     Add( $925D, [TTypeVR.vrSQ], 'ASL Bolus Cut-off Timing Sequence' );
     Add( $925E, [TTypeVR.vrLO], 'ASL Bolus Cut-off Technique' );
     Add( $925F, [TTypeVR.vrUL], 'ASL Bolus Cut-off Delay Time' );
     Add( $9260, [TTypeVR.vrSQ], 'ASL Slab Sequence' );
     Add( $9295, [TTypeVR.vrFD], 'Chemical Shift Minimum Integration Limit in ppm' );
     Add( $9296, [TTypeVR.vrFD], 'Chemical Shift Maximum Integration Limit in ppm' );
     Add( $9297, [TTypeVR.vrCS], 'Water Reference Acquisition' );
     Add( $9298, [TTypeVR.vrIS], 'Echo Peak Position' );
     Add( $9301, [TTypeVR.vrSQ], 'CT Acquisition Type Sequence' );
     Add( $9302, [TTypeVR.vrCS], 'Acquisition Type' );
     Add( $9303, [TTypeVR.vrFD], 'Tube Angle' );
     Add( $9304, [TTypeVR.vrSQ], 'CT Acquisition Details Sequence' );
     Add( $9305, [TTypeVR.vrFD], 'Revolution Time' );
     Add( $9306, [TTypeVR.vrFD], 'Single Collimation Width' );
     Add( $9307, [TTypeVR.vrFD], 'Total Collimation Width' );
     Add( $9308, [TTypeVR.vrSQ], 'CT Table Dynamics Sequence' );
     Add( $9309, [TTypeVR.vrFD], 'Table Speed' );
     Add( $9310, [TTypeVR.vrFD], 'Table Feed per Rotation' );
     Add( $9311, [TTypeVR.vrFD], 'Spiral Pitch Factor' );
     Add( $9312, [TTypeVR.vrSQ], 'CT Geometry Sequence' );
     Add( $9313, [TTypeVR.vrFD], 'Data Collection Center (Patient)' );
     Add( $9314, [TTypeVR.vrSQ], 'CT Reconstruction Sequence' );
     Add( $9315, [TTypeVR.vrCS], 'Reconstruction Algorithm' );
     Add( $9316, [TTypeVR.vrCS], 'Convolution Kernel Group' );
     Add( $9317, [TTypeVR.vrFD], 'Reconstruction Field of View' );
     Add( $9318, [TTypeVR.vrFD], 'Reconstruction Target Center (Patient)' );
     Add( $9319, [TTypeVR.vrFD], 'Reconstruction Angle' );
     Add( $9320, [TTypeVR.vrSH], 'Image Filter' );
     Add( $9321, [TTypeVR.vrSQ], 'CT Exposure Sequence' );
     Add( $9322, [TTypeVR.vrFD], 'Reconstruction Pixel Spacing' );
     Add( $9323, [TTypeVR.vrCS], 'Exposure Modulation Type' );
     Add( $9324, [TTypeVR.vrFD], 'Estimated Dose Saving' );
     Add( $9325, [TTypeVR.vrSQ], 'CT X-Ray Details Sequence' );
     Add( $9326, [TTypeVR.vrSQ], 'CT Position Sequence' );
     Add( $9327, [TTypeVR.vrFD], 'Table Position' );
     Add( $9328, [TTypeVR.vrFD], 'Exposure Time in ms' );
     Add( $9329, [TTypeVR.vrSQ], 'CT Image Frame Type Sequence' );
     Add( $9330, [TTypeVR.vrFD], 'X-Ray Tube Current in mA' );
     Add( $9332, [TTypeVR.vrFD], 'Exposure in mAs' );
     Add( $9333, [TTypeVR.vrCS], 'Constant Volume Flag' );
     Add( $9334, [TTypeVR.vrCS], 'Fluoroscopy Flag' );
     Add( $9335, [TTypeVR.vrFD], 'Distance Source to Data Collection Center' );
     Add( $9337, [TTypeVR.vrUS], 'Contrast/Bolus Agent Number' );
     Add( $9338, [TTypeVR.vrSQ], 'Contrast/Bolus Ingredient Code Sequence' );
     Add( $9340, [TTypeVR.vrSQ], 'Contrast Administration Profile Sequence' );
     Add( $9341, [TTypeVR.vrSQ], 'Contrast/Bolus Usage Sequence' );
     Add( $9342, [TTypeVR.vrCS], 'Contrast/Bolus Agent Administered' );
     Add( $9343, [TTypeVR.vrCS], 'Contrast/Bolus Agent Detected' );
     Add( $9344, [TTypeVR.vrCS], 'Contrast/Bolus Agent Phase' );
     Add( $9345, [TTypeVR.vrFD], 'CTDIvol' );
     Add( $9346, [TTypeVR.vrSQ], 'CTDI Phantom Type Code Sequence' );
     Add( $9351, [TTypeVR.vrFL], 'Calcium Scoring Mass Factor Patient' );
     Add( $9352, [TTypeVR.vrFL], 'Calcium Scoring Mass Factor Device' );
     Add( $9353, [TTypeVR.vrFL], 'Energy Weighting Factor' );
     Add( $9360, [TTypeVR.vrSQ], 'CT Additional X-Ray Source Sequence' );
     Add( $9401, [TTypeVR.vrSQ], 'Projection Pixel Calibration Sequence' );
     Add( $9402, [TTypeVR.vrFL], 'Distance Source to Isocenter' );
     Add( $9403, [TTypeVR.vrFL], 'Distance Object to Table Top' );
     Add( $9404, [TTypeVR.vrFL], 'Object Pixel Spacing in Center of Beam' );
     Add( $9405, [TTypeVR.vrSQ], 'Positioner Position Sequence' );
     Add( $9406, [TTypeVR.vrSQ], 'Table Position Sequence' );
     Add( $9407, [TTypeVR.vrSQ], 'Collimator Shape Sequence' );
     Add( $9410, [TTypeVR.vrCS], 'Planes in Acquisition' );
     Add( $9412, [TTypeVR.vrSQ], 'XA/XRF Frame Characteristics Sequence' );
     Add( $9417, [TTypeVR.vrSQ], 'Frame Acquisition Sequence' );
     Add( $9420, [TTypeVR.vrCS], 'X-Ray Receptor Type' );
     Add( $9423, [TTypeVR.vrLO], 'Acquisition Protocol Name' );
     Add( $9424, [TTypeVR.vrLT], 'Acquisition Protocol Description' );
     Add( $9425, [TTypeVR.vrCS], 'Contrast/Bolus Ingredient Opaque' );
     Add( $9426, [TTypeVR.vrFL], 'Distance Receptor Plane to Detector Housing' );
     Add( $9427, [TTypeVR.vrCS], 'Intensifier Active Shape' );
     Add( $9428, [TTypeVR.vrFL], 'Intensifier Active Dimension(s)' );
     Add( $9429, [TTypeVR.vrFL], 'Physical Detector Size' );
     Add( $9430, [TTypeVR.vrFL], 'Position of Isocenter Projection' );
     Add( $9432, [TTypeVR.vrSQ], 'Field of View Sequence' );
     Add( $9433, [TTypeVR.vrLO], 'Field of View Description' );
     Add( $9434, [TTypeVR.vrSQ], 'Exposure Control Sensing Regions Sequence' );
     Add( $9435, [TTypeVR.vrCS], 'Exposure Control Sensing Region Shape' );
     Add( $9436, [TTypeVR.vrSS], 'Exposure Control Sensing Region Left Vertical Edge' );
     Add( $9437, [TTypeVR.vrSS], 'Exposure Control Sensing Region Right Vertical Edge' );
     Add( $9438, [TTypeVR.vrSS], 'Exposure Control Sensing Region Upper Horizontal Edge' );
     Add( $9439, [TTypeVR.vrSS], 'Exposure Control Sensing Region Lower Horizontal Edge' );
     Add( $9440, [TTypeVR.vrSS], 'Center of Circular Exposure Control Sensing Region' );
     Add( $9441, [TTypeVR.vrUS], 'Radius of Circular Exposure Control Sensing Region' );
     Add( $9442, [TTypeVR.vrSS], 'Vertices of the Polygonal Exposure Control Sensing Region' );
     Add( $9445, [], '' );  //For some Data Elements, no Name or Keyword or VR or VM is specified; these are "placeholders" that are not assigned but will not be reused.
     Add( $9449, [TTypeVR.vrFL], 'Beam Angle' );
     Add( $9451, [TTypeVR.vrSQ], 'Frame Detector Parameters Sequence' );
     Add( $9452, [TTypeVR.vrFL], 'Calculated Anatomy Thickness' );
     Add( $9455, [TTypeVR.vrSQ], 'Calibration Sequence' );
     Add( $9456, [TTypeVR.vrSQ], 'Object Thickness Sequence' );
     Add( $9457, [TTypeVR.vrCS], 'Plane Identification' );
     Add( $9461, [TTypeVR.vrFL], 'Field of View Dimension(s) in Float' );
     Add( $9462, [TTypeVR.vrSQ], 'Isocenter Reference System Sequence' );
     Add( $9463, [TTypeVR.vrFL], 'Positioner Isocenter Primary Angle' );
     Add( $9464, [TTypeVR.vrFL], 'Positioner Isocenter Secondary Angle' );
     Add( $9465, [TTypeVR.vrFL], 'Positioner Isocenter Detector Rotation Angle' );
     Add( $9466, [TTypeVR.vrFL], 'Table X Position to Isocenter' );
     Add( $9467, [TTypeVR.vrFL], 'Table Y Position to Isocenter' );
     Add( $9468, [TTypeVR.vrFL], 'Table Z Position to Isocenter' );
     Add( $9469, [TTypeVR.vrFL], 'Table Horizontal Rotation Angle' );
     Add( $9470, [TTypeVR.vrFL], 'Table Head Tilt Angle' );
     Add( $9471, [TTypeVR.vrFL], 'Table Cradle Tilt Angle' );
     Add( $9472, [TTypeVR.vrSQ], 'Frame Display Shutter Sequence' );
     Add( $9473, [TTypeVR.vrFL], 'Acquired Image Area Dose Product' );
     Add( $9474, [TTypeVR.vrCS], 'C-arm Positioner Tabletop Relationship' );
     Add( $9476, [TTypeVR.vrSQ], 'X-Ray Geometry Sequence' );
     Add( $9477, [TTypeVR.vrSQ], 'Irradiation Event Identification Sequence' );
     Add( $9504, [TTypeVR.vrSQ], 'X-Ray 3D Frame Type Sequence' );
     Add( $9506, [TTypeVR.vrSQ], 'Contributing Sources Sequence' );
     Add( $9507, [TTypeVR.vrSQ], 'X-Ray 3D Acquisition Sequence' );
     Add( $9508, [TTypeVR.vrFL], 'Primary Positioner Scan Arc' );
     Add( $9509, [TTypeVR.vrFL], 'Secondary Positioner Scan Arc' );
     Add( $9510, [TTypeVR.vrFL], 'Primary Positioner Scan Start Angle' );
     Add( $9511, [TTypeVR.vrFL], 'Secondary Positioner Scan Start Angle' );
     Add( $9514, [TTypeVR.vrFL], 'Primary Positioner Increment' );
     Add( $9515, [TTypeVR.vrFL], 'Secondary Positioner Increment' );
     Add( $9516, [TTypeVR.vrDT], 'Start Acquisition DateTime' );
     Add( $9517, [TTypeVR.vrDT], 'End Acquisition DateTime' );
     Add( $9518, [TTypeVR.vrSS], 'Primary Positioner Increment Sign' );
     Add( $9519, [TTypeVR.vrSS], 'Secondary Positioner Increment Sign' );
     Add( $9524, [TTypeVR.vrLO], 'Application Name' );
     Add( $9525, [TTypeVR.vrLO], 'Application Version' );
     Add( $9526, [TTypeVR.vrLO], 'Application Manufacturer' );
     Add( $9527, [TTypeVR.vrCS], 'Algorithm Type' );
     Add( $9528, [TTypeVR.vrLO], 'Algorithm Description' );
     Add( $9530, [TTypeVR.vrSQ], 'X-Ray 3D Reconstruction Sequence' );
     Add( $9531, [TTypeVR.vrLO], 'Reconstruction Description' );
     Add( $9538, [TTypeVR.vrSQ], 'Per Projection Acquisition Sequence' );
     Add( $9541, [TTypeVR.vrSQ], 'Detector Position Sequence' );
     Add( $9542, [TTypeVR.vrSQ], 'X-Ray Acquisition Dose Sequence' );
     Add( $9543, [TTypeVR.vrFD], 'X-Ray Source Isocenter Primary Angle' );
     Add( $9544, [TTypeVR.vrFD], 'X-Ray Source Isocenter Secondary Angle' );
     Add( $9545, [TTypeVR.vrFD], 'Breast Support Isocenter Primary Angle' );
     Add( $9546, [TTypeVR.vrFD], 'Breast Support Isocenter Secondary Angle' );
     Add( $9547, [TTypeVR.vrFD], 'Breast Support X Position to Isocenter' );
     Add( $9548, [TTypeVR.vrFD], 'Breast Support Y Position to Isocenter' );
     Add( $9549, [TTypeVR.vrFD], 'Breast Support Z Position to Isocenter' );
     Add( $9550, [TTypeVR.vrFD], 'Detector Isocenter Primary Angle' );
     Add( $9551, [TTypeVR.vrFD], 'Detector Isocenter Secondary Angle' );
     Add( $9552, [TTypeVR.vrFD], 'Detector X Position to Isocenter' );
     Add( $9553, [TTypeVR.vrFD], 'Detector Y Position to Isocenter' );
     Add( $9554, [TTypeVR.vrFD], 'Detector Z Position to Isocenter' );
     Add( $9555, [TTypeVR.vrSQ], 'X-Ray Grid Sequence' );
     Add( $9556, [TTypeVR.vrSQ], 'X-Ray Filter Sequence' );
     Add( $9557, [TTypeVR.vrFD], 'Detector Active Area TLHC Position' );
     Add( $9558, [TTypeVR.vrFD], 'Detector Active Area Orientation' );
     Add( $9559, [TTypeVR.vrCS], 'Positioner Primary Angle Direction' );
     Add( $9601, [TTypeVR.vrSQ], 'Diffusion b-matrix Sequence' );
     Add( $9602, [TTypeVR.vrFD], 'Diffusion b-value XX' );
     Add( $9603, [TTypeVR.vrFD], 'Diffusion b-value XY' );
     Add( $9604, [TTypeVR.vrFD], 'Diffusion b-value XZ' );
     Add( $9605, [TTypeVR.vrFD], 'Diffusion b-value YY' );
     Add( $9606, [TTypeVR.vrFD], 'Diffusion b-value YZ' );
     Add( $9607, [TTypeVR.vrFD], 'Diffusion b-value ZZ' );
     Add( $9621, [TTypeVR.vrSQ], 'Functional MR Sequence' );
     Add( $9622, [TTypeVR.vrCS], 'Functional Settling Phase Frames Present' );
     Add( $9623, [TTypeVR.vrDT], 'Functional Sync Pulse' );
     Add( $9624, [TTypeVR.vrCS], 'Settling Phase Frame' );
     Add( $9701, [TTypeVR.vrDT], 'Decay Correction DateTime' );
     Add( $9715, [TTypeVR.vrFD], 'Start Density Threshold' );
     Add( $9716, [TTypeVR.vrFD], 'Start Relative Density Difference Threshold' );
     Add( $9717, [TTypeVR.vrFD], 'Start Cardiac Trigger Count Threshold' );
     Add( $9718, [TTypeVR.vrFD], 'Start Respiratory Trigger Count Threshold' );
     Add( $9719, [TTypeVR.vrFD], 'Termination Counts Threshold' );
     Add( $9720, [TTypeVR.vrFD], 'Termination Density Threshold' );
     Add( $9721, [TTypeVR.vrFD], 'Termination Relative Density Threshold' );
     Add( $9722, [TTypeVR.vrFD], 'Termination Time Threshold' );
     Add( $9723, [TTypeVR.vrFD], 'Termination Cardiac Trigger Count Threshold' );
     Add( $9724, [TTypeVR.vrFD], 'Termination Respiratory Trigger Count Threshold' );
     Add( $9725, [TTypeVR.vrCS], 'Detector Geometry' );
     Add( $9726, [TTypeVR.vrFD], 'Transverse Detector Separation' );
     Add( $9727, [TTypeVR.vrFD], 'Axial Detector Dimension' );
     Add( $9729, [TTypeVR.vrUS], 'Radiopharmaceutical Agent Number' );
     Add( $9732, [TTypeVR.vrSQ], 'PET Frame Acquisition Sequence' );
     Add( $9733, [TTypeVR.vrSQ], 'PET Detector Motion Details Sequence' );
     Add( $9734, [TTypeVR.vrSQ], 'PET Table Dynamics Sequence' );
     Add( $9735, [TTypeVR.vrSQ], 'PET Position Sequence' );
     Add( $9736, [TTypeVR.vrSQ], 'PET Frame Correction Factors Sequence' );
     Add( $9737, [TTypeVR.vrSQ], 'Radiopharmaceutical Usage Sequence' );
     Add( $9738, [TTypeVR.vrCS], 'Attenuation Correction Source' );
     Add( $9739, [TTypeVR.vrUS], 'Number of Iterations' );
     Add( $9740, [TTypeVR.vrUS], 'Number of Subsets' );
     Add( $9749, [TTypeVR.vrSQ], 'PET Reconstruction Sequence' );
     Add( $9751, [TTypeVR.vrSQ], 'PET Frame Type Sequence' );
     Add( $9755, [TTypeVR.vrCS], 'Time of Flight Information Used' );
     Add( $9756, [TTypeVR.vrCS], 'Reconstruction Type' );
     Add( $9758, [TTypeVR.vrCS], 'Decay Corrected' );
     Add( $9759, [TTypeVR.vrCS], 'Attenuation Corrected' );
     Add( $9760, [TTypeVR.vrCS], 'Scatter Corrected' );
     Add( $9761, [TTypeVR.vrCS], 'Dead Time Corrected' );
     Add( $9762, [TTypeVR.vrCS], 'Gantry Motion Corrected' );
     Add( $9763, [TTypeVR.vrCS], 'Patient Motion Corrected' );
     Add( $9764, [TTypeVR.vrCS], 'Count Loss Normalization Corrected' );
     Add( $9765, [TTypeVR.vrCS], 'Randoms Corrected' );
     Add( $9766, [TTypeVR.vrCS], 'Non-uniform Radial Sampling Corrected' );
     Add( $9767, [TTypeVR.vrCS], 'Sensitivity Calibrated' );
     Add( $9768, [TTypeVR.vrCS], 'Detector Normalization Correction' );
     Add( $9769, [TTypeVR.vrCS], 'Iterative Reconstruction Method' );
     Add( $9770, [TTypeVR.vrCS], 'Attenuation Correction Temporal Relationship' );
     Add( $9771, [TTypeVR.vrSQ], 'Patient Physiological State Sequence' );
     Add( $9772, [TTypeVR.vrSQ], 'Patient Physiological State Code Sequence' );
     Add( $9801, [TTypeVR.vrFD], 'Depth(s) of Focus' );
     Add( $9803, [TTypeVR.vrSQ], 'Excluded Intervals Sequence' );
     Add( $9804, [TTypeVR.vrDT], 'Exclusion Start DateTime' );
     Add( $9805, [TTypeVR.vrFD], 'Exclusion Duration' );
     Add( $9806, [TTypeVR.vrSQ], 'US Image Description Sequence' );
     Add( $9807, [TTypeVR.vrSQ], 'Image Data Type Sequence' );
     Add( $9808, [TTypeVR.vrCS], 'Data Type' );
     Add( $9809, [TTypeVR.vrSQ], 'Transducer Scan Pattern Code Sequence' );
     Add( $980B, [TTypeVR.vrCS], 'Aliased Data Type' );
     Add( $980C, [TTypeVR.vrCS], 'Position Measuring Device Used' );
     Add( $980D, [TTypeVR.vrSQ], 'Transducer Geometry Code Sequence' );
     Add( $980E, [TTypeVR.vrSQ], 'Transducer Beam Steering Code Sequence' );
     Add( $980F, [TTypeVR.vrSQ], 'Transducer Application Code Sequence' );
     Add( $9810, [TTypeVR.vrUS,TTypeVR.vrSS], 'Zero Velocity Pixel Value' );
     Add( $9900, [TTypeVR.vrLO], 'Reference Location Label' );
     Add( $9901, [TTypeVR.vrUT], 'Reference Location Description' );
     Add( $9902, [TTypeVR.vrSQ], 'Reference Basis Code Sequence' );
     Add( $9903, [TTypeVR.vrSQ], 'Reference Geometry Code Sequence' );
     Add( $9904, [TTypeVR.vrDS], 'Offset Distance' );
     Add( $9905, [TTypeVR.vrCS], 'Offset Direction' );
     Add( $9906, [TTypeVR.vrSQ], 'Potential Scheduled Protocol Code Sequence' );
     Add( $9907, [TTypeVR.vrSQ], 'Potential Requested Procedure Code Sequence' );
     Add( $9908, [TTypeVR.vrUC], 'Potential Reasons for Procedure' );
     Add( $9909, [TTypeVR.vrSQ], 'Potential Reasons for Procedure Code Sequence' );
     Add( $990A, [TTypeVR.vrUC], 'Potential Diagnostic Tasks' );
     Add( $990B, [TTypeVR.vrSQ], 'Contraindications Code Sequence' );
     Add( $990C, [TTypeVR.vrSQ], 'Referenced Defined Protocol Sequence' );
     Add( $990D, [TTypeVR.vrSQ], 'Referenced Performed Protocol Sequence' );
     Add( $990E, [TTypeVR.vrSQ], 'Predecessor Protocol Sequence' );
     Add( $990F, [TTypeVR.vrUT], 'Protocol Planning Information' );
     Add( $9910, [TTypeVR.vrUT], 'Protocol Design Rationale' );
     Add( $9911, [TTypeVR.vrSQ], 'Patient Specification Sequence' );
     Add( $9912, [TTypeVR.vrSQ], 'Model Specification Sequence' );
     Add( $9913, [TTypeVR.vrSQ], 'Parameters Specification Sequence' );
     Add( $9914, [TTypeVR.vrSQ], 'Instruction Sequence' );
     Add( $9915, [TTypeVR.vrUS], 'Instruction Index' );
     Add( $9916, [TTypeVR.vrLO], 'Instruction Text' );
     Add( $9917, [TTypeVR.vrUT], 'Instruction Description' );
     Add( $9918, [TTypeVR.vrCS], 'Instruction Performed Flag' );
     Add( $9919, [TTypeVR.vrDT], 'Instruction Performed DateTime' );
     Add( $991A, [TTypeVR.vrUT], 'Instruction Performance Comment' );
     Add( $991B, [TTypeVR.vrSQ], 'Patient Positioning Instruction Sequence' );
     Add( $991C, [TTypeVR.vrSQ], 'Positioning Method Code Sequence' );
     Add( $991D, [TTypeVR.vrSQ], 'Positioning Landmark Sequence' );
     Add( $991E, [TTypeVR.vrUI], 'Target Frame of Reference UID' );
     Add( $991F, [TTypeVR.vrSQ], 'Acquisition Protocol Element Specification Sequence' );
     Add( $9920, [TTypeVR.vrSQ], 'Acquisition Protocol Element Sequence' );
     Add( $9921, [TTypeVR.vrUS], 'Protocol Element Number' );
     Add( $9922, [TTypeVR.vrLO], 'Protocol Element Name' );
     Add( $9923, [TTypeVR.vrUT], 'Protocol Element Characteristics Summary' );
     Add( $9924, [TTypeVR.vrUT], 'Protocol Element Purpose' );
     Add( $9930, [TTypeVR.vrCS], 'Acquisition Motion' );
     Add( $9931, [TTypeVR.vrSQ], 'Acquisition Start Location Sequence' );
     Add( $9932, [TTypeVR.vrSQ], 'Acquisition End Location Sequence' );
     Add( $9933, [TTypeVR.vrSQ], 'Reconstruction Protocol Element Specification Sequence' );
     Add( $9934, [TTypeVR.vrSQ], 'Reconstruction Protocol Element Sequence' );
     Add( $9935, [TTypeVR.vrSQ], 'Storage Protocol Element Specification Sequence' );
     Add( $9936, [TTypeVR.vrSQ], 'Storage Protocol Element Sequence' );
     Add( $9937, [TTypeVR.vrLO], 'Requested Series Description' );
     Add( $9938, [TTypeVR.vrUS], 'Source Acquisition Protocol Element Number' );
     Add( $9939, [TTypeVR.vrUS], 'Source Acquisition Beam Number' );
     Add( $993A, [TTypeVR.vrUS], 'Source Reconstruction Protocol Element Number' );
     Add( $993B, [TTypeVR.vrSQ], 'Reconstruction Start Location Sequence' );
     Add( $993C, [TTypeVR.vrSQ], 'Reconstruction End Location Sequence' );
     Add( $993D, [TTypeVR.vrSQ], 'Reconstruction Algorithm Sequence' );
     Add( $993E, [TTypeVR.vrSQ], 'Reconstruction Target Center Location Sequence' );
     Add( $9941, [TTypeVR.vrUT], 'Image Filter Description' );
     Add( $9942, [TTypeVR.vrFD], 'CTDIvol Notification Trigger' );
     Add( $9943, [TTypeVR.vrFD], 'DLP Notification Trigger' );
     Add( $9944, [TTypeVR.vrCS], 'Auto KVP Selection Type' );
     Add( $9945, [TTypeVR.vrFD], 'Auto KVP Upper Bound' );
     Add( $9946, [TTypeVR.vrFD], 'Auto KVP Lower Bound' );
     Add( $9947, [TTypeVR.vrCS], 'Protocol Defined Patient Position' );
     Add( $A001, [TTypeVR.vrSQ], 'Contributing Equipment Sequence' );
     Add( $A002, [TTypeVR.vrDT], 'Contribution DateTime' );
     Add( $A003, [TTypeVR.vrST], 'Contribution Description' );
end;

//$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$【ルーチン】

//############################################################################## □

initialization //$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$ 初期化

finalization //$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$ 最終化

end. //######################################################################### ■
