unit LUX.DICOM.Tags.G0018;

interface //#################################################################### ■

uses LUX, LUX.DICOM.Tags, LUX.DICOM.VRs;

type //$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$【型】

     //$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$【レコード】

     //$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$【クラス】

     //%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% TdcmGrup0018

     TdcmGrup0018 = class( TdcmGrup )
     private
     protected
     public
       constructor Create;
     end;

//const //$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$【定数】

//var //$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$【変数】

//$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$【ルーチン】

implementation //############################################################### ■

//$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$【レコード】

//$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$【クラス】

//%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% TdcmGrup0018

//&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&& private

//&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&& protected

//&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&& public

constructor TdcmGrup0018.Create;
begin
     inherited;

     // http://dicom.nema.org/medical/dicom/current/output/html/part06.html#chapter_6
     // 6 Registry of DICOM Data Elements
     Add( $0010, 'ContrastBolusAgent', [TKindVR.vrLO], 'Contrast/Bolus Agent' );
     Add( $0012, 'ContrastBolusAgentSequence', [TKindVR.vrSQ], 'Contrast/Bolus Agent Sequence' );
     Add( $0013, 'ContrastBolusT1Relaxivity', [TKindVR.vrFL], 'Contrast/Bolus T1 Relaxivity' );
     Add( $0014, 'ContrastBolusAdministrationRouteSequence', [TKindVR.vrSQ], 'Contrast/Bolus Administration Route Sequence' );
     Add( $0015, 'BodyPartExamined', [TKindVR.vrCS], 'Body Part Examined' );
     Add( $0020, 'ScanningSequence', [TKindVR.vrCS], 'Scanning Sequence' );
     Add( $0021, 'SequenceVariant', [TKindVR.vrCS], 'Sequence Variant' );
     Add( $0022, 'ScanOptions', [TKindVR.vrCS], 'Scan Options' );
     Add( $0023, 'MRAcquisitionType', [TKindVR.vrCS], 'MR Acquisition Type' );
     Add( $0024, 'SequenceName', [TKindVR.vrSH], 'Sequence Name' );
     Add( $0025, 'AngioFlag', [TKindVR.vrCS], 'Angio Flag' );
     Add( $0026, 'InterventionDrugInformationSequence', [TKindVR.vrSQ], 'Intervention Drug Information Sequence' );
     Add( $0027, 'InterventionDrugStopTime', [TKindVR.vrTM], 'Intervention Drug Stop Time' );
     Add( $0028, 'InterventionDrugDose', [TKindVR.vrDS], 'Intervention Drug Dose' );
     Add( $0029, 'InterventionDrugCodeSequence', [TKindVR.vrSQ], 'Intervention Drug Code Sequence' );
     Add( $002A, 'AdditionalDrugSequence', [TKindVR.vrSQ], 'Additional Drug Sequence' );
     Add( $0030, 'Radionuclide', [TKindVR.vrLO], 'Radionuclide' );
     Add( $0031, 'Radiopharmaceutical', [TKindVR.vrLO], 'Radiopharmaceutical' );
     Add( $0032, 'EnergyWindowCenterline', [TKindVR.vrDS], 'Energy Window Centerline' );
     Add( $0033, 'EnergyWindowTotalWidth', [TKindVR.vrDS], 'Energy Window Total Width' );
     Add( $0034, 'InterventionDrugName', [TKindVR.vrLO], 'Intervention Drug Name' );
     Add( $0035, 'InterventionDrugStartTime', [TKindVR.vrTM], 'Intervention Drug Start Time' );
     Add( $0036, 'InterventionSequence', [TKindVR.vrSQ], 'Intervention Sequence' );
     Add( $0037, 'TherapyType', [TKindVR.vrCS], 'Therapy Type' );
     Add( $0038, 'InterventionStatus', [TKindVR.vrCS], 'Intervention Status' );
     Add( $0039, 'TherapyDescription', [TKindVR.vrCS], 'Therapy Description' );
     Add( $003A, 'InterventionDescription', [TKindVR.vrST], 'Intervention Description' );
     Add( $0040, 'CineRate', [TKindVR.vrIS], 'Cine Rate' );
     Add( $0042, 'InitialCineRunState', [TKindVR.vrCS], 'Initial Cine Run State' );
     Add( $0050, 'SliceThickness', [TKindVR.vrDS], 'Slice Thickness' );
     Add( $0060, 'KVP', [TKindVR.vrDS], 'KVP' );
     Add( $0061, '', [TKindVR.vrDS], '' );
     Add( $0070, 'CountsAccumulated', [TKindVR.vrIS], 'Counts Accumulated' );
     Add( $0071, 'AcquisitionTerminationCondition', [TKindVR.vrCS], 'Acquisition Termination Condition' );
     Add( $0072, 'EffectiveDuration', [TKindVR.vrDS], 'Effective Duration' );
     Add( $0073, 'AcquisitionStartCondition', [TKindVR.vrCS], 'Acquisition Start Condition' );
     Add( $0074, 'AcquisitionStartConditionData', [TKindVR.vrIS], 'Acquisition Start Condition Data' );
     Add( $0075, 'AcquisitionTerminationConditionData', [TKindVR.vrIS], 'Acquisition Termination Condition Data' );
     Add( $0080, 'RepetitionTime', [TKindVR.vrDS], 'Repetition Time' );
     Add( $0081, 'EchoTime', [TKindVR.vrDS], 'Echo Time' );
     Add( $0082, 'InversionTime', [TKindVR.vrDS], 'Inversion Time' );
     Add( $0083, 'NumberOfAverages', [TKindVR.vrDS], 'Number of Averages' );
     Add( $0084, 'ImagingFrequency', [TKindVR.vrDS], 'Imaging Frequency' );
     Add( $0085, 'ImagedNucleus', [TKindVR.vrSH], 'Imaged Nucleus' );
     Add( $0086, 'EchoNumbers', [TKindVR.vrIS], 'Echo Number(s)' );
     Add( $0087, 'MagneticFieldStrength', [TKindVR.vrDS], 'Magnetic Field Strength' );
     Add( $0088, 'SpacingBetweenSlices', [TKindVR.vrDS], 'Spacing Between Slices' );
     Add( $0089, 'NumberOfPhaseEncodingSteps', [TKindVR.vrIS], 'Number of Phase Encoding Steps' );
     Add( $0090, 'DataCollectionDiameter', [TKindVR.vrDS], 'Data Collection Diameter' );
     Add( $0091, 'EchoTrainLength', [TKindVR.vrIS], 'Echo Train Length' );
     Add( $0093, 'PercentSampling', [TKindVR.vrDS], 'Percent Sampling' );
     Add( $0094, 'PercentPhaseFieldOfView', [TKindVR.vrDS], 'Percent Phase Field of View' );
     Add( $0095, 'PixelBandwidth', [TKindVR.vrDS], 'Pixel Bandwidth' );
     Add( $1000, 'DeviceSerialNumber', [TKindVR.vrLO], 'Device Serial Number' );
     Add( $1002, 'DeviceUID', [TKindVR.vrUI], 'Device UID' );
     Add( $1003, 'DeviceID', [TKindVR.vrLO], 'Device ID' );
     Add( $1004, 'PlateID', [TKindVR.vrLO], 'Plate ID' );
     Add( $1005, 'GeneratorID', [TKindVR.vrLO], 'Generator ID' );
     Add( $1006, 'GridID', [TKindVR.vrLO], 'Grid ID' );
     Add( $1007, 'CassetteID', [TKindVR.vrLO], 'Cassette ID' );
     Add( $1008, 'GantryID', [TKindVR.vrLO], 'Gantry ID' );
     Add( $1009, 'UniqueDeviceIdentifier', [TKindVR.vrUT], 'Unique Device Identifier' );
     Add( $100A, 'UDISequence', [TKindVR.vrSQ], 'UDI Sequence' );
     Add( $1010, 'SecondaryCaptureDeviceID', [TKindVR.vrLO], 'Secondary Capture Device ID' );
     Add( $1011, 'HardcopyCreationDeviceID', [TKindVR.vrLO], 'Hardcopy Creation Device ID' );
     Add( $1012, 'DateOfSecondaryCapture', [TKindVR.vrDA], 'Date of Secondary Capture' );
     Add( $1014, 'TimeOfSecondaryCapture', [TKindVR.vrTM], 'Time of Secondary Capture' );
     Add( $1016, 'SecondaryCaptureDeviceManufacturer', [TKindVR.vrLO], 'Secondary Capture Device Manufacturer' );
     Add( $1017, 'HardcopyDeviceManufacturer', [TKindVR.vrLO], 'Hardcopy Device Manufacturer' );
     Add( $1018, 'SecondaryCaptureDeviceManufacturerModelName', [TKindVR.vrLO], 'Secondary Capture Device Manufacturer''s Model Name' );
     Add( $1019, 'SecondaryCaptureDeviceSoftwareVersions', [TKindVR.vrLO], 'Secondary Capture Device Software Versions' );
     Add( $101A, 'HardcopyDeviceSoftwareVersion', [TKindVR.vrLO], 'Hardcopy Device Software Version' );
     Add( $101B, 'HardcopyDeviceManufacturerModelName', [TKindVR.vrLO], 'Hardcopy Device Manufacturer''s Model Name' );
     Add( $1020, 'SoftwareVersions', [TKindVR.vrLO], 'Software Version(s)' );
     Add( $1022, 'VideoImageFormatAcquired', [TKindVR.vrSH], 'Video Image Format Acquired' );
     Add( $1023, 'DigitalImageFormatAcquired', [TKindVR.vrLO], 'Digital Image Format Acquired' );
     Add( $1030, 'ProtocolName', [TKindVR.vrLO], 'Protocol Name' );
     Add( $1040, 'ContrastBolusRoute', [TKindVR.vrLO], 'Contrast/Bolus Route' );
     Add( $1041, 'ContrastBolusVolume', [TKindVR.vrDS], 'Contrast/Bolus Volume' );
     Add( $1042, 'ContrastBolusStartTime', [TKindVR.vrTM], 'Contrast/Bolus Start Time' );
     Add( $1043, 'ContrastBolusStopTime', [TKindVR.vrTM], 'Contrast/Bolus Stop Time' );
     Add( $1044, 'ContrastBolusTotalDose', [TKindVR.vrDS], 'Contrast/Bolus Total Dose' );
     Add( $1045, 'SyringeCounts', [TKindVR.vrIS], 'Syringe Counts' );
     Add( $1046, 'ContrastFlowRate', [TKindVR.vrDS], 'Contrast Flow Rate' );
     Add( $1047, 'ContrastFlowDuration', [TKindVR.vrDS], 'Contrast Flow Duration' );
     Add( $1048, 'ContrastBolusIngredient', [TKindVR.vrCS], 'Contrast/Bolus Ingredient' );
     Add( $1049, 'ContrastBolusIngredientConcentration', [TKindVR.vrDS], 'Contrast/Bolus Ingredient Concentration' );
     Add( $1050, 'SpatialResolution', [TKindVR.vrDS], 'Spatial Resolution' );
     Add( $1060, 'TriggerTime', [TKindVR.vrDS], 'Trigger Time' );
     Add( $1061, 'TriggerSourceOrType', [TKindVR.vrLO], 'Trigger Source or Type' );
     Add( $1062, 'NominalInterval', [TKindVR.vrIS], 'Nominal Interval' );
     Add( $1063, 'FrameTime', [TKindVR.vrDS], 'Frame Time' );
     Add( $1064, 'CardiacFramingType', [TKindVR.vrLO], 'Cardiac Framing Type' );
     Add( $1065, 'FrameTimeVector', [TKindVR.vrDS], 'Frame Time Vector' );
     Add( $1066, 'FrameDelay', [TKindVR.vrDS], 'Frame Delay' );
     Add( $1067, 'ImageTriggerDelay', [TKindVR.vrDS], 'Image Trigger Delay' );
     Add( $1068, 'MultiplexGroupTimeOffset', [TKindVR.vrDS], 'Multiplex Group Time Offset' );
     Add( $1069, 'TriggerTimeOffset', [TKindVR.vrDS], 'Trigger Time Offset' );
     Add( $106A, 'SynchronizationTrigger', [TKindVR.vrCS], 'Synchronization Trigger' );
     Add( $106C, 'SynchronizationChannel', [TKindVR.vrUS], 'Synchronization Channel' );
     Add( $106E, 'TriggerSamplePosition', [TKindVR.vrUL], 'Trigger Sample Position' );
     Add( $1070, 'RadiopharmaceuticalRoute', [TKindVR.vrLO], 'Radiopharmaceutical Route' );
     Add( $1071, 'RadiopharmaceuticalVolume', [TKindVR.vrDS], 'Radiopharmaceutical Volume' );
     Add( $1072, 'RadiopharmaceuticalStartTime', [TKindVR.vrTM], 'Radiopharmaceutical Start Time' );
     Add( $1073, 'RadiopharmaceuticalStopTime', [TKindVR.vrTM], 'Radiopharmaceutical Stop Time' );
     Add( $1074, 'RadionuclideTotalDose', [TKindVR.vrDS], 'Radionuclide Total Dose' );
     Add( $1075, 'RadionuclideHalfLife', [TKindVR.vrDS], 'Radionuclide Half Life' );
     Add( $1076, 'RadionuclidePositronFraction', [TKindVR.vrDS], 'Radionuclide Positron Fraction' );
     Add( $1077, 'RadiopharmaceuticalSpecificActivity', [TKindVR.vrDS], 'Radiopharmaceutical Specific Activity' );
     Add( $1078, 'RadiopharmaceuticalStartDateTime', [TKindVR.vrDT], 'Radiopharmaceutical Start DateTime' );
     Add( $1079, 'RadiopharmaceuticalStopDateTime', [TKindVR.vrDT], 'Radiopharmaceutical Stop DateTime' );
     Add( $1080, 'BeatRejectionFlag', [TKindVR.vrCS], 'Beat Rejection Flag' );
     Add( $1081, 'LowRRValue', [TKindVR.vrIS], 'Low R-R Value' );
     Add( $1082, 'HighRRValue', [TKindVR.vrIS], 'High R-R Value' );
     Add( $1083, 'IntervalsAcquired', [TKindVR.vrIS], 'Intervals Acquired' );
     Add( $1084, 'IntervalsRejected', [TKindVR.vrIS], 'Intervals Rejected' );
     Add( $1085, 'PVCRejection', [TKindVR.vrLO], 'PVC Rejection' );
     Add( $1086, 'SkipBeats', [TKindVR.vrIS], 'Skip Beats' );
     Add( $1088, 'HeartRate', [TKindVR.vrIS], 'Heart Rate' );
     Add( $1090, 'CardiacNumberOfImages', [TKindVR.vrIS], 'Cardiac Number of Images' );
     Add( $1094, 'TriggerWindow', [TKindVR.vrIS], 'Trigger Window' );
     Add( $1100, 'ReconstructionDiameter', [TKindVR.vrDS], 'Reconstruction Diameter' );
     Add( $1110, 'DistanceSourceToDetector', [TKindVR.vrDS], 'Distance Source to Detector' );
     Add( $1111, 'DistanceSourceToPatient', [TKindVR.vrDS], 'Distance Source to Patient' );
     Add( $1114, 'EstimatedRadiographicMagnificationFactor', [TKindVR.vrDS], 'Estimated Radiographic Magnification Factor' );
     Add( $1120, 'GantryDetectorTilt', [TKindVR.vrDS], 'Gantry/Detector Tilt' );
     Add( $1121, 'GantryDetectorSlew', [TKindVR.vrDS], 'Gantry/Detector Slew' );
     Add( $1130, 'TableHeight', [TKindVR.vrDS], 'Table Height' );
     Add( $1131, 'TableTraverse', [TKindVR.vrDS], 'Table Traverse' );
     Add( $1134, 'TableMotion', [TKindVR.vrCS], 'Table Motion' );
     Add( $1135, 'TableVerticalIncrement', [TKindVR.vrDS], 'Table Vertical Increment' );
     Add( $1136, 'TableLateralIncrement', [TKindVR.vrDS], 'Table Lateral Increment' );
     Add( $1137, 'TableLongitudinalIncrement', [TKindVR.vrDS], 'Table Longitudinal Increment' );
     Add( $1138, 'TableAngle', [TKindVR.vrDS], 'Table Angle' );
     Add( $113A, 'TableType', [TKindVR.vrCS], 'Table Type' );
     Add( $1140, 'RotationDirection', [TKindVR.vrCS], 'Rotation Direction' );
     Add( $1141, 'AngularPosition', [TKindVR.vrDS], 'Angular Position' );
     Add( $1142, 'RadialPosition', [TKindVR.vrDS], 'Radial Position' );
     Add( $1143, 'ScanArc', [TKindVR.vrDS], 'Scan Arc' );
     Add( $1144, 'AngularStep', [TKindVR.vrDS], 'Angular Step' );
     Add( $1145, 'CenterOfRotationOffset', [TKindVR.vrDS], 'Center of Rotation Offset' );
     Add( $1146, 'RotationOffset', [TKindVR.vrDS], 'Rotation Offset' );
     Add( $1147, 'FieldOfViewShape', [TKindVR.vrCS], 'Field of View Shape' );
     Add( $1149, 'FieldOfViewDimensions', [TKindVR.vrIS], 'Field of View Dimension(s)' );
     Add( $1150, 'ExposureTime', [TKindVR.vrIS], 'Exposure Time' );
     Add( $1151, 'XRayTubeCurrent', [TKindVR.vrIS], 'X-Ray Tube Current' );
     Add( $1152, 'Exposure', [TKindVR.vrIS], 'Exposure' );
     Add( $1153, 'ExposureInuAs', [TKindVR.vrIS], 'Exposure in µAs' );
     Add( $1154, 'AveragePulseWidth', [TKindVR.vrDS], 'Average Pulse Width' );
     Add( $1155, 'RadiationSetting', [TKindVR.vrCS], 'Radiation Setting' );
     Add( $1156, 'RectificationType', [TKindVR.vrCS], 'Rectification Type' );
     Add( $115A, 'RadiationMode', [TKindVR.vrCS], 'Radiation Mode' );
     Add( $115E, 'ImageAndFluoroscopyAreaDoseProduct', [TKindVR.vrDS], 'Image and Fluoroscopy Area Dose Product' );
     Add( $1160, 'FilterType', [TKindVR.vrSH], 'Filter Type' );
     Add( $1161, 'TypeOfFilters', [TKindVR.vrLO], 'Type of Filters' );
     Add( $1162, 'IntensifierSize', [TKindVR.vrDS], 'Intensifier Size' );
     Add( $1164, 'ImagerPixelSpacing', [TKindVR.vrDS], 'Imager Pixel Spacing' );
     Add( $1166, 'Grid', [TKindVR.vrCS], 'Grid' );
     Add( $1170, 'GeneratorPower', [TKindVR.vrIS], 'Generator Power' );
     Add( $1180, 'CollimatorGridName', [TKindVR.vrSH], 'Collimator/grid Name' );
     Add( $1181, 'CollimatorType', [TKindVR.vrCS], 'Collimator Type' );
     Add( $1182, 'FocalDistance', [TKindVR.vrIS], 'Focal Distance' );
     Add( $1183, 'XFocusCenter', [TKindVR.vrDS], 'X Focus Center' );
     Add( $1184, 'YFocusCenter', [TKindVR.vrDS], 'Y Focus Center' );
     Add( $1190, 'FocalSpots', [TKindVR.vrDS], 'Focal Spot(s)' );
     Add( $1191, 'AnodeTargetMaterial', [TKindVR.vrCS], 'Anode Target Material' );
     Add( $11A0, 'BodyPartThickness', [TKindVR.vrDS], 'Body Part Thickness' );
     Add( $11A2, 'CompressionForce', [TKindVR.vrDS], 'Compression Force' );
     Add( $11A4, 'PaddleDescription', [TKindVR.vrLO], 'Paddle Description' );
     Add( $1200, 'DateOfLastCalibration', [TKindVR.vrDA], 'Date of Last Calibration' );
     Add( $1201, 'TimeOfLastCalibration', [TKindVR.vrTM], 'Time of Last Calibration' );
     Add( $1202, 'DateTimeOfLastCalibration', [TKindVR.vrDT], 'DateTime of Last Calibration' );
     Add( $1210, 'ConvolutionKernel', [TKindVR.vrSH], 'Convolution Kernel' );
     Add( $1240, 'UpperLowerPixelValues', [TKindVR.vrIS], 'Upper/Lower Pixel Values' );
     Add( $1242, 'ActualFrameDuration', [TKindVR.vrIS], 'Actual Frame Duration' );
     Add( $1243, 'CountRate', [TKindVR.vrIS], 'Count Rate' );
     Add( $1244, 'PreferredPlaybackSequencing', [TKindVR.vrUS], 'Preferred Playback Sequencing' );
     Add( $1250, 'ReceiveCoilName', [TKindVR.vrSH], 'Receive Coil Name' );
     Add( $1251, 'TransmitCoilName', [TKindVR.vrSH], 'Transmit Coil Name' );
     Add( $1260, 'PlateType', [TKindVR.vrSH], 'Plate Type' );
     Add( $1261, 'PhosphorType', [TKindVR.vrLO], 'Phosphor Type' );
     Add( $1271, 'WaterEquivalentDiameter', [TKindVR.vrFD], 'Water Equivalent Diameter' );
     Add( $1272, 'WaterEquivalentDiameterCalculationMethodCodeSequence', [TKindVR.vrSQ], 'Water Equivalent Diameter Calculation Method Code Sequence' );
     Add( $1300, 'ScanVelocity', [TKindVR.vrDS], 'Scan Velocity' );
     Add( $1301, 'WholeBodyTechnique', [TKindVR.vrCS], 'Whole Body Technique' );
     Add( $1302, 'ScanLength', [TKindVR.vrIS], 'Scan Length' );
     Add( $1310, 'AcquisitionMatrix', [TKindVR.vrUS], 'Acquisition Matrix' );
     Add( $1312, 'InPlanePhaseEncodingDirection', [TKindVR.vrCS], 'In-plane Phase Encoding Direction' );
     Add( $1314, 'FlipAngle', [TKindVR.vrDS], 'Flip Angle' );
     Add( $1315, 'VariableFlipAngleFlag', [TKindVR.vrCS], 'Variable Flip Angle Flag' );
     Add( $1316, 'SAR', [TKindVR.vrDS], 'SAR' );
     Add( $1318, 'dBdt', [TKindVR.vrDS], 'dB/dt' );
     Add( $1320, 'B1rms', [TKindVR.vrFL], 'B1rms' );
     Add( $1400, 'AcquisitionDeviceProcessingDescription', [TKindVR.vrLO], 'Acquisition Device Processing Description' );
     Add( $1401, 'AcquisitionDeviceProcessingCode', [TKindVR.vrLO], 'Acquisition Device Processing Code' );
     Add( $1402, 'CassetteOrientation', [TKindVR.vrCS], 'Cassette Orientation' );
     Add( $1403, 'CassetteSize', [TKindVR.vrCS], 'Cassette Size' );
     Add( $1404, 'ExposuresOnPlate', [TKindVR.vrUS], 'Exposures on Plate' );
     Add( $1405, 'RelativeXRayExposure', [TKindVR.vrIS], 'Relative X-Ray Exposure' );
     Add( $1411, 'ExposureIndex', [TKindVR.vrDS], 'Exposure Index' );
     Add( $1412, 'TargetExposureIndex', [TKindVR.vrDS], 'Target Exposure Index' );
     Add( $1413, 'DeviationIndex', [TKindVR.vrDS], 'Deviation Index' );
     Add( $1450, 'ColumnAngulation', [TKindVR.vrDS], 'Column Angulation' );
     Add( $1460, 'TomoLayerHeight', [TKindVR.vrDS], 'Tomo Layer Height' );
     Add( $1470, 'TomoAngle', [TKindVR.vrDS], 'Tomo Angle' );
     Add( $1480, 'TomoTime', [TKindVR.vrDS], 'Tomo Time' );
     Add( $1490, 'TomoType', [TKindVR.vrCS], 'Tomo Type' );
     Add( $1491, 'TomoClass', [TKindVR.vrCS], 'Tomo Class' );
     Add( $1495, 'NumberOfTomosynthesisSourceImages', [TKindVR.vrIS], 'Number of Tomosynthesis Source Images' );
     Add( $1500, 'PositionerMotion', [TKindVR.vrCS], 'Positioner Motion' );
     Add( $1508, 'PositionerType', [TKindVR.vrCS], 'Positioner Type' );
     Add( $1510, 'PositionerPrimaryAngle', [TKindVR.vrDS], 'Positioner Primary Angle' );
     Add( $1511, 'PositionerSecondaryAngle', [TKindVR.vrDS], 'Positioner Secondary Angle' );
     Add( $1520, 'PositionerPrimaryAngleIncrement', [TKindVR.vrDS], 'Positioner Primary Angle Increment' );
     Add( $1521, 'PositionerSecondaryAngleIncrement', [TKindVR.vrDS], 'Positioner Secondary Angle Increment' );
     Add( $1530, 'DetectorPrimaryAngle', [TKindVR.vrDS], 'Detector Primary Angle' );
     Add( $1531, 'DetectorSecondaryAngle', [TKindVR.vrDS], 'Detector Secondary Angle' );
     Add( $1600, 'ShutterShape', [TKindVR.vrCS], 'Shutter Shape' );
     Add( $1602, 'ShutterLeftVerticalEdge', [TKindVR.vrIS], 'Shutter Left Vertical Edge' );
     Add( $1604, 'ShutterRightVerticalEdge', [TKindVR.vrIS], 'Shutter Right Vertical Edge' );
     Add( $1606, 'ShutterUpperHorizontalEdge', [TKindVR.vrIS], 'Shutter Upper Horizontal Edge' );
     Add( $1608, 'ShutterLowerHorizontalEdge', [TKindVR.vrIS], 'Shutter Lower Horizontal Edge' );
     Add( $1610, 'CenterOfCircularShutter', [TKindVR.vrIS], 'Center of Circular Shutter' );
     Add( $1612, 'RadiusOfCircularShutter', [TKindVR.vrIS], 'Radius of Circular Shutter' );
     Add( $1620, 'VerticesOfThePolygonalShutter', [TKindVR.vrIS], 'Vertices of the Polygonal Shutter' );
     Add( $1622, 'ShutterPresentationValue', [TKindVR.vrUS], 'Shutter Presentation Value' );
     Add( $1623, 'ShutterOverlayGroup', [TKindVR.vrUS], 'Shutter Overlay Group' );
     Add( $1624, 'ShutterPresentationColorCIELabValue', [TKindVR.vrUS], 'Shutter Presentation Color CIELab Value' );
     Add( $1700, 'CollimatorShape', [TKindVR.vrCS], 'Collimator Shape' );
     Add( $1702, 'CollimatorLeftVerticalEdge', [TKindVR.vrIS], 'Collimator Left Vertical Edge' );
     Add( $1704, 'CollimatorRightVerticalEdge', [TKindVR.vrIS], 'Collimator Right Vertical Edge' );
     Add( $1706, 'CollimatorUpperHorizontalEdge', [TKindVR.vrIS], 'Collimator Upper Horizontal Edge' );
     Add( $1708, 'CollimatorLowerHorizontalEdge', [TKindVR.vrIS], 'Collimator Lower Horizontal Edge' );
     Add( $1710, 'CenterOfCircularCollimator', [TKindVR.vrIS], 'Center of Circular Collimator' );
     Add( $1712, 'RadiusOfCircularCollimator', [TKindVR.vrIS], 'Radius of Circular Collimator' );
     Add( $1720, 'VerticesOfThePolygonalCollimator', [TKindVR.vrIS], 'Vertices of the Polygonal Collimator' );
     Add( $1800, 'AcquisitionTimeSynchronized', [TKindVR.vrCS], 'Acquisition Time Synchronized' );
     Add( $1801, 'TimeSource', [TKindVR.vrSH], 'Time Source' );
     Add( $1802, 'TimeDistributionProtocol', [TKindVR.vrCS], 'Time Distribution Protocol' );
     Add( $1803, 'NTPSourceAddress', [TKindVR.vrLO], 'NTP Source Address' );
     Add( $2001, 'PageNumberVector', [TKindVR.vrIS], 'Page Number Vector' );
     Add( $2002, 'FrameLabelVector', [TKindVR.vrSH], 'Frame Label Vector' );
     Add( $2003, 'FramePrimaryAngleVector', [TKindVR.vrDS], 'Frame Primary Angle Vector' );
     Add( $2004, 'FrameSecondaryAngleVector', [TKindVR.vrDS], 'Frame Secondary Angle Vector' );
     Add( $2005, 'SliceLocationVector', [TKindVR.vrDS], 'Slice Location Vector' );
     Add( $2006, 'DisplayWindowLabelVector', [TKindVR.vrSH], 'Display Window Label Vector' );
     Add( $2010, 'NominalScannedPixelSpacing', [TKindVR.vrDS], 'Nominal Scanned Pixel Spacing' );
     Add( $2020, 'DigitizingDeviceTransportDirection', [TKindVR.vrCS], 'Digitizing Device Transport Direction' );
     Add( $2030, 'RotationOfScannedFilm', [TKindVR.vrDS], 'Rotation of Scanned Film' );
     Add( $2041, 'BiopsyTargetSequence', [TKindVR.vrSQ], 'Biopsy Target Sequence' );
     Add( $2042, 'TargetUID', [TKindVR.vrUI], 'Target UID' );
     Add( $2043, 'LocalizingCursorPosition', [TKindVR.vrFL], 'Localizing Cursor Position' );
     Add( $2044, 'CalculatedTargetPosition', [TKindVR.vrFL], 'Calculated Target Position' );
     Add( $2045, 'TargetLabel', [TKindVR.vrSH], 'Target Label' );
     Add( $2046, 'DisplayedZValue', [TKindVR.vrFL], 'Displayed Z Value' );
     Add( $3100, 'IVUSAcquisition', [TKindVR.vrCS], 'IVUS Acquisition' );
     Add( $3101, 'IVUSPullbackRate', [TKindVR.vrDS], 'IVUS Pullback Rate' );
     Add( $3102, 'IVUSGatedRate', [TKindVR.vrDS], 'IVUS Gated Rate' );
     Add( $3103, 'IVUSPullbackStartFrameNumber', [TKindVR.vrIS], 'IVUS Pullback Start Frame Number' );
     Add( $3104, 'IVUSPullbackStopFrameNumber', [TKindVR.vrIS], 'IVUS Pullback Stop Frame Number' );
     Add( $3105, 'LesionNumber', [TKindVR.vrIS], 'Lesion Number' );
     Add( $4000, 'AcquisitionComments', [TKindVR.vrLT], 'Acquisition Comments' );
     Add( $5000, 'OutputPower', [TKindVR.vrSH], 'Output Power' );
     Add( $5010, 'TransducerData', [TKindVR.vrLO], 'Transducer Data' );
     Add( $5012, 'FocusDepth', [TKindVR.vrDS], 'Focus Depth' );
     Add( $5020, 'ProcessingFunction', [TKindVR.vrLO], 'Processing Function' );
     Add( $5021, 'PostprocessingFunction', [TKindVR.vrLO], 'Postprocessing Function' );
     Add( $5022, 'MechanicalIndex', [TKindVR.vrDS], 'Mechanical Index' );
     Add( $5024, 'BoneThermalIndex', [TKindVR.vrDS], 'Bone Thermal Index' );
     Add( $5026, 'CranialThermalIndex', [TKindVR.vrDS], 'Cranial Thermal Index' );
     Add( $5027, 'SoftTissueThermalIndex', [TKindVR.vrDS], 'Soft Tissue Thermal Index' );
     Add( $5028, 'SoftTissueFocusThermalIndex', [TKindVR.vrDS], 'Soft Tissue-focus Thermal Index' );
     Add( $5029, 'SoftTissueSurfaceThermalIndex', [TKindVR.vrDS], 'Soft Tissue-surface Thermal Index' );
     Add( $5030, 'DynamicRange', [TKindVR.vrDS], 'Dynamic Range' );
     Add( $5040, 'TotalGain', [TKindVR.vrDS], 'Total Gain' );
     Add( $5050, 'DepthOfScanField', [TKindVR.vrIS], 'Depth of Scan Field' );
     Add( $5100, 'PatientPosition', [TKindVR.vrCS], 'Patient Position' );
     Add( $5101, 'ViewPosition', [TKindVR.vrCS], 'View Position' );
     Add( $5104, 'ProjectionEponymousNameCodeSequence', [TKindVR.vrSQ], 'Projection Eponymous Name Code Sequence' );
     Add( $5210, 'ImageTransformationMatrix', [TKindVR.vrDS], 'Image Transformation Matrix' );
     Add( $5212, 'ImageTranslationVector', [TKindVR.vrDS], 'Image Translation Vector' );
     Add( $6000, 'Sensitivity', [TKindVR.vrDS], 'Sensitivity' );
     Add( $6011, 'SequenceOfUltrasoundRegions', [TKindVR.vrSQ], 'Sequence of Ultrasound Regions' );
     Add( $6012, 'RegionSpatialFormat', [TKindVR.vrUS], 'Region Spatial Format' );
     Add( $6014, 'RegionDataType', [TKindVR.vrUS], 'Region Data Type' );
     Add( $6016, 'RegionFlags', [TKindVR.vrUL], 'Region Flags' );
     Add( $6018, 'RegionLocationMinX0', [TKindVR.vrUL], 'Region Location Min X0' );
     Add( $601A, 'RegionLocationMinY0', [TKindVR.vrUL], 'Region Location Min Y0' );
     Add( $601C, 'RegionLocationMaxX1', [TKindVR.vrUL], 'Region Location Max X1' );
     Add( $601E, 'RegionLocationMaxY1', [TKindVR.vrUL], 'Region Location Max Y1' );
     Add( $6020, 'ReferencePixelX0', [TKindVR.vrSL], 'Reference Pixel X0' );
     Add( $6022, 'ReferencePixelY0', [TKindVR.vrSL], 'Reference Pixel Y0' );
     Add( $6024, 'PhysicalUnitsXDirection', [TKindVR.vrUS], 'Physical Units X Direction' );
     Add( $6026, 'PhysicalUnitsYDirection', [TKindVR.vrUS], 'Physical Units Y Direction' );
     Add( $6028, 'ReferencePixelPhysicalValueX', [TKindVR.vrFD], 'Reference Pixel Physical Value X' );
     Add( $602A, 'ReferencePixelPhysicalValueY', [TKindVR.vrFD], 'Reference Pixel Physical Value Y' );
     Add( $602C, 'PhysicalDeltaX', [TKindVR.vrFD], 'Physical Delta X' );
     Add( $602E, 'PhysicalDeltaY', [TKindVR.vrFD], 'Physical Delta Y' );
     Add( $6030, 'TransducerFrequency', [TKindVR.vrUL], 'Transducer Frequency' );
     Add( $6031, 'TransducerType', [TKindVR.vrCS], 'Transducer Type' );
     Add( $6032, 'PulseRepetitionFrequency', [TKindVR.vrUL], 'Pulse Repetition Frequency' );
     Add( $6034, 'DopplerCorrectionAngle', [TKindVR.vrFD], 'Doppler Correction Angle' );
     Add( $6036, 'SteeringAngle', [TKindVR.vrFD], 'Steering Angle' );
     Add( $6038, 'DopplerSampleVolumeXPositionRetired', [TKindVR.vrUL], 'Doppler Sample Volume X Position (Retired)' );
     Add( $6039, 'DopplerSampleVolumeXPosition', [TKindVR.vrSL], 'Doppler Sample Volume X Position' );
     Add( $603A, 'DopplerSampleVolumeYPositionRetired', [TKindVR.vrUL], 'Doppler Sample Volume Y Position (Retired)' );
     Add( $603B, 'DopplerSampleVolumeYPosition', [TKindVR.vrSL], 'Doppler Sample Volume Y Position' );
     Add( $603C, 'TMLinePositionX0Retired', [TKindVR.vrUL], 'TM-Line Position X0 (Retired)' );
     Add( $603D, 'TMLinePositionX0', [TKindVR.vrSL], 'TM-Line Position X0' );
     Add( $603E, 'TMLinePositionY0Retired', [TKindVR.vrUL], 'TM-Line Position Y0 (Retired)' );
     Add( $603F, 'TMLinePositionY0', [TKindVR.vrSL], 'TM-Line Position Y0' );
     Add( $6040, 'TMLinePositionX1Retired', [TKindVR.vrUL], 'TM-Line Position X1 (Retired)' );
     Add( $6041, 'TMLinePositionX1', [TKindVR.vrSL], 'TM-Line Position X1' );
     Add( $6042, 'TMLinePositionY1Retired', [TKindVR.vrUL], 'TM-Line Position Y1 (Retired)' );
     Add( $6043, 'TMLinePositionY1', [TKindVR.vrSL], 'TM-Line Position Y1' );
     Add( $6044, 'PixelComponentOrganization', [TKindVR.vrUS], 'Pixel Component Organization' );
     Add( $6046, 'PixelComponentMask', [TKindVR.vrUL], 'Pixel Component Mask' );
     Add( $6048, 'PixelComponentRangeStart', [TKindVR.vrUL], 'Pixel Component Range Start' );
     Add( $604A, 'PixelComponentRangeStop', [TKindVR.vrUL], 'Pixel Component Range Stop' );
     Add( $604C, 'PixelComponentPhysicalUnits', [TKindVR.vrUS], 'Pixel Component Physical Units' );
     Add( $604E, 'PixelComponentDataType', [TKindVR.vrUS], 'Pixel Component Data Type' );
     Add( $6050, 'NumberOfTableBreakPoints', [TKindVR.vrUL], 'Number of Table Break Points' );
     Add( $6052, 'TableOfXBreakPoints', [TKindVR.vrUL], 'Table of X Break Points' );
     Add( $6054, 'TableOfYBreakPoints', [TKindVR.vrFD], 'Table of Y Break Points' );
     Add( $6056, 'NumberOfTableEntries', [TKindVR.vrUL], 'Number of Table Entries' );
     Add( $6058, 'TableOfPixelValues', [TKindVR.vrUL], 'Table of Pixel Values' );
     Add( $605A, 'TableOfParameterValues', [TKindVR.vrFL], 'Table of Parameter Values' );
     Add( $6060, 'RWaveTimeVector', [TKindVR.vrFL], 'R Wave Time Vector' );
     Add( $7000, 'DetectorConditionsNominalFlag', [TKindVR.vrCS], 'Detector Conditions Nominal Flag' );
     Add( $7001, 'DetectorTemperature', [TKindVR.vrDS], 'Detector Temperature' );
     Add( $7004, 'DetectorType', [TKindVR.vrCS], 'Detector Type' );
     Add( $7005, 'DetectorConfiguration', [TKindVR.vrCS], 'Detector Configuration' );
     Add( $7006, 'DetectorDescription', [TKindVR.vrLT], 'Detector Description' );
     Add( $7008, 'DetectorMode', [TKindVR.vrLT], 'Detector Mode' );
     Add( $700A, 'DetectorID', [TKindVR.vrSH], 'Detector ID' );
     Add( $700C, 'DateOfLastDetectorCalibration', [TKindVR.vrDA], 'Date of Last Detector Calibration' );
     Add( $700E, 'TimeOfLastDetectorCalibration', [TKindVR.vrTM], 'Time of Last Detector Calibration' );
     Add( $7010, 'ExposuresOnDetectorSinceLastCalibration', [TKindVR.vrIS], 'Exposures on Detector Since Last Calibration' );
     Add( $7011, 'ExposuresOnDetectorSinceManufactured', [TKindVR.vrIS], 'Exposures on Detector Since Manufactured' );
     Add( $7012, 'DetectorTimeSinceLastExposure', [TKindVR.vrDS], 'Detector Time Since Last Exposure' );
     Add( $7014, 'DetectorActiveTime', [TKindVR.vrDS], 'Detector Active Time' );
     Add( $7016, 'DetectorActivationOffsetFromExposure', [TKindVR.vrDS], 'Detector Activation Offset From Exposure' );
     Add( $701A, 'DetectorBinning', [TKindVR.vrDS], 'Detector Binning' );
     Add( $7020, 'DetectorElementPhysicalSize', [TKindVR.vrDS], 'Detector Element Physical Size' );
     Add( $7022, 'DetectorElementSpacing', [TKindVR.vrDS], 'Detector Element Spacing' );
     Add( $7024, 'DetectorActiveShape', [TKindVR.vrCS], 'Detector Active Shape' );
     Add( $7026, 'DetectorActiveDimensions', [TKindVR.vrDS], 'Detector Active Dimension(s)' );
     Add( $7028, 'DetectorActiveOrigin', [TKindVR.vrDS], 'Detector Active Origin' );
     Add( $702A, 'DetectorManufacturerName', [TKindVR.vrLO], 'Detector Manufacturer Name' );
     Add( $702B, 'DetectorManufacturerModelName', [TKindVR.vrLO], 'Detector Manufacturer''s Model Name' );
     Add( $7030, 'FieldOfViewOrigin', [TKindVR.vrDS], 'Field of View Origin' );
     Add( $7032, 'FieldOfViewRotation', [TKindVR.vrDS], 'Field of View Rotation' );
     Add( $7034, 'FieldOfViewHorizontalFlip', [TKindVR.vrCS], 'Field of View Horizontal Flip' );
     Add( $7036, 'PixelDataAreaOriginRelativeToFOV', [TKindVR.vrFL], 'Pixel Data Area Origin Relative To FOV' );
     Add( $7038, 'PixelDataAreaRotationAngleRelativeToFOV', [TKindVR.vrFL], 'Pixel Data Area Rotation Angle Relative To FOV' );
     Add( $7040, 'GridAbsorbingMaterial', [TKindVR.vrLT], 'Grid Absorbing Material' );
     Add( $7041, 'GridSpacingMaterial', [TKindVR.vrLT], 'Grid Spacing Material' );
     Add( $7042, 'GridThickness', [TKindVR.vrDS], 'Grid Thickness' );
     Add( $7044, 'GridPitch', [TKindVR.vrDS], 'Grid Pitch' );
     Add( $7046, 'GridAspectRatio', [TKindVR.vrIS], 'Grid Aspect Ratio' );
     Add( $7048, 'GridPeriod', [TKindVR.vrDS], 'Grid Period' );
     Add( $704C, 'GridFocalDistance', [TKindVR.vrDS], 'Grid Focal Distance' );
     Add( $7050, 'FilterMaterial', [TKindVR.vrCS], 'Filter Material' );
     Add( $7052, 'FilterThicknessMinimum', [TKindVR.vrDS], 'Filter Thickness Minimum' );
     Add( $7054, 'FilterThicknessMaximum', [TKindVR.vrDS], 'Filter Thickness Maximum' );
     Add( $7056, 'FilterBeamPathLengthMinimum', [TKindVR.vrFL], 'Filter Beam Path Length Minimum' );
     Add( $7058, 'FilterBeamPathLengthMaximum', [TKindVR.vrFL], 'Filter Beam Path Length Maximum' );
     Add( $7060, 'ExposureControlMode', [TKindVR.vrCS], 'Exposure Control Mode' );
     Add( $7062, 'ExposureControlModeDescription', [TKindVR.vrLT], 'Exposure Control Mode Description' );
     Add( $7064, 'ExposureStatus', [TKindVR.vrCS], 'Exposure Status' );
     Add( $7065, 'PhototimerSetting', [TKindVR.vrDS], 'Phototimer Setting' );
     Add( $8150, 'ExposureTimeInuS', [TKindVR.vrDS], 'Exposure Time in µS' );
     Add( $8151, 'XRayTubeCurrentInuA', [TKindVR.vrDS], 'X-Ray Tube Current in µA' );
     Add( $9004, 'ContentQualification', [TKindVR.vrCS], 'Content Qualification' );
     Add( $9005, 'PulseSequenceName', [TKindVR.vrSH], 'Pulse Sequence Name' );
     Add( $9006, 'MRImagingModifierSequence', [TKindVR.vrSQ], 'MR Imaging Modifier Sequence' );
     Add( $9008, 'EchoPulseSequence', [TKindVR.vrCS], 'Echo Pulse Sequence' );
     Add( $9009, 'InversionRecovery', [TKindVR.vrCS], 'Inversion Recovery' );
     Add( $9010, 'FlowCompensation', [TKindVR.vrCS], 'Flow Compensation' );
     Add( $9011, 'MultipleSpinEcho', [TKindVR.vrCS], 'Multiple Spin Echo' );
     Add( $9012, 'MultiPlanarExcitation', [TKindVR.vrCS], 'Multi-planar Excitation' );
     Add( $9014, 'PhaseContrast', [TKindVR.vrCS], 'Phase Contrast' );
     Add( $9015, 'TimeOfFlightContrast', [TKindVR.vrCS], 'Time of Flight Contrast' );
     Add( $9016, 'Spoiling', [TKindVR.vrCS], 'Spoiling' );
     Add( $9017, 'SteadyStatePulseSequence', [TKindVR.vrCS], 'Steady State Pulse Sequence' );
     Add( $9018, 'EchoPlanarPulseSequence', [TKindVR.vrCS], 'Echo Planar Pulse Sequence' );
     Add( $9019, 'TagAngleFirstAxis', [TKindVR.vrFD], 'Tag Angle First Axis' );
     Add( $9020, 'MagnetizationTransfer', [TKindVR.vrCS], 'Magnetization Transfer' );
     Add( $9021, 'T2Preparation', [TKindVR.vrCS], 'T2 Preparation' );
     Add( $9022, 'BloodSignalNulling', [TKindVR.vrCS], 'Blood Signal Nulling' );
     Add( $9024, 'SaturationRecovery', [TKindVR.vrCS], 'Saturation Recovery' );
     Add( $9025, 'SpectrallySelectedSuppression', [TKindVR.vrCS], 'Spectrally Selected Suppression' );
     Add( $9026, 'SpectrallySelectedExcitation', [TKindVR.vrCS], 'Spectrally Selected Excitation' );
     Add( $9027, 'SpatialPresaturation', [TKindVR.vrCS], 'Spatial Pre-saturation' );
     Add( $9028, 'Tagging', [TKindVR.vrCS], 'Tagging' );
     Add( $9029, 'OversamplingPhase', [TKindVR.vrCS], 'Oversampling Phase' );
     Add( $9030, 'TagSpacingFirstDimension', [TKindVR.vrFD], 'Tag Spacing First Dimension' );
     Add( $9032, 'GeometryOfKSpaceTraversal', [TKindVR.vrCS], 'Geometry of k-Space Traversal' );
     Add( $9033, 'SegmentedKSpaceTraversal', [TKindVR.vrCS], 'Segmented k-Space Traversal' );
     Add( $9034, 'RectilinearPhaseEncodeReordering', [TKindVR.vrCS], 'Rectilinear Phase Encode Reordering' );
     Add( $9035, 'TagThickness', [TKindVR.vrFD], 'Tag Thickness' );
     Add( $9036, 'PartialFourierDirection', [TKindVR.vrCS], 'Partial Fourier Direction' );
     Add( $9037, 'CardiacSynchronizationTechnique', [TKindVR.vrCS], 'Cardiac Synchronization Technique' );
     Add( $9041, 'ReceiveCoilManufacturerName', [TKindVR.vrLO], 'Receive Coil Manufacturer Name' );
     Add( $9042, 'MRReceiveCoilSequence', [TKindVR.vrSQ], 'MR Receive Coil Sequence' );
     Add( $9043, 'ReceiveCoilType', [TKindVR.vrCS], 'Receive Coil Type' );
     Add( $9044, 'QuadratureReceiveCoil', [TKindVR.vrCS], 'Quadrature Receive Coil' );
     Add( $9045, 'MultiCoilDefinitionSequence', [TKindVR.vrSQ], 'Multi-Coil Definition Sequence' );
     Add( $9046, 'MultiCoilConfiguration', [TKindVR.vrLO], 'Multi-Coil Configuration' );
     Add( $9047, 'MultiCoilElementName', [TKindVR.vrSH], 'Multi-Coil Element Name' );
     Add( $9048, 'MultiCoilElementUsed', [TKindVR.vrCS], 'Multi-Coil Element Used' );
     Add( $9049, 'MRTransmitCoilSequence', [TKindVR.vrSQ], 'MR Transmit Coil Sequence' );
     Add( $9050, 'TransmitCoilManufacturerName', [TKindVR.vrLO], 'Transmit Coil Manufacturer Name' );
     Add( $9051, 'TransmitCoilType', [TKindVR.vrCS], 'Transmit Coil Type' );
     Add( $9052, 'SpectralWidth', [TKindVR.vrFD], 'Spectral Width' );
     Add( $9053, 'ChemicalShiftReference', [TKindVR.vrFD], 'Chemical Shift Reference' );
     Add( $9054, 'VolumeLocalizationTechnique', [TKindVR.vrCS], 'Volume Localization Technique' );
     Add( $9058, 'MRAcquisitionFrequencyEncodingSteps', [TKindVR.vrUS], 'MR Acquisition Frequency Encoding Steps' );
     Add( $9059, 'Decoupling', [TKindVR.vrCS], 'De-coupling' );
     Add( $9060, 'DecoupledNucleus', [TKindVR.vrCS], 'De-coupled Nucleus' );
     Add( $9061, 'DecouplingFrequency', [TKindVR.vrFD], 'De-coupling Frequency' );
     Add( $9062, 'DecouplingMethod', [TKindVR.vrCS], 'De-coupling Method' );
     Add( $9063, 'DecouplingChemicalShiftReference', [TKindVR.vrFD], 'De-coupling Chemical Shift Reference' );
     Add( $9064, 'KSpaceFiltering', [TKindVR.vrCS], 'k-space Filtering' );
     Add( $9065, 'TimeDomainFiltering', [TKindVR.vrCS], 'Time Domain Filtering' );
     Add( $9066, 'NumberOfZeroFills', [TKindVR.vrUS], 'Number of Zero Fills' );
     Add( $9067, 'BaselineCorrection', [TKindVR.vrCS], 'Baseline Correction' );
     Add( $9069, 'ParallelReductionFactorInPlane', [TKindVR.vrFD], 'Parallel Reduction Factor In-plane' );
     Add( $9070, 'CardiacRRIntervalSpecified', [TKindVR.vrFD], 'Cardiac R-R Interval Specified' );
     Add( $9073, 'AcquisitionDuration', [TKindVR.vrFD], 'Acquisition Duration' );
     Add( $9074, 'FrameAcquisitionDateTime', [TKindVR.vrDT], 'Frame Acquisition DateTime' );
     Add( $9075, 'DiffusionDirectionality', [TKindVR.vrCS], 'Diffusion Directionality' );
     Add( $9076, 'DiffusionGradientDirectionSequence', [TKindVR.vrSQ], 'Diffusion Gradient Direction Sequence' );
     Add( $9077, 'ParallelAcquisition', [TKindVR.vrCS], 'Parallel Acquisition' );
     Add( $9078, 'ParallelAcquisitionTechnique', [TKindVR.vrCS], 'Parallel Acquisition Technique' );
     Add( $9079, 'InversionTimes', [TKindVR.vrFD], 'Inversion Times' );
     Add( $9080, 'MetaboliteMapDescription', [TKindVR.vrST], 'Metabolite Map Description' );
     Add( $9081, 'PartialFourier', [TKindVR.vrCS], 'Partial Fourier' );
     Add( $9082, 'EffectiveEchoTime', [TKindVR.vrFD], 'Effective Echo Time' );
     Add( $9083, 'MetaboliteMapCodeSequence', [TKindVR.vrSQ], 'Metabolite Map Code Sequence' );
     Add( $9084, 'ChemicalShiftSequence', [TKindVR.vrSQ], 'Chemical Shift Sequence' );
     Add( $9085, 'CardiacSignalSource', [TKindVR.vrCS], 'Cardiac Signal Source' );
     Add( $9087, 'DiffusionBValue', [TKindVR.vrFD], 'Diffusion b-value' );
     Add( $9089, 'DiffusionGradientOrientation', [TKindVR.vrFD], 'Diffusion Gradient Orientation' );
     Add( $9090, 'VelocityEncodingDirection', [TKindVR.vrFD], 'Velocity Encoding Direction' );
     Add( $9091, 'VelocityEncodingMinimumValue', [TKindVR.vrFD], 'Velocity Encoding Minimum Value' );
     Add( $9092, 'VelocityEncodingAcquisitionSequence', [TKindVR.vrSQ], 'Velocity Encoding Acquisition Sequence' );
     Add( $9093, 'NumberOfKSpaceTrajectories', [TKindVR.vrUS], 'Number of k-Space Trajectories' );
     Add( $9094, 'CoverageOfKSpace', [TKindVR.vrCS], 'Coverage of k-Space' );
     Add( $9095, 'SpectroscopyAcquisitionPhaseRows', [TKindVR.vrUL], 'Spectroscopy Acquisition Phase Rows' );
     Add( $9096, 'ParallelReductionFactorInPlaneRetired', [TKindVR.vrFD], 'Parallel Reduction Factor In-plane (Retired)' );
     Add( $9098, 'TransmitterFrequency', [TKindVR.vrFD], 'Transmitter Frequency' );
     Add( $9100, 'ResonantNucleus', [TKindVR.vrCS], 'Resonant Nucleus' );
     Add( $9101, 'FrequencyCorrection', [TKindVR.vrCS], 'Frequency Correction' );
     Add( $9103, 'MRSpectroscopyFOVGeometrySequence', [TKindVR.vrSQ], 'MR Spectroscopy FOV/Geometry Sequence' );
     Add( $9104, 'SlabThickness', [TKindVR.vrFD], 'Slab Thickness' );
     Add( $9105, 'SlabOrientation', [TKindVR.vrFD], 'Slab Orientation' );
     Add( $9106, 'MidSlabPosition', [TKindVR.vrFD], 'Mid Slab Position' );
     Add( $9107, 'MRSpatialSaturationSequence', [TKindVR.vrSQ], 'MR Spatial Saturation Sequence' );
     Add( $9112, 'MRTimingAndRelatedParametersSequence', [TKindVR.vrSQ], 'MR Timing and Related Parameters Sequence' );
     Add( $9114, 'MREchoSequence', [TKindVR.vrSQ], 'MR Echo Sequence' );
     Add( $9115, 'MRModifierSequence', [TKindVR.vrSQ], 'MR Modifier Sequence' );
     Add( $9117, 'MRDiffusionSequence', [TKindVR.vrSQ], 'MR Diffusion Sequence' );
     Add( $9118, 'CardiacSynchronizationSequence', [TKindVR.vrSQ], 'Cardiac Synchronization Sequence' );
     Add( $9119, 'MRAveragesSequence', [TKindVR.vrSQ], 'MR Averages Sequence' );
     Add( $9125, 'MRFOVGeometrySequence', [TKindVR.vrSQ], 'MR FOV/Geometry Sequence' );
     Add( $9126, 'VolumeLocalizationSequence', [TKindVR.vrSQ], 'Volume Localization Sequence' );
     Add( $9127, 'SpectroscopyAcquisitionDataColumns', [TKindVR.vrUL], 'Spectroscopy Acquisition Data Columns' );
     Add( $9147, 'DiffusionAnisotropyType', [TKindVR.vrCS], 'Diffusion Anisotropy Type' );
     Add( $9151, 'FrameReferenceDateTime', [TKindVR.vrDT], 'Frame Reference DateTime' );
     Add( $9152, 'MRMetaboliteMapSequence', [TKindVR.vrSQ], 'MR Metabolite Map Sequence' );
     Add( $9155, 'ParallelReductionFactorOutOfPlane', [TKindVR.vrFD], 'Parallel Reduction Factor out-of-plane' );
     Add( $9159, 'SpectroscopyAcquisitionOutOfPlanePhaseSteps', [TKindVR.vrUL], 'Spectroscopy Acquisition Out-of-plane Phase Steps' );
     Add( $9166, 'BulkMotionStatus', [TKindVR.vrCS], 'Bulk Motion Status' );
     Add( $9168, 'ParallelReductionFactorSecondInPlane', [TKindVR.vrFD], 'Parallel Reduction Factor Second In-plane' );
     Add( $9169, 'CardiacBeatRejectionTechnique', [TKindVR.vrCS], 'Cardiac Beat Rejection Technique' );
     Add( $9170, 'RespiratoryMotionCompensationTechnique', [TKindVR.vrCS], 'Respiratory Motion Compensation Technique' );
     Add( $9171, 'RespiratorySignalSource', [TKindVR.vrCS], 'Respiratory Signal Source' );
     Add( $9172, 'BulkMotionCompensationTechnique', [TKindVR.vrCS], 'Bulk Motion Compensation Technique' );
     Add( $9173, 'BulkMotionSignalSource', [TKindVR.vrCS], 'Bulk Motion Signal Source' );
     Add( $9174, 'ApplicableSafetyStandardAgency', [TKindVR.vrCS], 'Applicable Safety Standard Agency' );
     Add( $9175, 'ApplicableSafetyStandardDescription', [TKindVR.vrLO], 'Applicable Safety Standard Description' );
     Add( $9176, 'OperatingModeSequence', [TKindVR.vrSQ], 'Operating Mode Sequence' );
     Add( $9177, 'OperatingModeType', [TKindVR.vrCS], 'Operating Mode Type' );
     Add( $9178, 'OperatingMode', [TKindVR.vrCS], 'Operating Mode' );
     Add( $9179, 'SpecificAbsorptionRateDefinition', [TKindVR.vrCS], 'Specific Absorption Rate Definition' );
     Add( $9180, 'GradientOutputType', [TKindVR.vrCS], 'Gradient Output Type' );
     Add( $9181, 'SpecificAbsorptionRateValue', [TKindVR.vrFD], 'Specific Absorption Rate Value' );
     Add( $9182, 'GradientOutput', [TKindVR.vrFD], 'Gradient Output' );
     Add( $9183, 'FlowCompensationDirection', [TKindVR.vrCS], 'Flow Compensation Direction' );
     Add( $9184, 'TaggingDelay', [TKindVR.vrFD], 'Tagging Delay' );
     Add( $9185, 'RespiratoryMotionCompensationTechniqueDescription', [TKindVR.vrST], 'Respiratory Motion Compensation Technique Description' );
     Add( $9186, 'RespiratorySignalSourceID', [TKindVR.vrSH], 'Respiratory Signal Source ID' );
     Add( $9195, 'ChemicalShiftMinimumIntegrationLimitInHz', [TKindVR.vrFD], 'Chemical Shift Minimum Integration Limit in Hz' );
     Add( $9196, 'ChemicalShiftMaximumIntegrationLimitInHz', [TKindVR.vrFD], 'Chemical Shift Maximum Integration Limit in Hz' );
     Add( $9197, 'MRVelocityEncodingSequence', [TKindVR.vrSQ], 'MR Velocity Encoding Sequence' );
     Add( $9198, 'FirstOrderPhaseCorrection', [TKindVR.vrCS], 'First Order Phase Correction' );
     Add( $9199, 'WaterReferencedPhaseCorrection', [TKindVR.vrCS], 'Water Referenced Phase Correction' );
     Add( $9200, 'MRSpectroscopyAcquisitionType', [TKindVR.vrCS], 'MR Spectroscopy Acquisition Type' );
     Add( $9214, 'RespiratoryCyclePosition', [TKindVR.vrCS], 'Respiratory Cycle Position' );
     Add( $9217, 'VelocityEncodingMaximumValue', [TKindVR.vrFD], 'Velocity Encoding Maximum Value' );
     Add( $9218, 'TagSpacingSecondDimension', [TKindVR.vrFD], 'Tag Spacing Second Dimension' );
     Add( $9219, 'TagAngleSecondAxis', [TKindVR.vrSS], 'Tag Angle Second Axis' );
     Add( $9220, 'FrameAcquisitionDuration', [TKindVR.vrFD], 'Frame Acquisition Duration' );
     Add( $9226, 'MRImageFrameTypeSequence', [TKindVR.vrSQ], 'MR Image Frame Type Sequence' );
     Add( $9227, 'MRSpectroscopyFrameTypeSequence', [TKindVR.vrSQ], 'MR Spectroscopy Frame Type Sequence' );
     Add( $9231, 'MRAcquisitionPhaseEncodingStepsInPlane', [TKindVR.vrUS], 'MR Acquisition Phase Encoding Steps in-plane' );
     Add( $9232, 'MRAcquisitionPhaseEncodingStepsOutOfPlane', [TKindVR.vrUS], 'MR Acquisition Phase Encoding Steps out-of-plane' );
     Add( $9234, 'SpectroscopyAcquisitionPhaseColumns', [TKindVR.vrUL], 'Spectroscopy Acquisition Phase Columns' );
     Add( $9236, 'CardiacCyclePosition', [TKindVR.vrCS], 'Cardiac Cycle Position' );
     Add( $9239, 'SpecificAbsorptionRateSequence', [TKindVR.vrSQ], 'Specific Absorption Rate Sequence' );
     Add( $9240, 'RFEchoTrainLength', [TKindVR.vrUS], 'RF Echo Train Length' );
     Add( $9241, 'GradientEchoTrainLength', [TKindVR.vrUS], 'Gradient Echo Train Length' );
     Add( $9250, 'ArterialSpinLabelingContrast', [TKindVR.vrCS], 'Arterial Spin Labeling Contrast' );
     Add( $9251, 'MRArterialSpinLabelingSequence', [TKindVR.vrSQ], 'MR Arterial Spin Labeling Sequence' );
     Add( $9252, 'ASLTechniqueDescription', [TKindVR.vrLO], 'ASL Technique Description' );
     Add( $9253, 'ASLSlabNumber', [TKindVR.vrUS], 'ASL Slab Number' );
     Add( $9254, 'ASLSlabThickness', [TKindVR.vrFD], 'ASL Slab Thickness' );
     Add( $9255, 'ASLSlabOrientation', [TKindVR.vrFD], 'ASL Slab Orientation' );
     Add( $9256, 'ASLMidSlabPosition', [TKindVR.vrFD], 'ASL Mid Slab Position' );
     Add( $9257, 'ASLContext', [TKindVR.vrCS], 'ASL Context' );
     Add( $9258, 'ASLPulseTrainDuration', [TKindVR.vrUL], 'ASL Pulse Train Duration' );
     Add( $9259, 'ASLCrusherFlag', [TKindVR.vrCS], 'ASL Crusher Flag' );
     Add( $925A, 'ASLCrusherFlowLimit', [TKindVR.vrFD], 'ASL Crusher Flow Limit' );
     Add( $925B, 'ASLCrusherDescription', [TKindVR.vrLO], 'ASL Crusher Description' );
     Add( $925C, 'ASLBolusCutoffFlag', [TKindVR.vrCS], 'ASL Bolus Cut-off Flag' );
     Add( $925D, 'ASLBolusCutoffTimingSequence', [TKindVR.vrSQ], 'ASL Bolus Cut-off Timing Sequence' );
     Add( $925E, 'ASLBolusCutoffTechnique', [TKindVR.vrLO], 'ASL Bolus Cut-off Technique' );
     Add( $925F, 'ASLBolusCutoffDelayTime', [TKindVR.vrUL], 'ASL Bolus Cut-off Delay Time' );
     Add( $9260, 'ASLSlabSequence', [TKindVR.vrSQ], 'ASL Slab Sequence' );
     Add( $9295, 'ChemicalShiftMinimumIntegrationLimitInppm', [TKindVR.vrFD], 'Chemical Shift Minimum Integration Limit in ppm' );
     Add( $9296, 'ChemicalShiftMaximumIntegrationLimitInppm', [TKindVR.vrFD], 'Chemical Shift Maximum Integration Limit in ppm' );
     Add( $9297, 'WaterReferenceAcquisition', [TKindVR.vrCS], 'Water Reference Acquisition' );
     Add( $9298, 'EchoPeakPosition', [TKindVR.vrIS], 'Echo Peak Position' );
     Add( $9301, 'CTAcquisitionTypeSequence', [TKindVR.vrSQ], 'CT Acquisition Type Sequence' );
     Add( $9302, 'AcquisitionType', [TKindVR.vrCS], 'Acquisition Type' );
     Add( $9303, 'TubeAngle', [TKindVR.vrFD], 'Tube Angle' );
     Add( $9304, 'CTAcquisitionDetailsSequence', [TKindVR.vrSQ], 'CT Acquisition Details Sequence' );
     Add( $9305, 'RevolutionTime', [TKindVR.vrFD], 'Revolution Time' );
     Add( $9306, 'SingleCollimationWidth', [TKindVR.vrFD], 'Single Collimation Width' );
     Add( $9307, 'TotalCollimationWidth', [TKindVR.vrFD], 'Total Collimation Width' );
     Add( $9308, 'CTTableDynamicsSequence', [TKindVR.vrSQ], 'CT Table Dynamics Sequence' );
     Add( $9309, 'TableSpeed', [TKindVR.vrFD], 'Table Speed' );
     Add( $9310, 'TableFeedPerRotation', [TKindVR.vrFD], 'Table Feed per Rotation' );
     Add( $9311, 'SpiralPitchFactor', [TKindVR.vrFD], 'Spiral Pitch Factor' );
     Add( $9312, 'CTGeometrySequence', [TKindVR.vrSQ], 'CT Geometry Sequence' );
     Add( $9313, 'DataCollectionCenterPatient', [TKindVR.vrFD], 'Data Collection Center (Patient)' );
     Add( $9314, 'CTReconstructionSequence', [TKindVR.vrSQ], 'CT Reconstruction Sequence' );
     Add( $9315, 'ReconstructionAlgorithm', [TKindVR.vrCS], 'Reconstruction Algorithm' );
     Add( $9316, 'ConvolutionKernelGroup', [TKindVR.vrCS], 'Convolution Kernel Group' );
     Add( $9317, 'ReconstructionFieldOfView', [TKindVR.vrFD], 'Reconstruction Field of View' );
     Add( $9318, 'ReconstructionTargetCenterPatient', [TKindVR.vrFD], 'Reconstruction Target Center (Patient)' );
     Add( $9319, 'ReconstructionAngle', [TKindVR.vrFD], 'Reconstruction Angle' );
     Add( $9320, 'ImageFilter', [TKindVR.vrSH], 'Image Filter' );
     Add( $9321, 'CTExposureSequence', [TKindVR.vrSQ], 'CT Exposure Sequence' );
     Add( $9322, 'ReconstructionPixelSpacing', [TKindVR.vrFD], 'Reconstruction Pixel Spacing' );
     Add( $9323, 'ExposureModulationType', [TKindVR.vrCS], 'Exposure Modulation Type' );
     Add( $9324, 'EstimatedDoseSaving', [TKindVR.vrFD], 'Estimated Dose Saving' );
     Add( $9325, 'CTXRayDetailsSequence', [TKindVR.vrSQ], 'CT X-Ray Details Sequence' );
     Add( $9326, 'CTPositionSequence', [TKindVR.vrSQ], 'CT Position Sequence' );
     Add( $9327, 'TablePosition', [TKindVR.vrFD], 'Table Position' );
     Add( $9328, 'ExposureTimeInms', [TKindVR.vrFD], 'Exposure Time in ms' );
     Add( $9329, 'CTImageFrameTypeSequence', [TKindVR.vrSQ], 'CT Image Frame Type Sequence' );
     Add( $9330, 'XRayTubeCurrentInmA', [TKindVR.vrFD], 'X-Ray Tube Current in mA' );
     Add( $9332, 'ExposureInmAs', [TKindVR.vrFD], 'Exposure in mAs' );
     Add( $9333, 'ConstantVolumeFlag', [TKindVR.vrCS], 'Constant Volume Flag' );
     Add( $9334, 'FluoroscopyFlag', [TKindVR.vrCS], 'Fluoroscopy Flag' );
     Add( $9335, 'DistanceSourceToDataCollectionCenter', [TKindVR.vrFD], 'Distance Source to Data Collection Center' );
     Add( $9337, 'ContrastBolusAgentNumber', [TKindVR.vrUS], 'Contrast/Bolus Agent Number' );
     Add( $9338, 'ContrastBolusIngredientCodeSequence', [TKindVR.vrSQ], 'Contrast/Bolus Ingredient Code Sequence' );
     Add( $9340, 'ContrastAdministrationProfileSequence', [TKindVR.vrSQ], 'Contrast Administration Profile Sequence' );
     Add( $9341, 'ContrastBolusUsageSequence', [TKindVR.vrSQ], 'Contrast/Bolus Usage Sequence' );
     Add( $9342, 'ContrastBolusAgentAdministered', [TKindVR.vrCS], 'Contrast/Bolus Agent Administered' );
     Add( $9343, 'ContrastBolusAgentDetected', [TKindVR.vrCS], 'Contrast/Bolus Agent Detected' );
     Add( $9344, 'ContrastBolusAgentPhase', [TKindVR.vrCS], 'Contrast/Bolus Agent Phase' );
     Add( $9345, 'CTDIvol', [TKindVR.vrFD], 'CTDIvol' );
     Add( $9346, 'CTDIPhantomTypeCodeSequence', [TKindVR.vrSQ], 'CTDI Phantom Type Code Sequence' );
     Add( $9351, 'CalciumScoringMassFactorPatient', [TKindVR.vrFL], 'Calcium Scoring Mass Factor Patient' );
     Add( $9352, 'CalciumScoringMassFactorDevice', [TKindVR.vrFL], 'Calcium Scoring Mass Factor Device' );
     Add( $9353, 'EnergyWeightingFactor', [TKindVR.vrFL], 'Energy Weighting Factor' );
     Add( $9360, 'CTAdditionalXRaySourceSequence', [TKindVR.vrSQ], 'CT Additional X-Ray Source Sequence' );
     Add( $9401, 'ProjectionPixelCalibrationSequence', [TKindVR.vrSQ], 'Projection Pixel Calibration Sequence' );
     Add( $9402, 'DistanceSourceToIsocenter', [TKindVR.vrFL], 'Distance Source to Isocenter' );
     Add( $9403, 'DistanceObjectToTableTop', [TKindVR.vrFL], 'Distance Object to Table Top' );
     Add( $9404, 'ObjectPixelSpacingInCenterOfBeam', [TKindVR.vrFL], 'Object Pixel Spacing in Center of Beam' );
     Add( $9405, 'PositionerPositionSequence', [TKindVR.vrSQ], 'Positioner Position Sequence' );
     Add( $9406, 'TablePositionSequence', [TKindVR.vrSQ], 'Table Position Sequence' );
     Add( $9407, 'CollimatorShapeSequence', [TKindVR.vrSQ], 'Collimator Shape Sequence' );
     Add( $9410, 'PlanesInAcquisition', [TKindVR.vrCS], 'Planes in Acquisition' );
     Add( $9412, 'XAXRFFrameCharacteristicsSequence', [TKindVR.vrSQ], 'XA/XRF Frame Characteristics Sequence' );
     Add( $9417, 'FrameAcquisitionSequence', [TKindVR.vrSQ], 'Frame Acquisition Sequence' );
     Add( $9420, 'XRayReceptorType', [TKindVR.vrCS], 'X-Ray Receptor Type' );
     Add( $9423, 'AcquisitionProtocolName', [TKindVR.vrLO], 'Acquisition Protocol Name' );
     Add( $9424, 'AcquisitionProtocolDescription', [TKindVR.vrLT], 'Acquisition Protocol Description' );
     Add( $9425, 'ContrastBolusIngredientOpaque', [TKindVR.vrCS], 'Contrast/Bolus Ingredient Opaque' );
     Add( $9426, 'DistanceReceptorPlaneToDetectorHousing', [TKindVR.vrFL], 'Distance Receptor Plane to Detector Housing' );
     Add( $9427, 'IntensifierActiveShape', [TKindVR.vrCS], 'Intensifier Active Shape' );
     Add( $9428, 'IntensifierActiveDimensions', [TKindVR.vrFL], 'Intensifier Active Dimension(s)' );
     Add( $9429, 'PhysicalDetectorSize', [TKindVR.vrFL], 'Physical Detector Size' );
     Add( $9430, 'PositionOfIsocenterProjection', [TKindVR.vrFL], 'Position of Isocenter Projection' );
     Add( $9432, 'FieldOfViewSequence', [TKindVR.vrSQ], 'Field of View Sequence' );
     Add( $9433, 'FieldOfViewDescription', [TKindVR.vrLO], 'Field of View Description' );
     Add( $9434, 'ExposureControlSensingRegionsSequence', [TKindVR.vrSQ], 'Exposure Control Sensing Regions Sequence' );
     Add( $9435, 'ExposureControlSensingRegionShape', [TKindVR.vrCS], 'Exposure Control Sensing Region Shape' );
     Add( $9436, 'ExposureControlSensingRegionLeftVerticalEdge', [TKindVR.vrSS], 'Exposure Control Sensing Region Left Vertical Edge' );
     Add( $9437, 'ExposureControlSensingRegionRightVerticalEdge', [TKindVR.vrSS], 'Exposure Control Sensing Region Right Vertical Edge' );
     Add( $9438, 'ExposureControlSensingRegionUpperHorizontalEdge', [TKindVR.vrSS], 'Exposure Control Sensing Region Upper Horizontal Edge' );
     Add( $9439, 'ExposureControlSensingRegionLowerHorizontalEdge', [TKindVR.vrSS], 'Exposure Control Sensing Region Lower Horizontal Edge' );
     Add( $9440, 'CenterOfCircularExposureControlSensingRegion', [TKindVR.vrSS], 'Center of Circular Exposure Control Sensing Region' );
     Add( $9441, 'RadiusOfCircularExposureControlSensingRegion', [TKindVR.vrUS], 'Radius of Circular Exposure Control Sensing Region' );
     Add( $9442, 'VerticesOfThePolygonalExposureControlSensingRegion', [TKindVR.vrSS], 'Vertices of the Polygonal Exposure Control Sensing Region' );
     Add( $9445, '', [], '' );  //For some Data Elements, no Name or Keyword or VR or VM is specified; these are "placeholders" that are not assigned but will not be reused.
     Add( $9447, 'ColumnAngulationPatient', [TKindVR.vrFL], 'Column Angulation (Patient)' );
     Add( $9449, 'BeamAngle', [TKindVR.vrFL], 'Beam Angle' );
     Add( $9451, 'FrameDetectorParametersSequence', [TKindVR.vrSQ], 'Frame Detector Parameters Sequence' );
     Add( $9452, 'CalculatedAnatomyThickness', [TKindVR.vrFL], 'Calculated Anatomy Thickness' );
     Add( $9455, 'CalibrationSequence', [TKindVR.vrSQ], 'Calibration Sequence' );
     Add( $9456, 'ObjectThicknessSequence', [TKindVR.vrSQ], 'Object Thickness Sequence' );
     Add( $9457, 'PlaneIdentification', [TKindVR.vrCS], 'Plane Identification' );
     Add( $9461, 'FieldOfViewDimensionsInFloat', [TKindVR.vrFL], 'Field of View Dimension(s) in Float' );
     Add( $9462, 'IsocenterReferenceSystemSequence', [TKindVR.vrSQ], 'Isocenter Reference System Sequence' );
     Add( $9463, 'PositionerIsocenterPrimaryAngle', [TKindVR.vrFL], 'Positioner Isocenter Primary Angle' );
     Add( $9464, 'PositionerIsocenterSecondaryAngle', [TKindVR.vrFL], 'Positioner Isocenter Secondary Angle' );
     Add( $9465, 'PositionerIsocenterDetectorRotationAngle', [TKindVR.vrFL], 'Positioner Isocenter Detector Rotation Angle' );
     Add( $9466, 'TableXPositionToIsocenter', [TKindVR.vrFL], 'Table X Position to Isocenter' );
     Add( $9467, 'TableYPositionToIsocenter', [TKindVR.vrFL], 'Table Y Position to Isocenter' );
     Add( $9468, 'TableZPositionToIsocenter', [TKindVR.vrFL], 'Table Z Position to Isocenter' );
     Add( $9469, 'TableHorizontalRotationAngle', [TKindVR.vrFL], 'Table Horizontal Rotation Angle' );
     Add( $9470, 'TableHeadTiltAngle', [TKindVR.vrFL], 'Table Head Tilt Angle' );
     Add( $9471, 'TableCradleTiltAngle', [TKindVR.vrFL], 'Table Cradle Tilt Angle' );
     Add( $9472, 'FrameDisplayShutterSequence', [TKindVR.vrSQ], 'Frame Display Shutter Sequence' );
     Add( $9473, 'AcquiredImageAreaDoseProduct', [TKindVR.vrFL], 'Acquired Image Area Dose Product' );
     Add( $9474, 'CArmPositionerTabletopRelationship', [TKindVR.vrCS], 'C-arm Positioner Tabletop Relationship' );
     Add( $9476, 'XRayGeometrySequence', [TKindVR.vrSQ], 'X-Ray Geometry Sequence' );
     Add( $9477, 'IrradiationEventIdentificationSequence', [TKindVR.vrSQ], 'Irradiation Event Identification Sequence' );
     Add( $9504, 'XRay3DFrameTypeSequence', [TKindVR.vrSQ], 'X-Ray 3D Frame Type Sequence' );
     Add( $9506, 'ContributingSourcesSequence', [TKindVR.vrSQ], 'Contributing Sources Sequence' );
     Add( $9507, 'XRay3DAcquisitionSequence', [TKindVR.vrSQ], 'X-Ray 3D Acquisition Sequence' );
     Add( $9508, 'PrimaryPositionerScanArc', [TKindVR.vrFL], 'Primary Positioner Scan Arc' );
     Add( $9509, 'SecondaryPositionerScanArc', [TKindVR.vrFL], 'Secondary Positioner Scan Arc' );
     Add( $9510, 'PrimaryPositionerScanStartAngle', [TKindVR.vrFL], 'Primary Positioner Scan Start Angle' );
     Add( $9511, 'SecondaryPositionerScanStartAngle', [TKindVR.vrFL], 'Secondary Positioner Scan Start Angle' );
     Add( $9514, 'PrimaryPositionerIncrement', [TKindVR.vrFL], 'Primary Positioner Increment' );
     Add( $9515, 'SecondaryPositionerIncrement', [TKindVR.vrFL], 'Secondary Positioner Increment' );
     Add( $9516, 'StartAcquisitionDateTime', [TKindVR.vrDT], 'Start Acquisition DateTime' );
     Add( $9517, 'EndAcquisitionDateTime', [TKindVR.vrDT], 'End Acquisition DateTime' );
     Add( $9518, 'PrimaryPositionerIncrementSign', [TKindVR.vrSS], 'Primary Positioner Increment Sign' );
     Add( $9519, 'SecondaryPositionerIncrementSign', [TKindVR.vrSS], 'Secondary Positioner Increment Sign' );
     Add( $9524, 'ApplicationName', [TKindVR.vrLO], 'Application Name' );
     Add( $9525, 'ApplicationVersion', [TKindVR.vrLO], 'Application Version' );
     Add( $9526, 'ApplicationManufacturer', [TKindVR.vrLO], 'Application Manufacturer' );
     Add( $9527, 'AlgorithmType', [TKindVR.vrCS], 'Algorithm Type' );
     Add( $9528, 'AlgorithmDescription', [TKindVR.vrLO], 'Algorithm Description' );
     Add( $9530, 'XRay3DReconstructionSequence', [TKindVR.vrSQ], 'X-Ray 3D Reconstruction Sequence' );
     Add( $9531, 'ReconstructionDescription', [TKindVR.vrLO], 'Reconstruction Description' );
     Add( $9538, 'PerProjectionAcquisitionSequence', [TKindVR.vrSQ], 'Per Projection Acquisition Sequence' );
     Add( $9541, 'DetectorPositionSequence', [TKindVR.vrSQ], 'Detector Position Sequence' );
     Add( $9542, 'XRayAcquisitionDoseSequence', [TKindVR.vrSQ], 'X-Ray Acquisition Dose Sequence' );
     Add( $9543, 'XRaySourceIsocenterPrimaryAngle', [TKindVR.vrFD], 'X-Ray Source Isocenter Primary Angle' );
     Add( $9544, 'XRaySourceIsocenterSecondaryAngle', [TKindVR.vrFD], 'X-Ray Source Isocenter Secondary Angle' );
     Add( $9545, 'BreastSupportIsocenterPrimaryAngle', [TKindVR.vrFD], 'Breast Support Isocenter Primary Angle' );
     Add( $9546, 'BreastSupportIsocenterSecondaryAngle', [TKindVR.vrFD], 'Breast Support Isocenter Secondary Angle' );
     Add( $9547, 'BreastSupportXPositionToIsocenter', [TKindVR.vrFD], 'Breast Support X Position to Isocenter' );
     Add( $9548, 'BreastSupportYPositionToIsocenter', [TKindVR.vrFD], 'Breast Support Y Position to Isocenter' );
     Add( $9549, 'BreastSupportZPositionToIsocenter', [TKindVR.vrFD], 'Breast Support Z Position to Isocenter' );
     Add( $9550, 'DetectorIsocenterPrimaryAngle', [TKindVR.vrFD], 'Detector Isocenter Primary Angle' );
     Add( $9551, 'DetectorIsocenterSecondaryAngle', [TKindVR.vrFD], 'Detector Isocenter Secondary Angle' );
     Add( $9552, 'DetectorXPositionToIsocenter', [TKindVR.vrFD], 'Detector X Position to Isocenter' );
     Add( $9553, 'DetectorYPositionToIsocenter', [TKindVR.vrFD], 'Detector Y Position to Isocenter' );
     Add( $9554, 'DetectorZPositionToIsocenter', [TKindVR.vrFD], 'Detector Z Position to Isocenter' );
     Add( $9555, 'XRayGridSequence', [TKindVR.vrSQ], 'X-Ray Grid Sequence' );
     Add( $9556, 'XRayFilterSequence', [TKindVR.vrSQ], 'X-Ray Filter Sequence' );
     Add( $9557, 'DetectorActiveAreaTLHCPosition', [TKindVR.vrFD], 'Detector Active Area TLHC Position' );
     Add( $9558, 'DetectorActiveAreaOrientation', [TKindVR.vrFD], 'Detector Active Area Orientation' );
     Add( $9559, 'PositionerPrimaryAngleDirection', [TKindVR.vrCS], 'Positioner Primary Angle Direction' );
     Add( $9601, 'DiffusionBMatrixSequence', [TKindVR.vrSQ], 'Diffusion b-matrix Sequence' );
     Add( $9602, 'DiffusionBValueXX', [TKindVR.vrFD], 'Diffusion b-value XX' );
     Add( $9603, 'DiffusionBValueXY', [TKindVR.vrFD], 'Diffusion b-value XY' );
     Add( $9604, 'DiffusionBValueXZ', [TKindVR.vrFD], 'Diffusion b-value XZ' );
     Add( $9605, 'DiffusionBValueYY', [TKindVR.vrFD], 'Diffusion b-value YY' );
     Add( $9606, 'DiffusionBValueYZ', [TKindVR.vrFD], 'Diffusion b-value YZ' );
     Add( $9607, 'DiffusionBValueZZ', [TKindVR.vrFD], 'Diffusion b-value ZZ' );
     Add( $9621, 'FunctionalMRSequence', [TKindVR.vrSQ], 'Functional MR Sequence' );
     Add( $9622, 'FunctionalSettlingPhaseFramesPresent', [TKindVR.vrCS], 'Functional Settling Phase Frames Present' );
     Add( $9623, 'FunctionalSyncPulse', [TKindVR.vrDT], 'Functional Sync Pulse' );
     Add( $9624, 'SettlingPhaseFrame', [TKindVR.vrCS], 'Settling Phase Frame' );
     Add( $9701, 'DecayCorrectionDateTime', [TKindVR.vrDT], 'Decay Correction DateTime' );
     Add( $9715, 'StartDensityThreshold', [TKindVR.vrFD], 'Start Density Threshold' );
     Add( $9716, 'StartRelativeDensityDifferenceThreshold', [TKindVR.vrFD], 'Start Relative Density Difference Threshold' );
     Add( $9717, 'StartCardiacTriggerCountThreshold', [TKindVR.vrFD], 'Start Cardiac Trigger Count Threshold' );
     Add( $9718, 'StartRespiratoryTriggerCountThreshold', [TKindVR.vrFD], 'Start Respiratory Trigger Count Threshold' );
     Add( $9719, 'TerminationCountsThreshold', [TKindVR.vrFD], 'Termination Counts Threshold' );
     Add( $9720, 'TerminationDensityThreshold', [TKindVR.vrFD], 'Termination Density Threshold' );
     Add( $9721, 'TerminationRelativeDensityThreshold', [TKindVR.vrFD], 'Termination Relative Density Threshold' );
     Add( $9722, 'TerminationTimeThreshold', [TKindVR.vrFD], 'Termination Time Threshold' );
     Add( $9723, 'TerminationCardiacTriggerCountThreshold', [TKindVR.vrFD], 'Termination Cardiac Trigger Count Threshold' );
     Add( $9724, 'TerminationRespiratoryTriggerCountThreshold', [TKindVR.vrFD], 'Termination Respiratory Trigger Count Threshold' );
     Add( $9725, 'DetectorGeometry', [TKindVR.vrCS], 'Detector Geometry' );
     Add( $9726, 'TransverseDetectorSeparation', [TKindVR.vrFD], 'Transverse Detector Separation' );
     Add( $9727, 'AxialDetectorDimension', [TKindVR.vrFD], 'Axial Detector Dimension' );
     Add( $9729, 'RadiopharmaceuticalAgentNumber', [TKindVR.vrUS], 'Radiopharmaceutical Agent Number' );
     Add( $9732, 'PETFrameAcquisitionSequence', [TKindVR.vrSQ], 'PET Frame Acquisition Sequence' );
     Add( $9733, 'PETDetectorMotionDetailsSequence', [TKindVR.vrSQ], 'PET Detector Motion Details Sequence' );
     Add( $9734, 'PETTableDynamicsSequence', [TKindVR.vrSQ], 'PET Table Dynamics Sequence' );
     Add( $9735, 'PETPositionSequence', [TKindVR.vrSQ], 'PET Position Sequence' );
     Add( $9736, 'PETFrameCorrectionFactorsSequence', [TKindVR.vrSQ], 'PET Frame Correction Factors Sequence' );
     Add( $9737, 'RadiopharmaceuticalUsageSequence', [TKindVR.vrSQ], 'Radiopharmaceutical Usage Sequence' );
     Add( $9738, 'AttenuationCorrectionSource', [TKindVR.vrCS], 'Attenuation Correction Source' );
     Add( $9739, 'NumberOfIterations', [TKindVR.vrUS], 'Number of Iterations' );
     Add( $9740, 'NumberOfSubsets', [TKindVR.vrUS], 'Number of Subsets' );
     Add( $9749, 'PETReconstructionSequence', [TKindVR.vrSQ], 'PET Reconstruction Sequence' );
     Add( $9751, 'PETFrameTypeSequence', [TKindVR.vrSQ], 'PET Frame Type Sequence' );
     Add( $9755, 'TimeOfFlightInformationUsed', [TKindVR.vrCS], 'Time of Flight Information Used' );
     Add( $9756, 'ReconstructionType', [TKindVR.vrCS], 'Reconstruction Type' );
     Add( $9758, 'DecayCorrected', [TKindVR.vrCS], 'Decay Corrected' );
     Add( $9759, 'AttenuationCorrected', [TKindVR.vrCS], 'Attenuation Corrected' );
     Add( $9760, 'ScatterCorrected', [TKindVR.vrCS], 'Scatter Corrected' );
     Add( $9761, 'DeadTimeCorrected', [TKindVR.vrCS], 'Dead Time Corrected' );
     Add( $9762, 'GantryMotionCorrected', [TKindVR.vrCS], 'Gantry Motion Corrected' );
     Add( $9763, 'PatientMotionCorrected', [TKindVR.vrCS], 'Patient Motion Corrected' );
     Add( $9764, 'CountLossNormalizationCorrected', [TKindVR.vrCS], 'Count Loss Normalization Corrected' );
     Add( $9765, 'RandomsCorrected', [TKindVR.vrCS], 'Randoms Corrected' );
     Add( $9766, 'NonUniformRadialSamplingCorrected', [TKindVR.vrCS], 'Non-uniform Radial Sampling Corrected' );
     Add( $9767, 'SensitivityCalibrated', [TKindVR.vrCS], 'Sensitivity Calibrated' );
     Add( $9768, 'DetectorNormalizationCorrection', [TKindVR.vrCS], 'Detector Normalization Correction' );
     Add( $9769, 'IterativeReconstructionMethod', [TKindVR.vrCS], 'Iterative Reconstruction Method' );
     Add( $9770, 'AttenuationCorrectionTemporalRelationship', [TKindVR.vrCS], 'Attenuation Correction Temporal Relationship' );
     Add( $9771, 'PatientPhysiologicalStateSequence', [TKindVR.vrSQ], 'Patient Physiological State Sequence' );
     Add( $9772, 'PatientPhysiologicalStateCodeSequence', [TKindVR.vrSQ], 'Patient Physiological State Code Sequence' );
     Add( $9801, 'DepthsOfFocus', [TKindVR.vrFD], 'Depth(s) of Focus' );
     Add( $9803, 'ExcludedIntervalsSequence', [TKindVR.vrSQ], 'Excluded Intervals Sequence' );
     Add( $9804, 'ExclusionStartDateTime', [TKindVR.vrDT], 'Exclusion Start DateTime' );
     Add( $9805, 'ExclusionDuration', [TKindVR.vrFD], 'Exclusion Duration' );
     Add( $9806, 'USImageDescriptionSequence', [TKindVR.vrSQ], 'US Image Description Sequence' );
     Add( $9807, 'ImageDataTypeSequence', [TKindVR.vrSQ], 'Image Data Type Sequence' );
     Add( $9808, 'DataType', [TKindVR.vrCS], 'Data Type' );
     Add( $9809, 'TransducerScanPatternCodeSequence', [TKindVR.vrSQ], 'Transducer Scan Pattern Code Sequence' );
     Add( $980B, 'AliasedDataType', [TKindVR.vrCS], 'Aliased Data Type' );
     Add( $980C, 'PositionMeasuringDeviceUsed', [TKindVR.vrCS], 'Position Measuring Device Used' );
     Add( $980D, 'TransducerGeometryCodeSequence', [TKindVR.vrSQ], 'Transducer Geometry Code Sequence' );
     Add( $980E, 'TransducerBeamSteeringCodeSequence', [TKindVR.vrSQ], 'Transducer Beam Steering Code Sequence' );
     Add( $980F, 'TransducerApplicationCodeSequence', [TKindVR.vrSQ], 'Transducer Application Code Sequence' );
     Add( $9810, 'ZeroVelocityPixelValue', [TKindVR.vrUS,TKindVR.vrSS], 'Zero Velocity Pixel Value' );
     Add( $9900, 'ReferenceLocationLabel', [TKindVR.vrLO], 'Reference Location Label' );
     Add( $9901, 'ReferenceLocationDescription', [TKindVR.vrUT], 'Reference Location Description' );
     Add( $9902, 'ReferenceBasisCodeSequence', [TKindVR.vrSQ], 'Reference Basis Code Sequence' );
     Add( $9903, 'ReferenceGeometryCodeSequence', [TKindVR.vrSQ], 'Reference Geometry Code Sequence' );
     Add( $9904, 'OffsetDistance', [TKindVR.vrDS], 'Offset Distance' );
     Add( $9905, 'OffsetDirection', [TKindVR.vrCS], 'Offset Direction' );
     Add( $9906, 'PotentialScheduledProtocolCodeSequence', [TKindVR.vrSQ], 'Potential Scheduled Protocol Code Sequence' );
     Add( $9907, 'PotentialRequestedProcedureCodeSequence', [TKindVR.vrSQ], 'Potential Requested Procedure Code Sequence' );
     Add( $9908, 'PotentialReasonsForProcedure', [TKindVR.vrUC], 'Potential Reasons for Procedure' );
     Add( $9909, 'PotentialReasonsForProcedureCodeSequence', [TKindVR.vrSQ], 'Potential Reasons for Procedure Code Sequence' );
     Add( $990A, 'PotentialDiagnosticTasks', [TKindVR.vrUC], 'Potential Diagnostic Tasks' );
     Add( $990B, 'ContraindicationsCodeSequence', [TKindVR.vrSQ], 'Contraindications Code Sequence' );
     Add( $990C, 'ReferencedDefinedProtocolSequence', [TKindVR.vrSQ], 'Referenced Defined Protocol Sequence' );
     Add( $990D, 'ReferencedPerformedProtocolSequence', [TKindVR.vrSQ], 'Referenced Performed Protocol Sequence' );
     Add( $990E, 'PredecessorProtocolSequence', [TKindVR.vrSQ], 'Predecessor Protocol Sequence' );
     Add( $990F, 'ProtocolPlanningInformation', [TKindVR.vrUT], 'Protocol Planning Information' );
     Add( $9910, 'ProtocolDesignRationale', [TKindVR.vrUT], 'Protocol Design Rationale' );
     Add( $9911, 'PatientSpecificationSequence', [TKindVR.vrSQ], 'Patient Specification Sequence' );
     Add( $9912, 'ModelSpecificationSequence', [TKindVR.vrSQ], 'Model Specification Sequence' );
     Add( $9913, 'ParametersSpecificationSequence', [TKindVR.vrSQ], 'Parameters Specification Sequence' );
     Add( $9914, 'InstructionSequence', [TKindVR.vrSQ], 'Instruction Sequence' );
     Add( $9915, 'InstructionIndex', [TKindVR.vrUS], 'Instruction Index' );
     Add( $9916, 'InstructionText', [TKindVR.vrLO], 'Instruction Text' );
     Add( $9917, 'InstructionDescription', [TKindVR.vrUT], 'Instruction Description' );
     Add( $9918, 'InstructionPerformedFlag', [TKindVR.vrCS], 'Instruction Performed Flag' );
     Add( $9919, 'InstructionPerformedDateTime', [TKindVR.vrDT], 'Instruction Performed DateTime' );
     Add( $991A, 'InstructionPerformanceComment', [TKindVR.vrUT], 'Instruction Performance Comment' );
     Add( $991B, 'PatientPositioningInstructionSequence', [TKindVR.vrSQ], 'Patient Positioning Instruction Sequence' );
     Add( $991C, 'PositioningMethodCodeSequence', [TKindVR.vrSQ], 'Positioning Method Code Sequence' );
     Add( $991D, 'PositioningLandmarkSequence', [TKindVR.vrSQ], 'Positioning Landmark Sequence' );
     Add( $991E, 'TargetFrameOfReferenceUID', [TKindVR.vrUI], 'Target Frame of Reference UID' );
     Add( $991F, 'AcquisitionProtocolElementSpecificationSequence', [TKindVR.vrSQ], 'Acquisition Protocol Element Specification Sequence' );
     Add( $9920, 'AcquisitionProtocolElementSequence', [TKindVR.vrSQ], 'Acquisition Protocol Element Sequence' );
     Add( $9921, 'ProtocolElementNumber', [TKindVR.vrUS], 'Protocol Element Number' );
     Add( $9922, 'ProtocolElementName', [TKindVR.vrLO], 'Protocol Element Name' );
     Add( $9923, 'ProtocolElementCharacteristicsSummary', [TKindVR.vrUT], 'Protocol Element Characteristics Summary' );
     Add( $9924, 'ProtocolElementPurpose', [TKindVR.vrUT], 'Protocol Element Purpose' );
     Add( $9930, 'AcquisitionMotion', [TKindVR.vrCS], 'Acquisition Motion' );
     Add( $9931, 'AcquisitionStartLocationSequence', [TKindVR.vrSQ], 'Acquisition Start Location Sequence' );
     Add( $9932, 'AcquisitionEndLocationSequence', [TKindVR.vrSQ], 'Acquisition End Location Sequence' );
     Add( $9933, 'ReconstructionProtocolElementSpecificationSequence', [TKindVR.vrSQ], 'Reconstruction Protocol Element Specification Sequence' );
     Add( $9934, 'ReconstructionProtocolElementSequence', [TKindVR.vrSQ], 'Reconstruction Protocol Element Sequence' );
     Add( $9935, 'StorageProtocolElementSpecificationSequence', [TKindVR.vrSQ], 'Storage Protocol Element Specification Sequence' );
     Add( $9936, 'StorageProtocolElementSequence', [TKindVR.vrSQ], 'Storage Protocol Element Sequence' );
     Add( $9937, 'RequestedSeriesDescription', [TKindVR.vrLO], 'Requested Series Description' );
     Add( $9938, 'SourceAcquisitionProtocolElementNumber', [TKindVR.vrUS], 'Source Acquisition Protocol Element Number' );
     Add( $9939, 'SourceAcquisitionBeamNumber', [TKindVR.vrUS], 'Source Acquisition Beam Number' );
     Add( $993A, 'SourceReconstructionProtocolElementNumber', [TKindVR.vrUS], 'Source Reconstruction Protocol Element Number' );
     Add( $993B, 'ReconstructionStartLocationSequence', [TKindVR.vrSQ], 'Reconstruction Start Location Sequence' );
     Add( $993C, 'ReconstructionEndLocationSequence', [TKindVR.vrSQ], 'Reconstruction End Location Sequence' );
     Add( $993D, 'ReconstructionAlgorithmSequence', [TKindVR.vrSQ], 'Reconstruction Algorithm Sequence' );
     Add( $993E, 'ReconstructionTargetCenterLocationSequence', [TKindVR.vrSQ], 'Reconstruction Target Center Location Sequence' );
     Add( $9941, 'ImageFilterDescription', [TKindVR.vrUT], 'Image Filter Description' );
     Add( $9942, 'CTDIvolNotificationTrigger', [TKindVR.vrFD], 'CTDIvol Notification Trigger' );
     Add( $9943, 'DLPNotificationTrigger', [TKindVR.vrFD], 'DLP Notification Trigger' );
     Add( $9944, 'AutoKVPSelectionType', [TKindVR.vrCS], 'Auto KVP Selection Type' );
     Add( $9945, 'AutoKVPUpperBound', [TKindVR.vrFD], 'Auto KVP Upper Bound' );
     Add( $9946, 'AutoKVPLowerBound', [TKindVR.vrFD], 'Auto KVP Lower Bound' );
     Add( $9947, 'ProtocolDefinedPatientPosition', [TKindVR.vrCS], 'Protocol Defined Patient Position' );
     Add( $A001, 'ContributingEquipmentSequence', [TKindVR.vrSQ], 'Contributing Equipment Sequence' );
     Add( $A002, 'ContributionDateTime', [TKindVR.vrDT], 'Contribution DateTime' );
     Add( $A003, 'ContributionDescription', [TKindVR.vrST], 'Contribution Description' );
end;

//$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$【ルーチン】

//############################################################################## □

initialization //$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$ 初期化

finalization //$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$ 最終化

end. //######################################################################### ■
