unit LUX.DICOM.Tags.G0018;

interface //#################################################################### ■

uses LUX, LUX.DICOM.Tags, LUX.DICOM.VRs;

type //$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$【型】

     //$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$【レコード】

     //$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$【クラス】

     //%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% TDICOMElems0018

     TDICOMElems0018 = class( TDICOMElems )
     private
     protected
     public
       constructor Create;
     end;

//const //$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$【定数】

//var //$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$【変数】

//$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$【ルーチン】

implementation //############################################################### ■

//$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$【レコード】

//$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$【クラス】

//%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% TDICOMElems0018

//&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&& private

//&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&& protected

//&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&& public

constructor TDICOMElems0018.Create;
begin
     inherited;

     Add( $0000, TKindVR.vrUL, 'Acquisition Group Length' );

     // http://dicom.nema.org/medical/dicom/current/output/html/part06.html#chapter_6
     // 6 Registry of DICOM Data Elements
     Add( $0010, TKindVR.vrLO, 'Contrast/Bolus Agent' );
     Add( $0012, TKindVR.vrSQ, 'Contrast/Bolus Agent Sequence' );
     Add( $0013, TKindVR.vrFL, 'Contrast/Bolus T1 Relaxivity' );
     Add( $0014, TKindVR.vrSQ, 'Contrast/Bolus Administration Route Sequence' );
     Add( $0015, TKindVR.vrCS, 'Body Part Examined' );
     Add( $0020, TKindVR.vrCS, 'Scanning Sequence' );
     Add( $0021, TKindVR.vrCS, 'Sequence Variant' );
     Add( $0022, TKindVR.vrCS, 'Scan Options' );
     Add( $0023, TKindVR.vrCS, 'MR Acquisition Type' );
     Add( $0024, TKindVR.vrSH, 'Sequence Name' );
     Add( $0025, TKindVR.vrCS, 'Angio Flag' );
     Add( $0026, TKindVR.vrSQ, 'Intervention Drug Information Sequence' );
     Add( $0027, TKindVR.vrTM, 'Intervention Drug Stop Time' );
     Add( $0028, TKindVR.vrDS, 'Intervention Drug Dose' );
     Add( $0029, TKindVR.vrSQ, 'Intervention Drug Code Sequence' );
     Add( $002A, TKindVR.vrSQ, 'Additional Drug Sequence' );
     Add( $0030, TKindVR.vrLO, 'Radionuclide' );
     Add( $0031, TKindVR.vrLO, 'Radiopharmaceutical' );
     Add( $0032, TKindVR.vrDS, 'Energy Window Centerline' );
     Add( $0033, TKindVR.vrDS, 'Energy Window Total Width' );
     Add( $0034, TKindVR.vrLO, 'Intervention Drug Name' );
     Add( $0035, TKindVR.vrTM, 'Intervention Drug Start Time' );
     Add( $0036, TKindVR.vrSQ, 'Intervention Sequence' );
     Add( $0037, TKindVR.vrCS, 'Therapy Type' );
     Add( $0038, TKindVR.vrCS, 'Intervention Status' );
     Add( $0039, TKindVR.vrCS, 'Therapy Description' );
     Add( $003A, TKindVR.vrST, 'Intervention Description' );
     Add( $0040, TKindVR.vrIS, 'Cine Rate' );
     Add( $0042, TKindVR.vrCS, 'Initial Cine Run State' );
     Add( $0050, TKindVR.vrDS, 'Slice Thickness' );
     Add( $0060, TKindVR.vrDS, 'KVP' );
     Add( $0061, TKindVR.vrDS, '' );
     Add( $0070, TKindVR.vrIS, 'Counts Accumulated' );
     Add( $0071, TKindVR.vrCS, 'Acquisition Termination Condition' );
     Add( $0072, TKindVR.vrDS, 'Effective Duration' );
     Add( $0073, TKindVR.vrCS, 'Acquisition Start Condition' );
     Add( $0074, TKindVR.vrIS, 'Acquisition Start Condition Data' );
     Add( $0075, TKindVR.vrIS, 'Acquisition Termination Condition Data' );
     Add( $0080, TKindVR.vrDS, 'Repetition Time' );
     Add( $0081, TKindVR.vrDS, 'Echo Time' );
     Add( $0082, TKindVR.vrDS, 'Inversion Time' );
     Add( $0083, TKindVR.vrDS, 'Number of Averages' );
     Add( $0084, TKindVR.vrDS, 'Imaging Frequency' );
     Add( $0085, TKindVR.vrSH, 'Imaged Nucleus' );
     Add( $0086, TKindVR.vrIS, 'Echo Number(s)' );
     Add( $0087, TKindVR.vrDS, 'Magnetic Field Strength' );
     Add( $0088, TKindVR.vrDS, 'Spacing Between Slices' );
     Add( $0089, TKindVR.vrIS, 'Number of Phase Encoding Steps' );
     Add( $0090, TKindVR.vrDS, 'Data Collection Diameter' );
     Add( $0091, TKindVR.vrIS, 'Echo Train Length' );
     Add( $0093, TKindVR.vrDS, 'Percent Sampling' );
     Add( $0094, TKindVR.vrDS, 'Percent Phase Field of View' );
     Add( $0095, TKindVR.vrDS, 'Pixel Bandwidth' );
     Add( $1000, TKindVR.vrLO, 'Device Serial Number' );
     Add( $1002, TKindVR.vrUI, 'Device UID' );
     Add( $1003, TKindVR.vrLO, 'Device ID' );
     Add( $1004, TKindVR.vrLO, 'Plate ID' );
     Add( $1005, TKindVR.vrLO, 'Generator ID' );
     Add( $1006, TKindVR.vrLO, 'Grid ID' );
     Add( $1007, TKindVR.vrLO, 'Cassette ID' );
     Add( $1008, TKindVR.vrLO, 'Gantry ID' );
     Add( $1009, TKindVR.vrUT, 'Unique Device Identifier' );
     Add( $100A, TKindVR.vrSQ, 'UDI Sequence' );
     Add( $1010, TKindVR.vrLO, 'Secondary Capture Device ID' );
     Add( $1011, TKindVR.vrLO, 'Hardcopy Creation Device ID' );
     Add( $1012, TKindVR.vrDA, 'Date of Secondary Capture' );
     Add( $1014, TKindVR.vrTM, 'Time of Secondary Capture' );
     Add( $1016, TKindVR.vrLO, 'Secondary Capture Device Manufacturer' );
     Add( $1017, TKindVR.vrLO, 'Hardcopy Device Manufacturer' );
     Add( $1018, TKindVR.vrLO, 'Secondary Capture Device Manufacturer''s Model Name' );
     Add( $1019, TKindVR.vrLO, 'Secondary Capture Device Software Versions' );
     Add( $101A, TKindVR.vrLO, 'Hardcopy Device Software Version' );
     Add( $101B, TKindVR.vrLO, 'Hardcopy Device Manufacturer''s Model Name' );
     Add( $1020, TKindVR.vrLO, 'Software Version(s)' );
     Add( $1022, TKindVR.vrSH, 'Video Image Format Acquired' );
     Add( $1023, TKindVR.vrLO, 'Digital Image Format Acquired' );
     Add( $1030, TKindVR.vrLO, 'Protocol Name' );
     Add( $1040, TKindVR.vrLO, 'Contrast/Bolus Route' );
     Add( $1041, TKindVR.vrDS, 'Contrast/Bolus Volume' );
     Add( $1042, TKindVR.vrTM, 'Contrast/Bolus Start Time' );
     Add( $1043, TKindVR.vrTM, 'Contrast/Bolus Stop Time' );
     Add( $1044, TKindVR.vrDS, 'Contrast/Bolus Total Dose' );
     Add( $1045, TKindVR.vrIS, 'Syringe Counts' );
     Add( $1046, TKindVR.vrDS, 'Contrast Flow Rate' );
     Add( $1047, TKindVR.vrDS, 'Contrast Flow Duration' );
     Add( $1048, TKindVR.vrCS, 'Contrast/Bolus Ingredient' );
     Add( $1049, TKindVR.vrDS, 'Contrast/Bolus Ingredient Concentration' );
     Add( $1050, TKindVR.vrDS, 'Spatial Resolution' );
     Add( $1060, TKindVR.vrDS, 'Trigger Time' );
     Add( $1061, TKindVR.vrLO, 'Trigger Source or Type' );
     Add( $1062, TKindVR.vrIS, 'Nominal Interval' );
     Add( $1063, TKindVR.vrDS, 'Frame Time' );
     Add( $1064, TKindVR.vrLO, 'Cardiac Framing Type' );
     Add( $1065, TKindVR.vrDS, 'Frame Time Vector' );
     Add( $1066, TKindVR.vrDS, 'Frame Delay' );
     Add( $1067, TKindVR.vrDS, 'Image Trigger Delay' );
     Add( $1068, TKindVR.vrDS, 'Multiplex Group Time Offset' );
     Add( $1069, TKindVR.vrDS, 'Trigger Time Offset' );
     Add( $106A, TKindVR.vrCS, 'Synchronization Trigger' );
     Add( $106C, TKindVR.vrUS, 'Synchronization Channel' );
     Add( $106E, TKindVR.vrUL, 'Trigger Sample Position' );
     Add( $1070, TKindVR.vrLO, 'Radiopharmaceutical Route' );
     Add( $1071, TKindVR.vrDS, 'Radiopharmaceutical Volume' );
     Add( $1072, TKindVR.vrTM, 'Radiopharmaceutical Start Time' );
     Add( $1073, TKindVR.vrTM, 'Radiopharmaceutical Stop Time' );
     Add( $1074, TKindVR.vrDS, 'Radionuclide Total Dose' );
     Add( $1075, TKindVR.vrDS, 'Radionuclide Half Life' );
     Add( $1076, TKindVR.vrDS, 'Radionuclide Positron Fraction' );
     Add( $1077, TKindVR.vrDS, 'Radiopharmaceutical Specific Activity' );
     Add( $1078, TKindVR.vrDT, 'Radiopharmaceutical Start DateTime' );
     Add( $1079, TKindVR.vrDT, 'Radiopharmaceutical Stop DateTime' );
     Add( $1080, TKindVR.vrCS, 'Beat Rejection Flag' );
     Add( $1081, TKindVR.vrIS, 'Low R-R Value' );
     Add( $1082, TKindVR.vrIS, 'High R-R Value' );
     Add( $1083, TKindVR.vrIS, 'Intervals Acquired' );
     Add( $1084, TKindVR.vrIS, 'Intervals Rejected' );
     Add( $1085, TKindVR.vrLO, 'PVC Rejection' );
     Add( $1086, TKindVR.vrIS, 'Skip Beats' );
     Add( $1088, TKindVR.vrIS, 'Heart Rate' );
     Add( $1090, TKindVR.vrIS, 'Cardiac Number of Images' );
     Add( $1094, TKindVR.vrIS, 'Trigger Window' );
     Add( $1100, TKindVR.vrDS, 'Reconstruction Diameter' );
     Add( $1110, TKindVR.vrDS, 'Distance Source to Detector' );
     Add( $1111, TKindVR.vrDS, 'Distance Source to Patient' );
     Add( $1114, TKindVR.vrDS, 'Estimated Radiographic Magnification Factor' );
     Add( $1120, TKindVR.vrDS, 'Gantry/Detector Tilt' );
     Add( $1121, TKindVR.vrDS, 'Gantry/Detector Slew' );
     Add( $1130, TKindVR.vrDS, 'Table Height' );
     Add( $1131, TKindVR.vrDS, 'Table Traverse' );
     Add( $1134, TKindVR.vrCS, 'Table Motion' );
     Add( $1135, TKindVR.vrDS, 'Table Vertical Increment' );
     Add( $1136, TKindVR.vrDS, 'Table Lateral Increment' );
     Add( $1137, TKindVR.vrDS, 'Table Longitudinal Increment' );
     Add( $1138, TKindVR.vrDS, 'Table Angle' );
     Add( $113A, TKindVR.vrCS, 'Table Type' );
     Add( $1140, TKindVR.vrCS, 'Rotation Direction' );
     Add( $1141, TKindVR.vrDS, 'Angular Position' );
     Add( $1142, TKindVR.vrDS, 'Radial Position' );
     Add( $1143, TKindVR.vrDS, 'Scan Arc' );
     Add( $1144, TKindVR.vrDS, 'Angular Step' );
     Add( $1145, TKindVR.vrDS, 'Center of Rotation Offset' );
     Add( $1146, TKindVR.vrDS, 'Rotation Offset' );
     Add( $1147, TKindVR.vrCS, 'Field of View Shape' );
     Add( $1149, TKindVR.vrIS, 'Field of View Dimension(s)' );
     Add( $1150, TKindVR.vrIS, 'Exposure Time' );
     Add( $1151, TKindVR.vrIS, 'X-Ray Tube Current' );
     Add( $1152, TKindVR.vrIS, 'Exposure' );
     Add( $1153, TKindVR.vrIS, 'Exposure in µAs' );
     Add( $1154, TKindVR.vrDS, 'Average Pulse Width' );
     Add( $1155, TKindVR.vrCS, 'Radiation Setting' );
     Add( $1156, TKindVR.vrCS, 'Rectification Type' );
     Add( $115A, TKindVR.vrCS, 'Radiation Mode' );
     Add( $115E, TKindVR.vrDS, 'Image and Fluoroscopy Area Dose Product' );
     Add( $1160, TKindVR.vrSH, 'Filter Type' );
     Add( $1161, TKindVR.vrLO, 'Type of Filters' );
     Add( $1162, TKindVR.vrDS, 'Intensifier Size' );
     Add( $1164, TKindVR.vrDS, 'Imager Pixel Spacing' );
     Add( $1166, TKindVR.vrCS, 'Grid' );
     Add( $1170, TKindVR.vrIS, 'Generator Power' );
     Add( $1180, TKindVR.vrSH, 'Collimator/grid Name' );
     Add( $1181, TKindVR.vrCS, 'Collimator Type' );
     Add( $1182, TKindVR.vrIS, 'Focal Distance' );
     Add( $1183, TKindVR.vrDS, 'X Focus Center' );
     Add( $1184, TKindVR.vrDS, 'Y Focus Center' );
     Add( $1190, TKindVR.vrDS, 'Focal Spot(s)' );
     Add( $1191, TKindVR.vrCS, 'Anode Target Material' );
     Add( $11A0, TKindVR.vrDS, 'Body Part Thickness' );
     Add( $11A2, TKindVR.vrDS, 'Compression Force' );
     Add( $11A4, TKindVR.vrLO, 'Paddle Description' );
     Add( $1200, TKindVR.vrDA, 'Date of Last Calibration' );
     Add( $1201, TKindVR.vrTM, 'Time of Last Calibration' );
     Add( $1202, TKindVR.vrDT, 'DateTime of Last Calibration' );
     Add( $1210, TKindVR.vrSH, 'Convolution Kernel' );
     Add( $1240, TKindVR.vrIS, 'Upper/Lower Pixel Values' );
     Add( $1242, TKindVR.vrIS, 'Actual Frame Duration' );
     Add( $1243, TKindVR.vrIS, 'Count Rate' );
     Add( $1244, TKindVR.vrUS, 'Preferred Playback Sequencing' );
     Add( $1250, TKindVR.vrSH, 'Receive Coil Name' );
     Add( $1251, TKindVR.vrSH, 'Transmit Coil Name' );
     Add( $1260, TKindVR.vrSH, 'Plate Type' );
     Add( $1261, TKindVR.vrLO, 'Phosphor Type' );
     Add( $1271, TKindVR.vrFD, 'Water Equivalent Diameter' );
     Add( $1272, TKindVR.vrSQ, 'Water Equivalent Diameter Calculation Method Code Sequence' );
     Add( $1300, TKindVR.vrDS, 'Scan Velocity' );
     Add( $1301, TKindVR.vrCS, 'Whole Body Technique' );
     Add( $1302, TKindVR.vrIS, 'Scan Length' );
     Add( $1310, TKindVR.vrUS, 'Acquisition Matrix' );
     Add( $1312, TKindVR.vrCS, 'In-plane Phase Encoding Direction' );
     Add( $1314, TKindVR.vrDS, 'Flip Angle' );
     Add( $1315, TKindVR.vrCS, 'Variable Flip Angle Flag' );
     Add( $1316, TKindVR.vrDS, 'SAR' );
     Add( $1318, TKindVR.vrDS, 'dB/dt' );
     Add( $1320, TKindVR.vrFL, 'B1rms' );
     Add( $1400, TKindVR.vrLO, 'Acquisition Device Processing Description' );
     Add( $1401, TKindVR.vrLO, 'Acquisition Device Processing Code' );
     Add( $1402, TKindVR.vrCS, 'Cassette Orientation' );
     Add( $1403, TKindVR.vrCS, 'Cassette Size' );
     Add( $1404, TKindVR.vrUS, 'Exposures on Plate' );
     Add( $1405, TKindVR.vrIS, 'Relative X-Ray Exposure' );
     Add( $1411, TKindVR.vrDS, 'Exposure Index' );
     Add( $1412, TKindVR.vrDS, 'Target Exposure Index' );
     Add( $1413, TKindVR.vrDS, 'Deviation Index' );
     Add( $1450, TKindVR.vrDS, 'Column Angulation' );
     Add( $1460, TKindVR.vrDS, 'Tomo Layer Height' );
     Add( $1470, TKindVR.vrDS, 'Tomo Angle' );
     Add( $1480, TKindVR.vrDS, 'Tomo Time' );
     Add( $1490, TKindVR.vrCS, 'Tomo Type' );
     Add( $1491, TKindVR.vrCS, 'Tomo Class' );
     Add( $1495, TKindVR.vrIS, 'Number of Tomosynthesis Source Images' );
     Add( $1500, TKindVR.vrCS, 'Positioner Motion' );
     Add( $1508, TKindVR.vrCS, 'Positioner Type' );
     Add( $1510, TKindVR.vrDS, 'Positioner Primary Angle' );
     Add( $1511, TKindVR.vrDS, 'Positioner Secondary Angle' );
     Add( $1520, TKindVR.vrDS, 'Positioner Primary Angle Increment' );
     Add( $1521, TKindVR.vrDS, 'Positioner Secondary Angle Increment' );
     Add( $1530, TKindVR.vrDS, 'Detector Primary Angle' );
     Add( $1531, TKindVR.vrDS, 'Detector Secondary Angle' );
     Add( $1600, TKindVR.vrCS, 'Shutter Shape' );
     Add( $1602, TKindVR.vrIS, 'Shutter Left Vertical Edge' );
     Add( $1604, TKindVR.vrIS, 'Shutter Right Vertical Edge' );
     Add( $1606, TKindVR.vrIS, 'Shutter Upper Horizontal Edge' );
     Add( $1608, TKindVR.vrIS, 'Shutter Lower Horizontal Edge' );
     Add( $1610, TKindVR.vrIS, 'Center of Circular Shutter' );
     Add( $1612, TKindVR.vrIS, 'Radius of Circular Shutter' );
     Add( $1620, TKindVR.vrIS, 'Vertices of the Polygonal Shutter' );
     Add( $1622, TKindVR.vrUS, 'Shutter Presentation Value' );
     Add( $1623, TKindVR.vrUS, 'Shutter Overlay Group' );
     Add( $1624, TKindVR.vrUS, 'Shutter Presentation Color CIELab Value' );
     Add( $1700, TKindVR.vrCS, 'Collimator Shape' );
     Add( $1702, TKindVR.vrIS, 'Collimator Left Vertical Edge' );
     Add( $1704, TKindVR.vrIS, 'Collimator Right Vertical Edge' );
     Add( $1706, TKindVR.vrIS, 'Collimator Upper Horizontal Edge' );
     Add( $1708, TKindVR.vrIS, 'Collimator Lower Horizontal Edge' );
     Add( $1710, TKindVR.vrIS, 'Center of Circular Collimator' );
     Add( $1712, TKindVR.vrIS, 'Radius of Circular Collimator' );
     Add( $1720, TKindVR.vrIS, 'Vertices of the Polygonal Collimator' );
     Add( $1800, TKindVR.vrCS, 'Acquisition Time Synchronized' );
     Add( $1801, TKindVR.vrSH, 'Time Source' );
     Add( $1802, TKindVR.vrCS, 'Time Distribution Protocol' );
     Add( $1803, TKindVR.vrLO, 'NTP Source Address' );
     Add( $2001, TKindVR.vrIS, 'Page Number Vector' );
     Add( $2002, TKindVR.vrSH, 'Frame Label Vector' );
     Add( $2003, TKindVR.vrDS, 'Frame Primary Angle Vector' );
     Add( $2004, TKindVR.vrDS, 'Frame Secondary Angle Vector' );
     Add( $2005, TKindVR.vrDS, 'Slice Location Vector' );
     Add( $2006, TKindVR.vrSH, 'Display Window Label Vector' );
     Add( $2010, TKindVR.vrDS, 'Nominal Scanned Pixel Spacing' );
     Add( $2020, TKindVR.vrCS, 'Digitizing Device Transport Direction' );
     Add( $2030, TKindVR.vrDS, 'Rotation of Scanned Film' );
     Add( $2041, TKindVR.vrSQ, 'Biopsy Target Sequence' );
     Add( $2042, TKindVR.vrUI, 'Target UID' );
     Add( $2043, TKindVR.vrFL, 'Localizing Cursor Position' );
     Add( $2044, TKindVR.vrFL, 'Calculated Target Position' );
     Add( $2045, TKindVR.vrSH, 'Target Label' );
     Add( $2046, TKindVR.vrFL, 'Displayed Z Value' );
     Add( $3100, TKindVR.vrCS, 'IVUS Acquisition' );
     Add( $3101, TKindVR.vrDS, 'IVUS Pullback Rate' );
     Add( $3102, TKindVR.vrDS, 'IVUS Gated Rate' );
     Add( $3103, TKindVR.vrIS, 'IVUS Pullback Start Frame Number' );
     Add( $3104, TKindVR.vrIS, 'IVUS Pullback Stop Frame Number' );
     Add( $3105, TKindVR.vrIS, 'Lesion Number' );
     Add( $4000, TKindVR.vrLT, 'Acquisition Comments' );
     Add( $5000, TKindVR.vrSH, 'Output Power' );
     Add( $5010, TKindVR.vrLO, 'Transducer Data' );
     Add( $5012, TKindVR.vrDS, 'Focus Depth' );
     Add( $5020, TKindVR.vrLO, 'Processing Function' );
     Add( $5021, TKindVR.vrLO, 'Postprocessing Function' );
     Add( $5022, TKindVR.vrDS, 'Mechanical Index' );
     Add( $5024, TKindVR.vrDS, 'Bone Thermal Index' );
     Add( $5026, TKindVR.vrDS, 'Cranial Thermal Index' );
     Add( $5027, TKindVR.vrDS, 'Soft Tissue Thermal Index' );
     Add( $5028, TKindVR.vrDS, 'Soft Tissue-focus Thermal Index' );
     Add( $5029, TKindVR.vrDS, 'Soft Tissue-surface Thermal Index' );
     Add( $5030, TKindVR.vrDS, 'Dynamic Range' );
     Add( $5040, TKindVR.vrDS, 'Total Gain' );
     Add( $5050, TKindVR.vrIS, 'Depth of Scan Field' );
     Add( $5100, TKindVR.vrCS, 'Patient Position' );
     Add( $5101, TKindVR.vrCS, 'View Position' );
     Add( $5104, TKindVR.vrSQ, 'Projection Eponymous Name Code Sequence' );
     Add( $5210, TKindVR.vrDS, 'Image Transformation Matrix' );
     Add( $5212, TKindVR.vrDS, 'Image Translation Vector' );
     Add( $6000, TKindVR.vrDS, 'Sensitivity' );
     Add( $6011, TKindVR.vrSQ, 'Sequence of Ultrasound Regions' );
     Add( $6012, TKindVR.vrUS, 'Region Spatial Format' );
     Add( $6014, TKindVR.vrUS, 'Region Data Type' );
     Add( $6016, TKindVR.vrUL, 'Region Flags' );
     Add( $6018, TKindVR.vrUL, 'Region Location Min X0' );
     Add( $601A, TKindVR.vrUL, 'Region Location Min Y0' );
     Add( $601C, TKindVR.vrUL, 'Region Location Max X1' );
     Add( $601E, TKindVR.vrUL, 'Region Location Max Y1' );
     Add( $6020, TKindVR.vrSL, 'Reference Pixel X0' );
     Add( $6022, TKindVR.vrSL, 'Reference Pixel Y0' );
     Add( $6024, TKindVR.vrUS, 'Physical Units X Direction' );
     Add( $6026, TKindVR.vrUS, 'Physical Units Y Direction' );
     Add( $6028, TKindVR.vrFD, 'Reference Pixel Physical Value X' );
     Add( $602A, TKindVR.vrFD, 'Reference Pixel Physical Value Y' );
     Add( $602C, TKindVR.vrFD, 'Physical Delta X' );
     Add( $602E, TKindVR.vrFD, 'Physical Delta Y' );
     Add( $6030, TKindVR.vrUL, 'Transducer Frequency' );
     Add( $6031, TKindVR.vrCS, 'Transducer Type' );
     Add( $6032, TKindVR.vrUL, 'Pulse Repetition Frequency' );
     Add( $6034, TKindVR.vrFD, 'Doppler Correction Angle' );
     Add( $6036, TKindVR.vrFD, 'Steering Angle' );
     Add( $6038, TKindVR.vrUL, 'Doppler Sample Volume X Position (Retired)' );
     Add( $6039, TKindVR.vrSL, 'Doppler Sample Volume X Position' );
     Add( $603A, TKindVR.vrUL, 'Doppler Sample Volume Y Position (Retired)' );
     Add( $603B, TKindVR.vrSL, 'Doppler Sample Volume Y Position' );
     Add( $603C, TKindVR.vrUL, 'TM-Line Position X0 (Retired)' );
     Add( $603D, TKindVR.vrSL, 'TM-Line Position X0' );
     Add( $603E, TKindVR.vrUL, 'TM-Line Position Y0 (Retired)' );
     Add( $603F, TKindVR.vrSL, 'TM-Line Position Y0' );
     Add( $6040, TKindVR.vrUL, 'TM-Line Position X1 (Retired)' );
     Add( $6041, TKindVR.vrSL, 'TM-Line Position X1' );
     Add( $6042, TKindVR.vrUL, 'TM-Line Position Y1 (Retired)' );
     Add( $6043, TKindVR.vrSL, 'TM-Line Position Y1' );
     Add( $6044, TKindVR.vrUS, 'Pixel Component Organization' );
     Add( $6046, TKindVR.vrUL, 'Pixel Component Mask' );
     Add( $6048, TKindVR.vrUL, 'Pixel Component Range Start' );
     Add( $604A, TKindVR.vrUL, 'Pixel Component Range Stop' );
     Add( $604C, TKindVR.vrUS, 'Pixel Component Physical Units' );
     Add( $604E, TKindVR.vrUS, 'Pixel Component Data Type' );
     Add( $6050, TKindVR.vrUL, 'Number of Table Break Points' );
     Add( $6052, TKindVR.vrUL, 'Table of X Break Points' );
     Add( $6054, TKindVR.vrFD, 'Table of Y Break Points' );
     Add( $6056, TKindVR.vrUL, 'Number of Table Entries' );
     Add( $6058, TKindVR.vrUL, 'Table of Pixel Values' );
     Add( $605A, TKindVR.vrFL, 'Table of Parameter Values' );
     Add( $6060, TKindVR.vrFL, 'R Wave Time Vector' );
     Add( $7000, TKindVR.vrCS, 'Detector Conditions Nominal Flag' );
     Add( $7001, TKindVR.vrDS, 'Detector Temperature' );
     Add( $7004, TKindVR.vrCS, 'Detector Type' );
     Add( $7005, TKindVR.vrCS, 'Detector Configuration' );
     Add( $7006, TKindVR.vrLT, 'Detector Description' );
     Add( $7008, TKindVR.vrLT, 'Detector Mode' );
     Add( $700A, TKindVR.vrSH, 'Detector ID' );
     Add( $700C, TKindVR.vrDA, 'Date of Last Detector Calibration' );
     Add( $700E, TKindVR.vrTM, 'Time of Last Detector Calibration' );
     Add( $7010, TKindVR.vrIS, 'Exposures on Detector Since Last Calibration' );
     Add( $7011, TKindVR.vrIS, 'Exposures on Detector Since Manufactured' );
     Add( $7012, TKindVR.vrDS, 'Detector Time Since Last Exposure' );
     Add( $7014, TKindVR.vrDS, 'Detector Active Time' );
     Add( $7016, TKindVR.vrDS, 'Detector Activation Offset From Exposure' );
     Add( $701A, TKindVR.vrDS, 'Detector Binning' );
     Add( $7020, TKindVR.vrDS, 'Detector Element Physical Size' );
     Add( $7022, TKindVR.vrDS, 'Detector Element Spacing' );
     Add( $7024, TKindVR.vrCS, 'Detector Active Shape' );
     Add( $7026, TKindVR.vrDS, 'Detector Active Dimension(s)' );
     Add( $7028, TKindVR.vrDS, 'Detector Active Origin' );
     Add( $702A, TKindVR.vrLO, 'Detector Manufacturer Name' );
     Add( $702B, TKindVR.vrLO, 'Detector Manufacturer''s Model Name' );
     Add( $7030, TKindVR.vrDS, 'Field of View Origin' );
     Add( $7032, TKindVR.vrDS, 'Field of View Rotation' );
     Add( $7034, TKindVR.vrCS, 'Field of View Horizontal Flip' );
     Add( $7036, TKindVR.vrFL, 'Pixel Data Area Origin Relative To FOV' );
     Add( $7038, TKindVR.vrFL, 'Pixel Data Area Rotation Angle Relative To FOV' );
     Add( $7040, TKindVR.vrLT, 'Grid Absorbing Material' );
     Add( $7041, TKindVR.vrLT, 'Grid Spacing Material' );
     Add( $7042, TKindVR.vrDS, 'Grid Thickness' );
     Add( $7044, TKindVR.vrDS, 'Grid Pitch' );
     Add( $7046, TKindVR.vrIS, 'Grid Aspect Ratio' );
     Add( $7048, TKindVR.vrDS, 'Grid Period' );
     Add( $704C, TKindVR.vrDS, 'Grid Focal Distance' );
     Add( $7050, TKindVR.vrCS, 'Filter Material' );
     Add( $7052, TKindVR.vrDS, 'Filter Thickness Minimum' );
     Add( $7054, TKindVR.vrDS, 'Filter Thickness Maximum' );
     Add( $7056, TKindVR.vrFL, 'Filter Beam Path Length Minimum' );
     Add( $7058, TKindVR.vrFL, 'Filter Beam Path Length Maximum' );
     Add( $7060, TKindVR.vrCS, 'Exposure Control Mode' );
     Add( $7062, TKindVR.vrLT, 'Exposure Control Mode Description' );
     Add( $7064, TKindVR.vrCS, 'Exposure Status' );
     Add( $7065, TKindVR.vrDS, 'Phototimer Setting' );
     Add( $8150, TKindVR.vrDS, 'Exposure Time in µS' );
     Add( $8151, TKindVR.vrDS, 'X-Ray Tube Current in µA' );
     Add( $9004, TKindVR.vrCS, 'Content Qualification' );
     Add( $9005, TKindVR.vrSH, 'Pulse Sequence Name' );
     Add( $9006, TKindVR.vrSQ, 'MR Imaging Modifier Sequence' );
     Add( $9008, TKindVR.vrCS, 'Echo Pulse Sequence' );
     Add( $9009, TKindVR.vrCS, 'Inversion Recovery' );
     Add( $9010, TKindVR.vrCS, 'Flow Compensation' );
     Add( $9011, TKindVR.vrCS, 'Multiple Spin Echo' );
     Add( $9012, TKindVR.vrCS, 'Multi-planar Excitation' );
     Add( $9014, TKindVR.vrCS, 'Phase Contrast' );
     Add( $9015, TKindVR.vrCS, 'Time of Flight Contrast' );
     Add( $9016, TKindVR.vrCS, 'Spoiling' );
     Add( $9017, TKindVR.vrCS, 'Steady State Pulse Sequence' );
     Add( $9018, TKindVR.vrCS, 'Echo Planar Pulse Sequence' );
     Add( $9019, TKindVR.vrFD, 'Tag Angle First Axis' );
     Add( $9020, TKindVR.vrCS, 'Magnetization Transfer' );
     Add( $9021, TKindVR.vrCS, 'T2 Preparation' );
     Add( $9022, TKindVR.vrCS, 'Blood Signal Nulling' );
     Add( $9024, TKindVR.vrCS, 'Saturation Recovery' );
     Add( $9025, TKindVR.vrCS, 'Spectrally Selected Suppression' );
     Add( $9026, TKindVR.vrCS, 'Spectrally Selected Excitation' );
     Add( $9027, TKindVR.vrCS, 'Spatial Pre-saturation' );
     Add( $9028, TKindVR.vrCS, 'Tagging' );
     Add( $9029, TKindVR.vrCS, 'Oversampling Phase' );
     Add( $9030, TKindVR.vrFD, 'Tag Spacing First Dimension' );
     Add( $9032, TKindVR.vrCS, 'Geometry of k-Space Traversal' );
     Add( $9033, TKindVR.vrCS, 'Segmented k-Space Traversal' );
     Add( $9034, TKindVR.vrCS, 'Rectilinear Phase Encode Reordering' );
     Add( $9035, TKindVR.vrFD, 'Tag Thickness' );
     Add( $9036, TKindVR.vrCS, 'Partial Fourier Direction' );
     Add( $9037, TKindVR.vrCS, 'Cardiac Synchronization Technique' );
     Add( $9041, TKindVR.vrLO, 'Receive Coil Manufacturer Name' );
     Add( $9042, TKindVR.vrSQ, 'MR Receive Coil Sequence' );
     Add( $9043, TKindVR.vrCS, 'Receive Coil Type' );
     Add( $9044, TKindVR.vrCS, 'Quadrature Receive Coil' );
     Add( $9045, TKindVR.vrSQ, 'Multi-Coil Definition Sequence' );
     Add( $9046, TKindVR.vrLO, 'Multi-Coil Configuration' );
     Add( $9047, TKindVR.vrSH, 'Multi-Coil Element Name' );
     Add( $9048, TKindVR.vrCS, 'Multi-Coil Element Used' );
     Add( $9049, TKindVR.vrSQ, 'MR Transmit Coil Sequence' );
     Add( $9050, TKindVR.vrLO, 'Transmit Coil Manufacturer Name' );
     Add( $9051, TKindVR.vrCS, 'Transmit Coil Type' );
     Add( $9052, TKindVR.vrFD, 'Spectral Width' );
     Add( $9053, TKindVR.vrFD, 'Chemical Shift Reference' );
     Add( $9054, TKindVR.vrCS, 'Volume Localization Technique' );
     Add( $9058, TKindVR.vrUS, 'MR Acquisition Frequency Encoding Steps' );
     Add( $9059, TKindVR.vrCS, 'De-coupling' );
     Add( $9060, TKindVR.vrCS, 'De-coupled Nucleus' );
     Add( $9061, TKindVR.vrFD, 'De-coupling Frequency' );
     Add( $9062, TKindVR.vrCS, 'De-coupling Method' );
     Add( $9063, TKindVR.vrFD, 'De-coupling Chemical Shift Reference' );
     Add( $9064, TKindVR.vrCS, 'k-space Filtering' );
     Add( $9065, TKindVR.vrCS, 'Time Domain Filtering' );
     Add( $9066, TKindVR.vrUS, 'Number of Zero Fills' );
     Add( $9067, TKindVR.vrCS, 'Baseline Correction' );
     Add( $9069, TKindVR.vrFD, 'Parallel Reduction Factor In-plane' );
     Add( $9070, TKindVR.vrFD, 'Cardiac R-R Interval Specified' );
     Add( $9073, TKindVR.vrFD, 'Acquisition Duration' );
     Add( $9074, TKindVR.vrDT, 'Frame Acquisition DateTime' );
     Add( $9075, TKindVR.vrCS, 'Diffusion Directionality' );
     Add( $9076, TKindVR.vrSQ, 'Diffusion Gradient Direction Sequence' );
     Add( $9077, TKindVR.vrCS, 'Parallel Acquisition' );
     Add( $9078, TKindVR.vrCS, 'Parallel Acquisition Technique' );
     Add( $9079, TKindVR.vrFD, 'Inversion Times' );
     Add( $9080, TKindVR.vrST, 'Metabolite Map Description' );
     Add( $9081, TKindVR.vrCS, 'Partial Fourier' );
     Add( $9082, TKindVR.vrFD, 'Effective Echo Time' );
     Add( $9083, TKindVR.vrSQ, 'Metabolite Map Code Sequence' );
     Add( $9084, TKindVR.vrSQ, 'Chemical Shift Sequence' );
     Add( $9085, TKindVR.vrCS, 'Cardiac Signal Source' );
     Add( $9087, TKindVR.vrFD, 'Diffusion b-value' );
     Add( $9089, TKindVR.vrFD, 'Diffusion Gradient Orientation' );
     Add( $9090, TKindVR.vrFD, 'Velocity Encoding Direction' );
     Add( $9091, TKindVR.vrFD, 'Velocity Encoding Minimum Value' );
     Add( $9092, TKindVR.vrSQ, 'Velocity Encoding Acquisition Sequence' );
     Add( $9093, TKindVR.vrUS, 'Number of k-Space Trajectories' );
     Add( $9094, TKindVR.vrCS, 'Coverage of k-Space' );
     Add( $9095, TKindVR.vrUL, 'Spectroscopy Acquisition Phase Rows' );
     Add( $9096, TKindVR.vrFD, 'Parallel Reduction Factor In-plane (Retired)' );
     Add( $9098, TKindVR.vrFD, 'Transmitter Frequency' );
     Add( $9100, TKindVR.vrCS, 'Resonant Nucleus' );
     Add( $9101, TKindVR.vrCS, 'Frequency Correction' );
     Add( $9103, TKindVR.vrSQ, 'MR Spectroscopy FOV/Geometry Sequence' );
     Add( $9104, TKindVR.vrFD, 'Slab Thickness' );
     Add( $9105, TKindVR.vrFD, 'Slab Orientation' );
     Add( $9106, TKindVR.vrFD, 'Mid Slab Position' );
     Add( $9107, TKindVR.vrSQ, 'MR Spatial Saturation Sequence' );
     Add( $9112, TKindVR.vrSQ, 'MR Timing and Related Parameters Sequence' );
     Add( $9114, TKindVR.vrSQ, 'MR Echo Sequence' );
     Add( $9115, TKindVR.vrSQ, 'MR Modifier Sequence' );
     Add( $9117, TKindVR.vrSQ, 'MR Diffusion Sequence' );
     Add( $9118, TKindVR.vrSQ, 'Cardiac Synchronization Sequence' );
     Add( $9119, TKindVR.vrSQ, 'MR Averages Sequence' );
     Add( $9125, TKindVR.vrSQ, 'MR FOV/Geometry Sequence' );
     Add( $9126, TKindVR.vrSQ, 'Volume Localization Sequence' );
     Add( $9127, TKindVR.vrUL, 'Spectroscopy Acquisition Data Columns' );
     Add( $9147, TKindVR.vrCS, 'Diffusion Anisotropy Type' );
     Add( $9151, TKindVR.vrDT, 'Frame Reference DateTime' );
     Add( $9152, TKindVR.vrSQ, 'MR Metabolite Map Sequence' );
     Add( $9155, TKindVR.vrFD, 'Parallel Reduction Factor out-of-plane' );
     Add( $9159, TKindVR.vrUL, 'Spectroscopy Acquisition Out-of-plane Phase Steps' );
     Add( $9166, TKindVR.vrCS, 'Bulk Motion Status' );
     Add( $9168, TKindVR.vrFD, 'Parallel Reduction Factor Second In-plane' );
     Add( $9169, TKindVR.vrCS, 'Cardiac Beat Rejection Technique' );
     Add( $9170, TKindVR.vrCS, 'Respiratory Motion Compensation Technique' );
     Add( $9171, TKindVR.vrCS, 'Respiratory Signal Source' );
     Add( $9172, TKindVR.vrCS, 'Bulk Motion Compensation Technique' );
     Add( $9173, TKindVR.vrCS, 'Bulk Motion Signal Source' );
     Add( $9174, TKindVR.vrCS, 'Applicable Safety Standard Agency' );
     Add( $9175, TKindVR.vrLO, 'Applicable Safety Standard Description' );
     Add( $9176, TKindVR.vrSQ, 'Operating Mode Sequence' );
     Add( $9177, TKindVR.vrCS, 'Operating Mode Type' );
     Add( $9178, TKindVR.vrCS, 'Operating Mode' );
     Add( $9179, TKindVR.vrCS, 'Specific Absorption Rate Definition' );
     Add( $9180, TKindVR.vrCS, 'Gradient Output Type' );
     Add( $9181, TKindVR.vrFD, 'Specific Absorption Rate Value' );
     Add( $9182, TKindVR.vrFD, 'Gradient Output' );
     Add( $9183, TKindVR.vrCS, 'Flow Compensation Direction' );
     Add( $9184, TKindVR.vrFD, 'Tagging Delay' );
     Add( $9185, TKindVR.vrST, 'Respiratory Motion Compensation Technique Description' );
     Add( $9186, TKindVR.vrSH, 'Respiratory Signal Source ID' );
     Add( $9195, TKindVR.vrFD, 'Chemical Shift Minimum Integration Limit in Hz' );
     Add( $9196, TKindVR.vrFD, 'Chemical Shift Maximum Integration Limit in Hz' );
     Add( $9197, TKindVR.vrSQ, 'MR Velocity Encoding Sequence' );
     Add( $9198, TKindVR.vrCS, 'First Order Phase Correction' );
     Add( $9199, TKindVR.vrCS, 'Water Referenced Phase Correction' );
     Add( $9200, TKindVR.vrCS, 'MR Spectroscopy Acquisition Type' );
     Add( $9214, TKindVR.vrCS, 'Respiratory Cycle Position' );
     Add( $9217, TKindVR.vrFD, 'Velocity Encoding Maximum Value' );
     Add( $9218, TKindVR.vrFD, 'Tag Spacing Second Dimension' );
     Add( $9219, TKindVR.vrSS, 'Tag Angle Second Axis' );
     Add( $9220, TKindVR.vrFD, 'Frame Acquisition Duration' );
     Add( $9226, TKindVR.vrSQ, 'MR Image Frame Type Sequence' );
     Add( $9227, TKindVR.vrSQ, 'MR Spectroscopy Frame Type Sequence' );
     Add( $9231, TKindVR.vrUS, 'MR Acquisition Phase Encoding Steps in-plane' );
     Add( $9232, TKindVR.vrUS, 'MR Acquisition Phase Encoding Steps out-of-plane' );
     Add( $9234, TKindVR.vrUL, 'Spectroscopy Acquisition Phase Columns' );
     Add( $9236, TKindVR.vrCS, 'Cardiac Cycle Position' );
     Add( $9239, TKindVR.vrSQ, 'Specific Absorption Rate Sequence' );
     Add( $9240, TKindVR.vrUS, 'RF Echo Train Length' );
     Add( $9241, TKindVR.vrUS, 'Gradient Echo Train Length' );
     Add( $9250, TKindVR.vrCS, 'Arterial Spin Labeling Contrast' );
     Add( $9251, TKindVR.vrSQ, 'MR Arterial Spin Labeling Sequence' );
     Add( $9252, TKindVR.vrLO, 'ASL Technique Description' );
     Add( $9253, TKindVR.vrUS, 'ASL Slab Number' );
     Add( $9254, TKindVR.vrFD, 'ASL Slab Thickness' );
     Add( $9255, TKindVR.vrFD, 'ASL Slab Orientation' );
     Add( $9256, TKindVR.vrFD, 'ASL Mid Slab Position' );
     Add( $9257, TKindVR.vrCS, 'ASL Context' );
     Add( $9258, TKindVR.vrUL, 'ASL Pulse Train Duration' );
     Add( $9259, TKindVR.vrCS, 'ASL Crusher Flag' );
     Add( $925A, TKindVR.vrFD, 'ASL Crusher Flow Limit' );
     Add( $925B, TKindVR.vrLO, 'ASL Crusher Description' );
     Add( $925C, TKindVR.vrCS, 'ASL Bolus Cut-off Flag' );
     Add( $925D, TKindVR.vrSQ, 'ASL Bolus Cut-off Timing Sequence' );
     Add( $925E, TKindVR.vrLO, 'ASL Bolus Cut-off Technique' );
     Add( $925F, TKindVR.vrUL, 'ASL Bolus Cut-off Delay Time' );
     Add( $9260, TKindVR.vrSQ, 'ASL Slab Sequence' );
     Add( $9295, TKindVR.vrFD, 'Chemical Shift Minimum Integration Limit in ppm' );
     Add( $9296, TKindVR.vrFD, 'Chemical Shift Maximum Integration Limit in ppm' );
     Add( $9297, TKindVR.vrCS, 'Water Reference Acquisition' );
     Add( $9298, TKindVR.vrIS, 'Echo Peak Position' );
     Add( $9301, TKindVR.vrSQ, 'CT Acquisition Type Sequence' );
     Add( $9302, TKindVR.vrCS, 'Acquisition Type' );
     Add( $9303, TKindVR.vrFD, 'Tube Angle' );
     Add( $9304, TKindVR.vrSQ, 'CT Acquisition Details Sequence' );
     Add( $9305, TKindVR.vrFD, 'Revolution Time' );
     Add( $9306, TKindVR.vrFD, 'Single Collimation Width' );
     Add( $9307, TKindVR.vrFD, 'Total Collimation Width' );
     Add( $9308, TKindVR.vrSQ, 'CT Table Dynamics Sequence' );
     Add( $9309, TKindVR.vrFD, 'Table Speed' );
     Add( $9310, TKindVR.vrFD, 'Table Feed per Rotation' );
     Add( $9311, TKindVR.vrFD, 'Spiral Pitch Factor' );
     Add( $9312, TKindVR.vrSQ, 'CT Geometry Sequence' );
     Add( $9313, TKindVR.vrFD, 'Data Collection Center (Patient)' );
     Add( $9314, TKindVR.vrSQ, 'CT Reconstruction Sequence' );
     Add( $9315, TKindVR.vrCS, 'Reconstruction Algorithm' );
     Add( $9316, TKindVR.vrCS, 'Convolution Kernel Group' );
     Add( $9317, TKindVR.vrFD, 'Reconstruction Field of View' );
     Add( $9318, TKindVR.vrFD, 'Reconstruction Target Center (Patient)' );
     Add( $9319, TKindVR.vrFD, 'Reconstruction Angle' );
     Add( $9320, TKindVR.vrSH, 'Image Filter' );
     Add( $9321, TKindVR.vrSQ, 'CT Exposure Sequence' );
     Add( $9322, TKindVR.vrFD, 'Reconstruction Pixel Spacing' );
     Add( $9323, TKindVR.vrCS, 'Exposure Modulation Type' );
     Add( $9324, TKindVR.vrFD, 'Estimated Dose Saving' );
     Add( $9325, TKindVR.vrSQ, 'CT X-Ray Details Sequence' );
     Add( $9326, TKindVR.vrSQ, 'CT Position Sequence' );
     Add( $9327, TKindVR.vrFD, 'Table Position' );
     Add( $9328, TKindVR.vrFD, 'Exposure Time in ms' );
     Add( $9329, TKindVR.vrSQ, 'CT Image Frame Type Sequence' );
     Add( $9330, TKindVR.vrFD, 'X-Ray Tube Current in mA' );
     Add( $9332, TKindVR.vrFD, 'Exposure in mAs' );
     Add( $9333, TKindVR.vrCS, 'Constant Volume Flag' );
     Add( $9334, TKindVR.vrCS, 'Fluoroscopy Flag' );
     Add( $9335, TKindVR.vrFD, 'Distance Source to Data Collection Center' );
     Add( $9337, TKindVR.vrUS, 'Contrast/Bolus Agent Number' );
     Add( $9338, TKindVR.vrSQ, 'Contrast/Bolus Ingredient Code Sequence' );
     Add( $9340, TKindVR.vrSQ, 'Contrast Administration Profile Sequence' );
     Add( $9341, TKindVR.vrSQ, 'Contrast/Bolus Usage Sequence' );
     Add( $9342, TKindVR.vrCS, 'Contrast/Bolus Agent Administered' );
     Add( $9343, TKindVR.vrCS, 'Contrast/Bolus Agent Detected' );
     Add( $9344, TKindVR.vrCS, 'Contrast/Bolus Agent Phase' );
     Add( $9345, TKindVR.vrFD, 'CTDIvol' );
     Add( $9346, TKindVR.vrSQ, 'CTDI Phantom Type Code Sequence' );
     Add( $9351, TKindVR.vrFL, 'Calcium Scoring Mass Factor Patient' );
     Add( $9352, TKindVR.vrFL, 'Calcium Scoring Mass Factor Device' );
     Add( $9353, TKindVR.vrFL, 'Energy Weighting Factor' );
     Add( $9360, TKindVR.vrSQ, 'CT Additional X-Ray Source Sequence' );
     Add( $9401, TKindVR.vrSQ, 'Projection Pixel Calibration Sequence' );
     Add( $9402, TKindVR.vrFL, 'Distance Source to Isocenter' );
     Add( $9403, TKindVR.vrFL, 'Distance Object to Table Top' );
     Add( $9404, TKindVR.vrFL, 'Object Pixel Spacing in Center of Beam' );
     Add( $9405, TKindVR.vrSQ, 'Positioner Position Sequence' );
     Add( $9406, TKindVR.vrSQ, 'Table Position Sequence' );
     Add( $9407, TKindVR.vrSQ, 'Collimator Shape Sequence' );
     Add( $9410, TKindVR.vrCS, 'Planes in Acquisition' );
     Add( $9412, TKindVR.vrSQ, 'XA/XRF Frame Characteristics Sequence' );
     Add( $9417, TKindVR.vrSQ, 'Frame Acquisition Sequence' );
     Add( $9420, TKindVR.vrCS, 'X-Ray Receptor Type' );
     Add( $9423, TKindVR.vrLO, 'Acquisition Protocol Name' );
     Add( $9424, TKindVR.vrLT, 'Acquisition Protocol Description' );
     Add( $9425, TKindVR.vrCS, 'Contrast/Bolus Ingredient Opaque' );
     Add( $9426, TKindVR.vrFL, 'Distance Receptor Plane to Detector Housing' );
     Add( $9427, TKindVR.vrCS, 'Intensifier Active Shape' );
     Add( $9428, TKindVR.vrFL, 'Intensifier Active Dimension(s)' );
     Add( $9429, TKindVR.vrFL, 'Physical Detector Size' );
     Add( $9430, TKindVR.vrFL, 'Position of Isocenter Projection' );
     Add( $9432, TKindVR.vrSQ, 'Field of View Sequence' );
     Add( $9433, TKindVR.vrLO, 'Field of View Description' );
     Add( $9434, TKindVR.vrSQ, 'Exposure Control Sensing Regions Sequence' );
     Add( $9435, TKindVR.vrCS, 'Exposure Control Sensing Region Shape' );
     Add( $9436, TKindVR.vrSS, 'Exposure Control Sensing Region Left Vertical Edge' );
     Add( $9437, TKindVR.vrSS, 'Exposure Control Sensing Region Right Vertical Edge' );
     Add( $9438, TKindVR.vrSS, 'Exposure Control Sensing Region Upper Horizontal Edge' );
     Add( $9439, TKindVR.vrSS, 'Exposure Control Sensing Region Lower Horizontal Edge' );
     Add( $9440, TKindVR.vrSS, 'Center of Circular Exposure Control Sensing Region' );
     Add( $9441, TKindVR.vrUS, 'Radius of Circular Exposure Control Sensing Region' );
     Add( $9442, TKindVR.vrSS, 'Vertices of the Polygonal Exposure Control Sensing Region' );
     Add( $9445, TKindVR.vr00, '' );  //For some Data Elements, no Name or Keyword or VR or VM is specified; these are "placeholders" that are not assigned but will not be reused.
     Add( $9449, TKindVR.vrFL, 'Beam Angle' );
     Add( $9451, TKindVR.vrSQ, 'Frame Detector Parameters Sequence' );
     Add( $9452, TKindVR.vrFL, 'Calculated Anatomy Thickness' );
     Add( $9455, TKindVR.vrSQ, 'Calibration Sequence' );
     Add( $9456, TKindVR.vrSQ, 'Object Thickness Sequence' );
     Add( $9457, TKindVR.vrCS, 'Plane Identification' );
     Add( $9461, TKindVR.vrFL, 'Field of View Dimension(s) in Float' );
     Add( $9462, TKindVR.vrSQ, 'Isocenter Reference System Sequence' );
     Add( $9463, TKindVR.vrFL, 'Positioner Isocenter Primary Angle' );
     Add( $9464, TKindVR.vrFL, 'Positioner Isocenter Secondary Angle' );
     Add( $9465, TKindVR.vrFL, 'Positioner Isocenter Detector Rotation Angle' );
     Add( $9466, TKindVR.vrFL, 'Table X Position to Isocenter' );
     Add( $9467, TKindVR.vrFL, 'Table Y Position to Isocenter' );
     Add( $9468, TKindVR.vrFL, 'Table Z Position to Isocenter' );
     Add( $9469, TKindVR.vrFL, 'Table Horizontal Rotation Angle' );
     Add( $9470, TKindVR.vrFL, 'Table Head Tilt Angle' );
     Add( $9471, TKindVR.vrFL, 'Table Cradle Tilt Angle' );
     Add( $9472, TKindVR.vrSQ, 'Frame Display Shutter Sequence' );
     Add( $9473, TKindVR.vrFL, 'Acquired Image Area Dose Product' );
     Add( $9474, TKindVR.vrCS, 'C-arm Positioner Tabletop Relationship' );
     Add( $9476, TKindVR.vrSQ, 'X-Ray Geometry Sequence' );
     Add( $9477, TKindVR.vrSQ, 'Irradiation Event Identification Sequence' );
     Add( $9504, TKindVR.vrSQ, 'X-Ray 3D Frame Type Sequence' );
     Add( $9506, TKindVR.vrSQ, 'Contributing Sources Sequence' );
     Add( $9507, TKindVR.vrSQ, 'X-Ray 3D Acquisition Sequence' );
     Add( $9508, TKindVR.vrFL, 'Primary Positioner Scan Arc' );
     Add( $9509, TKindVR.vrFL, 'Secondary Positioner Scan Arc' );
     Add( $9510, TKindVR.vrFL, 'Primary Positioner Scan Start Angle' );
     Add( $9511, TKindVR.vrFL, 'Secondary Positioner Scan Start Angle' );
     Add( $9514, TKindVR.vrFL, 'Primary Positioner Increment' );
     Add( $9515, TKindVR.vrFL, 'Secondary Positioner Increment' );
     Add( $9516, TKindVR.vrDT, 'Start Acquisition DateTime' );
     Add( $9517, TKindVR.vrDT, 'End Acquisition DateTime' );
     Add( $9518, TKindVR.vrSS, 'Primary Positioner Increment Sign' );
     Add( $9519, TKindVR.vrSS, 'Secondary Positioner Increment Sign' );
     Add( $9524, TKindVR.vrLO, 'Application Name' );
     Add( $9525, TKindVR.vrLO, 'Application Version' );
     Add( $9526, TKindVR.vrLO, 'Application Manufacturer' );
     Add( $9527, TKindVR.vrCS, 'Algorithm Type' );
     Add( $9528, TKindVR.vrLO, 'Algorithm Description' );
     Add( $9530, TKindVR.vrSQ, 'X-Ray 3D Reconstruction Sequence' );
     Add( $9531, TKindVR.vrLO, 'Reconstruction Description' );
     Add( $9538, TKindVR.vrSQ, 'Per Projection Acquisition Sequence' );
     Add( $9541, TKindVR.vrSQ, 'Detector Position Sequence' );
     Add( $9542, TKindVR.vrSQ, 'X-Ray Acquisition Dose Sequence' );
     Add( $9543, TKindVR.vrFD, 'X-Ray Source Isocenter Primary Angle' );
     Add( $9544, TKindVR.vrFD, 'X-Ray Source Isocenter Secondary Angle' );
     Add( $9545, TKindVR.vrFD, 'Breast Support Isocenter Primary Angle' );
     Add( $9546, TKindVR.vrFD, 'Breast Support Isocenter Secondary Angle' );
     Add( $9547, TKindVR.vrFD, 'Breast Support X Position to Isocenter' );
     Add( $9548, TKindVR.vrFD, 'Breast Support Y Position to Isocenter' );
     Add( $9549, TKindVR.vrFD, 'Breast Support Z Position to Isocenter' );
     Add( $9550, TKindVR.vrFD, 'Detector Isocenter Primary Angle' );
     Add( $9551, TKindVR.vrFD, 'Detector Isocenter Secondary Angle' );
     Add( $9552, TKindVR.vrFD, 'Detector X Position to Isocenter' );
     Add( $9553, TKindVR.vrFD, 'Detector Y Position to Isocenter' );
     Add( $9554, TKindVR.vrFD, 'Detector Z Position to Isocenter' );
     Add( $9555, TKindVR.vrSQ, 'X-Ray Grid Sequence' );
     Add( $9556, TKindVR.vrSQ, 'X-Ray Filter Sequence' );
     Add( $9557, TKindVR.vrFD, 'Detector Active Area TLHC Position' );
     Add( $9558, TKindVR.vrFD, 'Detector Active Area Orientation' );
     Add( $9559, TKindVR.vrCS, 'Positioner Primary Angle Direction' );
     Add( $9601, TKindVR.vrSQ, 'Diffusion b-matrix Sequence' );
     Add( $9602, TKindVR.vrFD, 'Diffusion b-value XX' );
     Add( $9603, TKindVR.vrFD, 'Diffusion b-value XY' );
     Add( $9604, TKindVR.vrFD, 'Diffusion b-value XZ' );
     Add( $9605, TKindVR.vrFD, 'Diffusion b-value YY' );
     Add( $9606, TKindVR.vrFD, 'Diffusion b-value YZ' );
     Add( $9607, TKindVR.vrFD, 'Diffusion b-value ZZ' );
     Add( $9621, TKindVR.vrSQ, 'Functional MR Sequence' );
     Add( $9622, TKindVR.vrCS, 'Functional Settling Phase Frames Present' );
     Add( $9623, TKindVR.vrDT, 'Functional Sync Pulse' );
     Add( $9624, TKindVR.vrCS, 'Settling Phase Frame' );
     Add( $9701, TKindVR.vrDT, 'Decay Correction DateTime' );
     Add( $9715, TKindVR.vrFD, 'Start Density Threshold' );
     Add( $9716, TKindVR.vrFD, 'Start Relative Density Difference Threshold' );
     Add( $9717, TKindVR.vrFD, 'Start Cardiac Trigger Count Threshold' );
     Add( $9718, TKindVR.vrFD, 'Start Respiratory Trigger Count Threshold' );
     Add( $9719, TKindVR.vrFD, 'Termination Counts Threshold' );
     Add( $9720, TKindVR.vrFD, 'Termination Density Threshold' );
     Add( $9721, TKindVR.vrFD, 'Termination Relative Density Threshold' );
     Add( $9722, TKindVR.vrFD, 'Termination Time Threshold' );
     Add( $9723, TKindVR.vrFD, 'Termination Cardiac Trigger Count Threshold' );
     Add( $9724, TKindVR.vrFD, 'Termination Respiratory Trigger Count Threshold' );
     Add( $9725, TKindVR.vrCS, 'Detector Geometry' );
     Add( $9726, TKindVR.vrFD, 'Transverse Detector Separation' );
     Add( $9727, TKindVR.vrFD, 'Axial Detector Dimension' );
     Add( $9729, TKindVR.vrUS, 'Radiopharmaceutical Agent Number' );
     Add( $9732, TKindVR.vrSQ, 'PET Frame Acquisition Sequence' );
     Add( $9733, TKindVR.vrSQ, 'PET Detector Motion Details Sequence' );
     Add( $9734, TKindVR.vrSQ, 'PET Table Dynamics Sequence' );
     Add( $9735, TKindVR.vrSQ, 'PET Position Sequence' );
     Add( $9736, TKindVR.vrSQ, 'PET Frame Correction Factors Sequence' );
     Add( $9737, TKindVR.vrSQ, 'Radiopharmaceutical Usage Sequence' );
     Add( $9738, TKindVR.vrCS, 'Attenuation Correction Source' );
     Add( $9739, TKindVR.vrUS, 'Number of Iterations' );
     Add( $9740, TKindVR.vrUS, 'Number of Subsets' );
     Add( $9749, TKindVR.vrSQ, 'PET Reconstruction Sequence' );
     Add( $9751, TKindVR.vrSQ, 'PET Frame Type Sequence' );
     Add( $9755, TKindVR.vrCS, 'Time of Flight Information Used' );
     Add( $9756, TKindVR.vrCS, 'Reconstruction Type' );
     Add( $9758, TKindVR.vrCS, 'Decay Corrected' );
     Add( $9759, TKindVR.vrCS, 'Attenuation Corrected' );
     Add( $9760, TKindVR.vrCS, 'Scatter Corrected' );
     Add( $9761, TKindVR.vrCS, 'Dead Time Corrected' );
     Add( $9762, TKindVR.vrCS, 'Gantry Motion Corrected' );
     Add( $9763, TKindVR.vrCS, 'Patient Motion Corrected' );
     Add( $9764, TKindVR.vrCS, 'Count Loss Normalization Corrected' );
     Add( $9765, TKindVR.vrCS, 'Randoms Corrected' );
     Add( $9766, TKindVR.vrCS, 'Non-uniform Radial Sampling Corrected' );
     Add( $9767, TKindVR.vrCS, 'Sensitivity Calibrated' );
     Add( $9768, TKindVR.vrCS, 'Detector Normalization Correction' );
     Add( $9769, TKindVR.vrCS, 'Iterative Reconstruction Method' );
     Add( $9770, TKindVR.vrCS, 'Attenuation Correction Temporal Relationship' );
     Add( $9771, TKindVR.vrSQ, 'Patient Physiological State Sequence' );
     Add( $9772, TKindVR.vrSQ, 'Patient Physiological State Code Sequence' );
     Add( $9801, TKindVR.vrFD, 'Depth(s) of Focus' );
     Add( $9803, TKindVR.vrSQ, 'Excluded Intervals Sequence' );
     Add( $9804, TKindVR.vrDT, 'Exclusion Start DateTime' );
     Add( $9805, TKindVR.vrFD, 'Exclusion Duration' );
     Add( $9806, TKindVR.vrSQ, 'US Image Description Sequence' );
     Add( $9807, TKindVR.vrSQ, 'Image Data Type Sequence' );
     Add( $9808, TKindVR.vrCS, 'Data Type' );
     Add( $9809, TKindVR.vrSQ, 'Transducer Scan Pattern Code Sequence' );
     Add( $980B, TKindVR.vrCS, 'Aliased Data Type' );
     Add( $980C, TKindVR.vrCS, 'Position Measuring Device Used' );
     Add( $980D, TKindVR.vrSQ, 'Transducer Geometry Code Sequence' );
     Add( $980E, TKindVR.vrSQ, 'Transducer Beam Steering Code Sequence' );
     Add( $980F, TKindVR.vrSQ, 'Transducer Application Code Sequence' );
     Add( $9810, TKindVR.vrUSSS, 'Zero Velocity Pixel Value' );
     Add( $9900, TKindVR.vrLO, 'Reference Location Label' );
     Add( $9901, TKindVR.vrUT, 'Reference Location Description' );
     Add( $9902, TKindVR.vrSQ, 'Reference Basis Code Sequence' );
     Add( $9903, TKindVR.vrSQ, 'Reference Geometry Code Sequence' );
     Add( $9904, TKindVR.vrDS, 'Offset Distance' );
     Add( $9905, TKindVR.vrCS, 'Offset Direction' );
     Add( $9906, TKindVR.vrSQ, 'Potential Scheduled Protocol Code Sequence' );
     Add( $9907, TKindVR.vrSQ, 'Potential Requested Procedure Code Sequence' );
     Add( $9908, TKindVR.vrUC, 'Potential Reasons for Procedure' );
     Add( $9909, TKindVR.vrSQ, 'Potential Reasons for Procedure Code Sequence' );
     Add( $990A, TKindVR.vrUC, 'Potential Diagnostic Tasks' );
     Add( $990B, TKindVR.vrSQ, 'Contraindications Code Sequence' );
     Add( $990C, TKindVR.vrSQ, 'Referenced Defined Protocol Sequence' );
     Add( $990D, TKindVR.vrSQ, 'Referenced Performed Protocol Sequence' );
     Add( $990E, TKindVR.vrSQ, 'Predecessor Protocol Sequence' );
     Add( $990F, TKindVR.vrUT, 'Protocol Planning Information' );
     Add( $9910, TKindVR.vrUT, 'Protocol Design Rationale' );
     Add( $9911, TKindVR.vrSQ, 'Patient Specification Sequence' );
     Add( $9912, TKindVR.vrSQ, 'Model Specification Sequence' );
     Add( $9913, TKindVR.vrSQ, 'Parameters Specification Sequence' );
     Add( $9914, TKindVR.vrSQ, 'Instruction Sequence' );
     Add( $9915, TKindVR.vrUS, 'Instruction Index' );
     Add( $9916, TKindVR.vrLO, 'Instruction Text' );
     Add( $9917, TKindVR.vrUT, 'Instruction Description' );
     Add( $9918, TKindVR.vrCS, 'Instruction Performed Flag' );
     Add( $9919, TKindVR.vrDT, 'Instruction Performed DateTime' );
     Add( $991A, TKindVR.vrUT, 'Instruction Performance Comment' );
     Add( $991B, TKindVR.vrSQ, 'Patient Positioning Instruction Sequence' );
     Add( $991C, TKindVR.vrSQ, 'Positioning Method Code Sequence' );
     Add( $991D, TKindVR.vrSQ, 'Positioning Landmark Sequence' );
     Add( $991E, TKindVR.vrUI, 'Target Frame of Reference UID' );
     Add( $991F, TKindVR.vrSQ, 'Acquisition Protocol Element Specification Sequence' );
     Add( $9920, TKindVR.vrSQ, 'Acquisition Protocol Element Sequence' );
     Add( $9921, TKindVR.vrUS, 'Protocol Element Number' );
     Add( $9922, TKindVR.vrLO, 'Protocol Element Name' );
     Add( $9923, TKindVR.vrUT, 'Protocol Element Characteristics Summary' );
     Add( $9924, TKindVR.vrUT, 'Protocol Element Purpose' );
     Add( $9930, TKindVR.vrCS, 'Acquisition Motion' );
     Add( $9931, TKindVR.vrSQ, 'Acquisition Start Location Sequence' );
     Add( $9932, TKindVR.vrSQ, 'Acquisition End Location Sequence' );
     Add( $9933, TKindVR.vrSQ, 'Reconstruction Protocol Element Specification Sequence' );
     Add( $9934, TKindVR.vrSQ, 'Reconstruction Protocol Element Sequence' );
     Add( $9935, TKindVR.vrSQ, 'Storage Protocol Element Specification Sequence' );
     Add( $9936, TKindVR.vrSQ, 'Storage Protocol Element Sequence' );
     Add( $9937, TKindVR.vrLO, 'Requested Series Description' );
     Add( $9938, TKindVR.vrUS, 'Source Acquisition Protocol Element Number' );
     Add( $9939, TKindVR.vrUS, 'Source Acquisition Beam Number' );
     Add( $993A, TKindVR.vrUS, 'Source Reconstruction Protocol Element Number' );
     Add( $993B, TKindVR.vrSQ, 'Reconstruction Start Location Sequence' );
     Add( $993C, TKindVR.vrSQ, 'Reconstruction End Location Sequence' );
     Add( $993D, TKindVR.vrSQ, 'Reconstruction Algorithm Sequence' );
     Add( $993E, TKindVR.vrSQ, 'Reconstruction Target Center Location Sequence' );
     Add( $9941, TKindVR.vrUT, 'Image Filter Description' );
     Add( $9942, TKindVR.vrFD, 'CTDIvol Notification Trigger' );
     Add( $9943, TKindVR.vrFD, 'DLP Notification Trigger' );
     Add( $9944, TKindVR.vrCS, 'Auto KVP Selection Type' );
     Add( $9945, TKindVR.vrFD, 'Auto KVP Upper Bound' );
     Add( $9946, TKindVR.vrFD, 'Auto KVP Lower Bound' );
     Add( $9947, TKindVR.vrCS, 'Protocol Defined Patient Position' );
     Add( $A001, TKindVR.vrSQ, 'Contributing Equipment Sequence' );
     Add( $A002, TKindVR.vrDT, 'Contribution DateTime' );
     Add( $A003, TKindVR.vrST, 'Contribution Description' );
end;

//$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$【ルーチン】

//############################################################################## □

initialization //$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$ 初期化

finalization //$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$ 最終化

end. //######################################################################### ■
